%% GENERATED by ggen from the admitted bpm:RecordType graph. Do not edit.
%%
%% Real EUnit tests for the pure-reflection beam4pm_types_manifest module.
%% No mocks: every expected list is a literal built from the same admitted
%% bpm:RecordType graph at generation time, then compared against the real
%% return value of the generated module under test.

-module(beam4pm_types_manifest_tests).

-include_lib("eunit/include/eunit.hrl").

%% No explicit -export here: EUnit's own parse transform auto-exports every
%% *_test/0 function in this module, and an explicit -export of the same
%% functions produces a real "already exported" compiler warning (which
%% would become a hard failure under warnings_as_errors).

record_names_count_test() ->
    ?assertEqual(185, length(beam4pm_types_manifest:record_names())).

account_discovery_fields_test() ->
    ?assertEqual([account_discovery_id, account_id, discovery_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(account_discovery)).

account_master_match_fields_test() ->
    ?assertEqual([source_account_id, canonical_account_id, match_evidence_hash], beam4pm_types_manifest:fields(account_master_match)).

account_parent_scope_fields_test() ->
    ?assertEqual([account_id, parent_account_id, scope_evidence_hash], beam4pm_types_manifest:fields(account_parent_scope)).

activation_event_fields_test() ->
    ?assertEqual([activation_event_id, account_id, activation_type, evidence_digest, observed_at], beam4pm_types_manifest:fields(activation_event)).

add_on_bundle_fields_test() ->
    ?assertEqual([add_on_id, name, capability_ids, status], beam4pm_types_manifest:fields(add_on_bundle)).

adoption_milestone_fields_test() ->
    ?assertEqual([adoption_milestone_id, account_id, milestone_name, evidence_digest, observed_at], beam4pm_types_manifest:fields(adoption_milestone)).

alignment_move_fields_test() ->
    ?assertEqual([move_type, cost], beam4pm_types_manifest:fields(alignment_move)).

annual_subscription_fields_test() ->
    ?assertEqual([subscription_id, sku, seat_count, renews_at], beam4pm_types_manifest:fields(annual_subscription)).

architecture_readiness_fields_test() ->
    ?assertEqual([architecture_readiness_id, account_id, architecture_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(architecture_readiness)).

baseline_metric_fields_test() ->
    ?assertEqual([baseline_metric_id, account_id, baseline_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(baseline_metric)).

beneficial_owner_evidence_fields_test() ->
    ?assertEqual([account_id, owner_id, evidence_hash], beam4pm_types_manifest:fields(beneficial_owner_evidence)).

billing_account_fields_test() ->
    ?assertEqual([billing_account_id, account_id, currency, invoice_profile], beam4pm_types_manifest:fields(billing_account)).

billing_reconciliation_fields_test() ->
    ?assertEqual([entitlement_id, metric_name, total_quantity, applied_event_ids, period_start, period_end], beam4pm_types_manifest:fields(billing_reconciliation)).

booking_readiness_fields_test() ->
    ?assertEqual([opportunity_id, readiness_id, decision], beam4pm_types_manifest:fields(booking_readiness)).

budget_period_alignment_fields_test() ->
    ?assertEqual([opportunity_id, budget_period, alignment_result], beam4pm_types_manifest:fields(budget_period_alignment)).

buying_committee_fields_test() ->
    ?assertEqual([buying_committee_id, account_id, committee_coverage, evidence_digest, observed_at], beam4pm_types_manifest:fields(buying_committee)).

canary_decision_fields_test() ->
    ?assertEqual([canary_decision_id, account_id, canary_result, evidence_digest, observed_at], beam4pm_types_manifest:fields(canary_decision)).

capability_bundle_fields_test() ->
    ?assertEqual([bundle_id, name, capability_ids, version], beam4pm_types_manifest:fields(capability_bundle)).

capability_gap_fields_test() ->
    ?assertEqual([capability_gap_id, account_id, gap_severity, evidence_digest, observed_at], beam4pm_types_manifest:fields(capability_gap)).

case_stats_fields_test() ->
    ?assertEqual([case_id, event_count, duration_seconds], beam4pm_types_manifest:fields(case_stats)).

catalog_release_fields_test() ->
    ?assertEqual([release_id, version, sku_ids, effective_at], beam4pm_types_manifest:fields(catalog_release)).

change_order_authority_fields_test() ->
    ?assertEqual([opportunity_id, authority_id, evidence_hash], beam4pm_types_manifest:fields(change_order_authority)).

channel_agreement_fields_test() ->
    ?assertEqual([agreement_id, partner_id, territory, valid_until], beam4pm_types_manifest:fields(channel_agreement)).

chargeback_rule_fields_test() ->
    ?assertEqual([rule_id, cost_center, metric_name, rate], beam4pm_types_manifest:fields(chargeback_rule)).

commercial_approval_fields_test() ->
    ?assertEqual([approval_id, quote_id, authority, status], beam4pm_types_manifest:fields(commercial_approval)).

commercial_exception_fields_test() ->
    ?assertEqual([opportunity_id, exception_id, exception_state], beam4pm_types_manifest:fields(commercial_exception)).

commercial_execution_receipt_fields_test() ->
    ?assertEqual([receipt_id, subject_id, operation, evidence_hash], beam4pm_types_manifest:fields(commercial_execution_receipt)).

commercial_forecast_fields_test() ->
    ?assertEqual([forecast_id, account_id, amount, confidence], beam4pm_types_manifest:fields(commercial_forecast)).

commercial_outcome_fields_test() ->
    ?assertEqual([commercial_outcome_id, account_id, outcome_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(commercial_outcome)).

commercial_quote_fields_test() ->
    ?assertEqual([quote_id, account_id, currency, status], beam4pm_types_manifest:fields(commercial_quote)).

commercial_quote_line_fields_test() ->
    ?assertEqual([quote_id, sku, quantity, unit_price], beam4pm_types_manifest:fields(commercial_quote_line)).

commercial_value_realization_fields_test() ->
    ?assertEqual([realization_id, baseline_id, realized_value, measured_at], beam4pm_types_manifest:fields(commercial_value_realization)).

committed_spend_fields_test() ->
    ?assertEqual([commitment_id, amount, currency, expires_at], beam4pm_types_manifest:fields(committed_spend)).

committed_spend_admission_fields_test() ->
    ?assertEqual([opportunity_id, commitment_id, decision], beam4pm_types_manifest:fields(committed_spend_admission)).

compatibility_contract_fields_test() ->
    ?assertEqual([contract_id, product_version, schema_version, api_version], beam4pm_types_manifest:fields(compatibility_contract)).

configuration_export_fields_test() ->
    ?assertEqual([export_id, tenant_id, configuration_hash, exported_at], beam4pm_types_manifest:fields(configuration_export)).

configuration_import_fields_test() ->
    ?assertEqual([import_id, tenant_id, configuration_hash, status], beam4pm_types_manifest:fields(configuration_import)).

conformance_result_fields_test() ->
    ?assertEqual([trace_id, fitness, precision], beam4pm_types_manifest:fields(conformance_result)).

consumption_pool_fields_test() ->
    ?assertEqual([pool_id, account_id, unit, remaining_quantity], beam4pm_types_manifest:fields(consumption_pool)).

consumption_subscription_fields_test() ->
    ?assertEqual([subscription_id, account_id, plan_id, status], beam4pm_types_manifest:fields(consumption_subscription)).

contracting_entity_identity_fields_test() ->
    ?assertEqual([opportunity_id, contracting_entity_id, identity_evidence_hash], beam4pm_types_manifest:fields(contracting_entity_identity)).

credit_risk_admission_fields_test() ->
    ?assertEqual([account_id, risk_band, decision], beam4pm_types_manifest:fields(credit_risk_admission)).

cross_sell_fit_fields_test() ->
    ?assertEqual([cross_sell_fit_id, account_id, cross_sell_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(cross_sell_fit)).

customer_health_fields_test() ->
    ?assertEqual([customer_health_id, account_id, health_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(customer_health)).

data_migration_scope_admission_fields_test() ->
    ?assertEqual([opportunity_id, migration_scope_id, decision], beam4pm_types_manifest:fields(data_migration_scope_admission)).

data_processing_addendum_state_fields_test() ->
    ?assertEqual([opportunity_id, addendum_id, addendum_state], beam4pm_types_manifest:fields(data_processing_addendum_state)).

data_readiness_fields_test() ->
    ?assertEqual([data_readiness_id, account_id, data_quality_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(data_readiness)).

data_residency_policy_fields_test() ->
    ?assertEqual([policy_id, tenant_id, allowed_regions, status], beam4pm_types_manifest:fields(data_residency_policy)).

deal_desk_packet_fields_test() ->
    ?assertEqual([opportunity_id, packet_id, evidence_hash], beam4pm_types_manifest:fields(deal_desk_packet)).

demo_run_fields_test() ->
    ?assertEqual([demo_run_id, account_id, demo_result, evidence_digest, observed_at], beam4pm_types_manifest:fields(demo_run)).

demo_scenario_fields_test() ->
    ?assertEqual([demo_scenario_id, account_id, scenario_name, evidence_digest, observed_at], beam4pm_types_manifest:fields(demo_scenario)).

deployment_entitlement_fields_test() ->
    ?assertEqual([entitlement_id, tenant_id, profile_id, valid_until], beam4pm_types_manifest:fields(deployment_entitlement)).

developer_readiness_fields_test() ->
    ?assertEqual([developer_readiness_id, account_id, developer_readiness_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(developer_readiness)).

dfg_edge_fields_test() ->
    ?assertEqual([source_activity, target_activity, frequency], beam4pm_types_manifest:fields(dfg_edge)).

discount_schedule_fields_test() ->
    ?assertEqual([schedule_id, threshold, discount_percent, currency], beam4pm_types_manifest:fields(discount_schedule)).

discovery_hypothesis_fields_test() ->
    ?assertEqual([discovery_hypothesis_id, account_id, expected_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(discovery_hypothesis)).

edition_definition_fields_test() ->
    ?assertEqual([edition_id, name, bundle_ids, support_tier], beam4pm_types_manifest:fields(edition_definition)).

enterprise_order_fields_test() ->
    ?assertEqual([order_id, account_id, quote_id, status], beam4pm_types_manifest:fields(enterprise_order)).

enterprise_order_line_fields_test() ->
    ?assertEqual([order_id, sku, quantity, unit_price], beam4pm_types_manifest:fields(enterprise_order_line)).

entitlement_event_fields_test() ->
    ?assertEqual([event_id, entitlement_id, event_type, effective_at, payload], beam4pm_types_manifest:fields(entitlement_event)).

entitlement_grant_fields_test() ->
    ?assertEqual([grant_id, tenant_id, capability_id, valid_until], beam4pm_types_manifest:fields(entitlement_grant)).

entitlement_revocation_fields_test() ->
    ?assertEqual([revocation_id, grant_id, reason, revoked_at], beam4pm_types_manifest:fields(entitlement_revocation)).

entitlement_state_fields_test() ->
    ?assertEqual([entitlement_id, status, last_applied_event_id, updated_at], beam4pm_types_manifest:fields(entitlement_state)).

environment_profile_fields_test() ->
    ?assertEqual([profile_id, environment, region, configuration_hash], beam4pm_types_manifest:fields(environment_profile)).

event_log_fields_test() ->
    ?assertEqual([log_id, name, description], beam4pm_types_manifest:fields(event_log)).

event_type_fields_test() ->
    ?assertEqual([type_name, attribute_names], beam4pm_types_manifest:fields(event_type)).

exception_authority_fields_test() ->
    ?assertEqual([exception_id, authority_id, decision], beam4pm_types_manifest:fields(exception_authority)).

executive_business_review_fields_test() ->
    ?assertEqual([executive_business_review_id, account_id, executive_outcome, evidence_digest, observed_at], beam4pm_types_manifest:fields(executive_business_review)).

executive_sponsor_fields_test() ->
    ?assertEqual([executive_sponsor_id, account_id, sponsor_commitment, evidence_digest, observed_at], beam4pm_types_manifest:fields(executive_sponsor)).

expansion_opportunity_fields_test() ->
    ?assertEqual([expansion_opportunity_id, account_id, expansion_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(expansion_opportunity)).

expansion_option_fields_test() ->
    ?assertEqual([option_id, account_id, sku, max_quantity], beam4pm_types_manifest:fields(expansion_option)).

expansion_receipt_fields_test() ->
    ?assertEqual([expansion_receipt_id, account_id, receipt_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(expansion_receipt)).

expansion_signal_fields_test() ->
    ?assertEqual([expansion_signal_id, account_id, expansion_signal_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(expansion_signal)).

funding_approval_chain_fields_test() ->
    ?assertEqual([opportunity_id, approval_chain_id, evidence_hash], beam4pm_types_manifest:fields(funding_approval_chain)).

heuristic_arc_fields_test() ->
    ?assertEqual([source_activity, target_activity, dependency_measure], beam4pm_types_manifest:fields(heuristic_arc)).

implementation_fee_admission_fields_test() ->
    ?assertEqual([opportunity_id, fee_id, decision], beam4pm_types_manifest:fields(implementation_fee_admission)).

indemnity_scope_admission_fields_test() ->
    ?assertEqual([opportunity_id, indemnity_scope_id, decision], beam4pm_types_manifest:fields(indemnity_scope_admission)).

insurance_requirement_fields_test() ->
    ?assertEqual([opportunity_id, coverage_id, evidence_hash], beam4pm_types_manifest:fields(insurance_requirement)).

integration_readiness_fields_test() ->
    ?assertEqual([integration_readiness_id, account_id, integration_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(integration_readiness)).

integration_scope_admission_fields_test() ->
    ?assertEqual([opportunity_id, integration_scope_id, decision], beam4pm_types_manifest:fields(integration_scope_admission)).

invoice_entity_identity_fields_test() ->
    ?assertEqual([opportunity_id, invoice_entity_id, identity_evidence_hash], beam4pm_types_manifest:fields(invoice_entity_identity)).

invoice_schedule_fields_test() ->
    ?assertEqual([schedule_id, billing_account_id, cadence, next_invoice_at], beam4pm_types_manifest:fields(invoice_schedule)).

k8s_object_ref_fields_test() ->
    ?assertEqual([kind, name, namespace], beam4pm_types_manifest:fields(k8s_object_ref)).

legal_blocker_fields_test() ->
    ?assertEqual([opportunity_id, blocker_id, refusal_code], beam4pm_types_manifest:fields(legal_blocker)).

liability_cap_admission_fields_test() ->
    ?assertEqual([opportunity_id, liability_cap_id, decision], beam4pm_types_manifest:fields(liability_cap_admission)).

log_trace_fields_test() ->
    ?assertEqual([case_id, activity_sequence], beam4pm_types_manifest:fields(log_trace)).

master_service_agreement_state_fields_test() ->
    ?assertEqual([opportunity_id, agreement_id, agreement_state], beam4pm_types_manifest:fields(master_service_agreement_state)).

migration_contract_fields_test() ->
    ?assertEqual([migration_id, from_version, to_version, rollback_plan], beam4pm_types_manifest:fields(migration_contract)).

migration_readiness_fields_test() ->
    ?assertEqual([migration_readiness_id, account_id, migration_effort_days, evidence_digest, observed_at], beam4pm_types_manifest:fields(migration_readiness)).

minimum_term_admission_fields_test() ->
    ?assertEqual([opportunity_id, minimum_term, decision], beam4pm_types_manifest:fields(minimum_term_admission)).

object_attribute_change_fields_test() ->
    ?assertEqual([object_id, attribute_name, old_value, new_value, changed_at], beam4pm_types_manifest:fields(object_attribute_change)).

object_type_fields_test() ->
    ?assertEqual([type_name, attribute_names], beam4pm_types_manifest:fields(object_type)).

objection_fields_test() ->
    ?assertEqual([objection_id, account_id, objection_type, evidence_digest, observed_at], beam4pm_types_manifest:fields(objection)).

objection_resolution_fields_test() ->
    ?assertEqual([objection_resolution_id, account_id, resolution_status, evidence_digest, observed_at], beam4pm_types_manifest:fields(objection_resolution)).

oc_declare_constraint_fields_test() ->
    ?assertEqual([constraint_id, source_activity, target_activity, constraint_type], beam4pm_types_manifest:fields(oc_declare_constraint)).

ocel_attribute_fields_test() ->
    ?assertEqual([attribute_name, attribute_value, recorded_at], beam4pm_types_manifest:fields(ocel_attribute)).

ocel_event_fields_test() ->
    ?assertEqual([event_id, event_type, event_time, attributes], beam4pm_types_manifest:fields(ocel_event)).

ocel_object_fields_test() ->
    ?assertEqual([object_id, object_type, attributes], beam4pm_types_manifest:fields(ocel_object)).

ocel_relationship_fields_test() ->
    ?assertEqual([qualifier, object_id], beam4pm_types_manifest:fields(ocel_relationship)).

operator_readiness_fields_test() ->
    ?assertEqual([operator_readiness_id, account_id, operator_readiness_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(operator_readiness)).

opportunity_currency_contract_fields_test() ->
    ?assertEqual([opportunity_id, currency_code, fx_basis_id], beam4pm_types_manifest:fields(opportunity_currency_contract)).

opportunity_value_range_fields_test() ->
    ?assertEqual([opportunity_id, minimum_value, maximum_value], beam4pm_types_manifest:fields(opportunity_value_range)).

order_form_admission_fields_test() ->
    ?assertEqual([opportunity_id, order_form_id, decision], beam4pm_types_manifest:fields(order_form_admission)).

overage_policy_fields_test() ->
    ?assertEqual([policy_id, quota_id, unit_price, behavior], beam4pm_types_manifest:fields(overage_policy)).

path_schema_fields_test() ->
    ?assertEqual([schema_id, source_type, target_type, support], beam4pm_types_manifest:fields(path_schema)).

path_schema_query_fields_test() ->
    ?assertEqual([source_type, target_type, max_length], beam4pm_types_manifest:fields(path_schema_query)).

payment_terms_fields_test() ->
    ?assertEqual([terms_id, net_days, late_policy, status], beam4pm_types_manifest:fields(payment_terms)).

payment_terms_admission_fields_test() ->
    ?assertEqual([opportunity_id, payment_terms, authority_evidence_hash], beam4pm_types_manifest:fields(payment_terms_admission)).

petri_arc_fields_test() ->
    ?assertEqual([source_id, target_id, weight], beam4pm_types_manifest:fields(petri_arc)).

petri_place_fields_test() ->
    ?assertEqual([place_id, tokens], beam4pm_types_manifest:fields(petri_place)).

petri_transition_fields_test() ->
    ?assertEqual([transition_id, label], beam4pm_types_manifest:fields(petri_transition)).

planning_action_fields_test() ->
    ?assertEqual([action_name, preconditions, effects], beam4pm_types_manifest:fields(planning_action)).

planning_state_fields_test() ->
    ?assertEqual([state_id, facts], beam4pm_types_manifest:fields(planning_state)).

poc_exit_criteria_fields_test() ->
    ?assertEqual([poc_exit_criteria_id, account_id, criteria_pass_rate, evidence_digest, observed_at], beam4pm_types_manifest:fields(poc_exit_criteria)).

poc_risk_fields_test() ->
    ?assertEqual([poc_risk_id, account_id, risk_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(poc_risk)).

poc_scope_fields_test() ->
    ?assertEqual([poc_scope_id, account_id, use_case_count, evidence_digest, observed_at], beam4pm_types_manifest:fields(poc_scope)).

poc_timeline_fields_test() ->
    ?assertEqual([poc_timeline_id, account_id, days_to_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(poc_timeline)).

policy_decision_fields_test() ->
    ?assertEqual([decision_id, verdict, reason], beam4pm_types_manifest:fields(policy_decision)).

pricing_basis_contract_fields_test() ->
    ?assertEqual([opportunity_id, pricing_basis_id, evidence_hash], beam4pm_types_manifest:fields(pricing_basis_contract)).

private_offer_fields_test() ->
    ?assertEqual([offer_id, account_id, total_price, expires_at], beam4pm_types_manifest:fields(private_offer)).

process_variant_fields_test() ->
    ?assertEqual([variant_id, activity_sequence, frequency], beam4pm_types_manifest:fields(process_variant)).

procurement_blocker_fields_test() ->
    ?assertEqual([opportunity_id, blocker_id, refusal_code], beam4pm_types_manifest:fields(procurement_blocker)).

procurement_channel_selection_fields_test() ->
    ?assertEqual([opportunity_id, channel_id, selection_evidence_hash], beam4pm_types_manifest:fields(procurement_channel_selection)).

procurement_readiness_fields_test() ->
    ?assertEqual([procurement_readiness_id, account_id, procurement_stage, evidence_digest, observed_at], beam4pm_types_manifest:fields(procurement_readiness)).

production_readiness_fields_test() ->
    ?assertEqual([production_readiness_id, account_id, production_readiness_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(production_readiness)).

proof_of_value_budget_fields_test() ->
    ?assertEqual([opportunity_id, budget_id, decision], beam4pm_types_manifest:fields(proof_of_value_budget)).

proof_of_value_exit_gate_fields_test() ->
    ?assertEqual([pov_id, exit_gate_id, decision], beam4pm_types_manifest:fields(proof_of_value_exit_gate)).

purchase_order_binding_fields_test() ->
    ?assertEqual([binding_id, order_id, purchase_order_number, status], beam4pm_types_manifest:fields(purchase_order_binding)).

purchase_order_requirement_fields_test() ->
    ?assertEqual([opportunity_id, requirement_id, evidence_hash], beam4pm_types_manifest:fields(purchase_order_requirement)).

purchasing_entity_identity_fields_test() ->
    ?assertEqual([opportunity_id, purchasing_entity_id, identity_evidence_hash], beam4pm_types_manifest:fields(purchasing_entity_identity)).

queue_snapshot_fields_test() ->
    ?assertEqual([queue_name, depth, observed_at], beam4pm_types_manifest:fields(queue_snapshot)).

quota_policy_fields_test() ->
    ?assertEqual([quota_id, metric_name, limit, window], beam4pm_types_manifest:fields(quota_policy)).

ramp_commitment_fields_test() ->
    ?assertEqual([ramp_id, phase, committed_amount, effective_at], beam4pm_types_manifest:fields(ramp_commitment)).

recovery_plan_fields_test() ->
    ?assertEqual([recovery_plan_id, account_id, recovery_time_hours, evidence_digest, observed_at], beam4pm_types_manifest:fields(recovery_plan)).

renewal_evidence_fields_test() ->
    ?assertEqual([renewal_evidence_id, account_id, renewal_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(renewal_evidence)).

renewal_health_fields_test() ->
    ?assertEqual([renewal_health_id, account_id, renewal_health_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(renewal_health)).

renewal_option_fields_test() ->
    ?assertEqual([option_id, subscription_id, term_months, notice_by], beam4pm_types_manifest:fields(renewal_option)).

renewal_risk_fields_test() ->
    ?assertEqual([renewal_risk_id, account_id, renewal_risk_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(renewal_risk)).

renewal_term_admission_fields_test() ->
    ?assertEqual([opportunity_id, renewal_term, decision], beam4pm_types_manifest:fields(renewal_term_admission)).

reseller_authorization_fields_test() ->
    ?assertEqual([authorization_id, reseller_id, sku, status], beam4pm_types_manifest:fields(reseller_authorization)).

resource_allocation_fields_test() ->
    ?assertEqual([resource_id, activity, event_id], beam4pm_types_manifest:fields(resource_allocation)).

revenue_attribution_fields_test() ->
    ?assertEqual([revenue_attribution_id, account_id, attributed_revenue, evidence_digest, observed_at], beam4pm_types_manifest:fields(revenue_attribution)).

revenue_contract_admission_fields_test() ->
    ?assertEqual([opportunity_id, contract_id, admission_receipt_hash], beam4pm_types_manifest:fields(revenue_contract_admission)).

revenue_schedule_assumption_fields_test() ->
    ?assertEqual([opportunity_id, schedule_id, assumption_evidence_hash], beam4pm_types_manifest:fields(revenue_schedule_assumption)).

rollback_decision_fields_test() ->
    ?assertEqual([rollback_decision_id, account_id, rollback_result, evidence_digest, observed_at], beam4pm_types_manifest:fields(rollback_decision)).

sanctions_screening_result_fields_test() ->
    ?assertEqual([account_id, screening_id, screening_result], beam4pm_types_manifest:fields(sanctions_screening_result)).

security_addendum_state_fields_test() ->
    ?assertEqual([opportunity_id, addendum_id, addendum_state], beam4pm_types_manifest:fields(security_addendum_state)).

security_blocker_fields_test() ->
    ?assertEqual([opportunity_id, blocker_id, refusal_code], beam4pm_types_manifest:fields(security_blocker)).

security_readiness_fields_test() ->
    ?assertEqual([security_readiness_id, account_id, control_coverage, evidence_digest, observed_at], beam4pm_types_manifest:fields(security_readiness)).

service_credit_fields_test() ->
    ?assertEqual([credit_id, slo_id, amount, currency], beam4pm_types_manifest:fields(service_credit)).

service_credit_admission_fields_test() ->
    ?assertEqual([opportunity_id, service_credit_id, decision], beam4pm_types_manifest:fields(service_credit_admission)).

service_level_objective_fields_test() ->
    ?assertEqual([slo_id, contract_id, target_percent, measurement_window], beam4pm_types_manifest:fields(service_level_objective)).

service_span_fields_test() ->
    ?assertEqual([span_id, service_name, duration_ms, parent_span_id], beam4pm_types_manifest:fields(service_span)).

showback_allocation_fields_test() ->
    ?assertEqual([allocation_id, project_id, metric_name, quantity], beam4pm_types_manifest:fields(showback_allocation)).

sku_definition_fields_test() ->
    ?assertEqual([sku, edition_id, billing_model, status], beam4pm_types_manifest:fields(sku_definition)).

sla_offer_admission_fields_test() ->
    ?assertEqual([opportunity_id, sla_offer_id, decision], beam4pm_types_manifest:fields(sla_offer_admission)).

sojourn_time_fields_test() ->
    ?assertEqual([object_id, event_type, seconds], beam4pm_types_manifest:fields(sojourn_time)).

solution_fit_fields_test() ->
    ?assertEqual([solution_fit_id, account_id, fit_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(solution_fit)).

stakeholder_map_fields_test() ->
    ?assertEqual([stakeholder_map_id, account_id, stakeholder_count, evidence_digest, observed_at], beam4pm_types_manifest:fields(stakeholder_map)).

success_plan_fields_test() ->
    ?assertEqual([success_plan_id, account_id, success_target, evidence_digest, observed_at], beam4pm_types_manifest:fields(success_plan)).

support_contract_fields_test() ->
    ?assertEqual([contract_id, account_id, tier, valid_until], beam4pm_types_manifest:fields(support_contract)).

support_readiness_fields_test() ->
    ?assertEqual([support_readiness_id, account_id, support_readiness_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(support_readiness)).

support_tier_admission_fields_test() ->
    ?assertEqual([opportunity_id, support_tier_id, decision], beam4pm_types_manifest:fields(support_tier_admission)).

sync_time_fields_test() ->
    ?assertEqual([object_id, delaying_object_id, seconds], beam4pm_types_manifest:fields(sync_time)).

target_metric_fields_test() ->
    ?assertEqual([target_metric_id, account_id, target_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(target_metric)).

tax_jurisdiction_evidence_fields_test() ->
    ?assertEqual([contracting_entity_id, tax_jurisdiction, evidence_hash], beam4pm_types_manifest:fields(tax_jurisdiction_evidence)).

technical_blocker_fields_test() ->
    ?assertEqual([opportunity_id, blocker_id, refusal_code], beam4pm_types_manifest:fields(technical_blocker)).

tenant_account_fields_test() ->
    ?assertEqual([tenant_id, account_id, home_region, edition_id], beam4pm_types_manifest:fields(tenant_account)).

tenant_project_fields_test() ->
    ?assertEqual([project_id, tenant_id, cost_center, status], beam4pm_types_manifest:fields(tenant_project)).

term_subscription_fields_test() ->
    ?assertEqual([subscription_id, sku, starts_at, ends_at], beam4pm_types_manifest:fields(term_subscription)).

termination_right_admission_fields_test() ->
    ?assertEqual([opportunity_id, termination_right_id, decision], beam4pm_types_manifest:fields(termination_right_admission)).

time_to_value_fields_test() ->
    ?assertEqual([time_to_value_id, account_id, verified_days, evidence_digest, observed_at], beam4pm_types_manifest:fields(time_to_value)).

training_readiness_fields_test() ->
    ?assertEqual([training_readiness_id, account_id, training_completion_rate, evidence_digest, observed_at], beam4pm_types_manifest:fields(training_readiness)).

training_scope_admission_fields_test() ->
    ?assertEqual([opportunity_id, training_scope_id, decision], beam4pm_types_manifest:fields(training_scope_admission)).

true_up_policy_fields_test() ->
    ?assertEqual([policy_id, commitment_id, cadence, shortfall_behavior], beam4pm_types_manifest:fields(true_up_policy)).

type_edge_fields_test() ->
    ?assertEqual([source_type, target_type, qualifier, direction], beam4pm_types_manifest:fields(type_edge)).

upsell_readiness_fields_test() ->
    ?assertEqual([upsell_readiness_id, account_id, upsell_score, evidence_digest, observed_at], beam4pm_types_manifest:fields(upsell_readiness)).

usage_event_fields_test() ->
    ?assertEqual([event_id, entitlement_id, quantity, metric_name, occurred_at], beam4pm_types_manifest:fields(usage_event)).

usage_plan_fields_test() ->
    ?assertEqual([plan_id, metric_name, unit, billing_mode], beam4pm_types_manifest:fields(usage_plan)).

usage_signal_fields_test() ->
    ?assertEqual([usage_signal_id, account_id, active_user_count, evidence_digest, observed_at], beam4pm_types_manifest:fields(usage_signal)).

value_baseline_fields_test() ->
    ?assertEqual([baseline_id, account_id, metric_name, baseline_value], beam4pm_types_manifest:fields(value_baseline)).

value_driver_fields_test() ->
    ?assertEqual([value_driver_id, account_id, annual_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(value_driver)).

value_realization_fields_test() ->
    ?assertEqual([value_realization_id, account_id, realized_value, evidence_digest, observed_at], beam4pm_types_manifest:fields(value_realization)).

vendor_registration_state_fields_test() ->
    ?assertEqual([account_id, registration_id, registration_state], beam4pm_types_manifest:fields(vendor_registration_state)).

volume_tier_admission_fields_test() ->
    ?assertEqual([opportunity_id, volume_tier_id, decision], beam4pm_types_manifest:fields(volume_tier_admission)).

