# GENERATED by ggen from the admitted bpm:RecordType graph. Do not edit.
defmodule BeamPM.DiscoveryTest do
  use ExUnit.Case, async: true

  alias BeamPM.Discovery
  alias BeamPM.Types.ConformanceResult
  alias BeamPM.Types.DfgEdge
  alias BeamPM.Types.LogTrace
  alias BeamPM.Types.OcelEvent

  @case_attr_key "case_id"

  defp event!(event_id, event_type, event_time, attributes) do
    {:ok, event} =
      OcelEvent.new(%{
        event_id: event_id,
        event_type: event_type,
        event_time: event_time,
        attributes: attributes
      })

    event
  end

  defp trace!(case_id, activity_sequence) do
    {:ok, trace} = LogTrace.new(%{case_id: case_id, activity_sequence: activity_sequence})
    trace
  end

  # Seeded known log (shared with the Erlang discovery tests): 3 cases plus
  # one event whose attributes lack the case attribute key. The input list is
  # deliberately shuffled, and c2's two events share the same timestamp so the
  # event_id tie-break is exercised.
  defp seeded_events do
    [
      event!("e5", "approve", "2026-08-29T12:02:00Z", %{"case_id" => "c1"}),
      event!("e1", "receive", "2026-08-29T12:00:00Z", %{"case_id" => "c1"}),
      event!("e4", "validate", "2026-08-29T12:00:00Z", %{"case_id" => "c2"}),
      event!("e2", "validate", "2026-08-29T12:01:00Z", %{"case_id" => "c1"}),
      event!("e3", "receive", "2026-08-29T12:00:00Z", %{"case_id" => "c2"}),
      event!("e6", "receive", "2026-08-29T12:00:00Z", %{"case_id" => "c3"}),
      event!("e7", "orphan", "2026-08-29T12:03:00Z", %{"other" => "x"})
    ]
  end

  defp seeded_edges do
    seeded_events()
    |> Discovery.traces_from_events(@case_attr_key)
    |> Discovery.dfg_from_traces()
  end

  test "traces_from_events/2 groups, sorts, tie-breaks, and skips events missing the case attribute" do
    traces = Discovery.traces_from_events(seeded_events(), @case_attr_key)

    assert [
             %LogTrace{case_id: "c1", activity_sequence: ["receive", "validate", "approve"]},
             %LogTrace{case_id: "c2", activity_sequence: ["receive", "validate"]},
             %LogTrace{case_id: "c3", activity_sequence: ["receive"]}
           ] = traces

    refute Enum.any?(traces, fn trace -> "orphan" in trace.activity_sequence end)
  end

  test "dfg_from_traces/1 counts exact directly-follows edge frequencies, sorted by source then target" do
    assert [
             %DfgEdge{source_activity: "receive", target_activity: "validate", frequency: 2},
             %DfgEdge{source_activity: "validate", target_activity: "approve", frequency: 1}
           ] = seeded_edges()
  end

  test "conformance/2 fitness is exactly 1.0 (a float) for a fully fitting trace" do
    result = Discovery.conformance(seeded_edges(), trace!("c1", ["receive", "validate", "approve"]))

    assert %ConformanceResult{trace_id: "c1", fitness: fitness, precision: nil} = result
    assert fitness === 1.0
  end

  test "conformance/2 fitness is exactly 0.5 when one of two adjacent pairs is unknown" do
    result = Discovery.conformance(seeded_edges(), trace!("c9", ["receive", "validate", "reject"]))

    assert %ConformanceResult{trace_id: "c9", fitness: fitness, precision: nil} = result
    assert fitness === 0.5
  end

  test "conformance/2 fitness is exactly 1.0 (a float) for a single-activity trace" do
    result = Discovery.conformance(seeded_edges(), trace!("c3", ["receive"]))

    assert %ConformanceResult{trace_id: "c3", fitness: fitness, precision: nil} = result
    assert fitness === 1.0
    assert is_float(fitness)
  end

  test "conformance/2 fitness is exactly 1.0 (a float) for an empty edge set and a short trace" do
    result = Discovery.conformance([], trace!("c3", ["receive"]))

    assert %ConformanceResult{trace_id: "c3", fitness: fitness, precision: nil} = result
    assert fitness === 1.0
  end

  test "admitted record type conformance_result backs the discovery API with a generated struct module" do
    assert Code.ensure_loaded?(BeamPM.Types.ConformanceResult)
    assert function_exported?(BeamPM.Types.ConformanceResult, :new, 1)
  end

  test "admitted record type dfg_edge backs the discovery API with a generated struct module" do
    assert Code.ensure_loaded?(BeamPM.Types.DfgEdge)
    assert function_exported?(BeamPM.Types.DfgEdge, :new, 1)
  end

  test "admitted record type log_trace backs the discovery API with a generated struct module" do
    assert Code.ensure_loaded?(BeamPM.Types.LogTrace)
    assert function_exported?(BeamPM.Types.LogTrace, :new, 1)
  end

  test "admitted record type ocel_event backs the discovery API with a generated struct module" do
    assert Code.ensure_loaded?(BeamPM.Types.OcelEvent)
    assert function_exported?(BeamPM.Types.OcelEvent, :new, 1)
  end
end
