defmodule Beam4pm.MixProject do
  use Mix.Project

  def project do
    [
      app: :beam4pm,
      version: "0.1.0",
      elixir: "~> 1.17",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  # lib/ and test/ hold hand-authored and ggen-manufactured source alike --
  # standard Mix defaults (compile all of lib/, run all of test/), no custom
  # elixirc_paths/test_paths needed. Manufactured provenance is signalled
  # per-file by the "GENERATED by ggen ... Do not edit." header comment,
  # never by directory placement. See CONTRIBUTING.md.

  # :ggen_igniter is a manufacturing-time tool only (`mix ggen_igniter.sync`,
  # see scripts/igniter_sync.sh) -- never a runtime dependency of generated
  # code. Compiling it requires a working Rust/cargo toolchain (its default
  # oxigraph query engine is a Rustler NIF). :ash IS a real runtime
  # dependency of the manufactured lib/beam4pm_ash.ex.
  defp deps do
    [
      {:ggen_igniter, "~> 26.8", only: [:dev, :test], runtime: false},
      {:ash, "~> 3.0"}
    ]
  end
end
