defmodule Beam4pm.MixProject do
  use Mix.Project

  def project do
    [
      app: :beam4pm,
      version: "26.9.9",
      elixir: "~> 1.17",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      aliases: aliases()
    ]
  end

  def application do
    [
      mod: {BeamPM.Application, []},
      extra_applications: [:logger]
    ]
  end

  def cli do
    [preferred_envs: ["test.chicago": :test]]
  end

  # lib/ and test/ hold hand-authored and ggen-manufactured source alike --
  # standard Mix defaults (compile all of lib/, run all of test/), no custom
  # elixirc_paths/test_paths needed. Manufactured provenance is signalled
  # per-file by the "GENERATED by ggen ... Do not edit." header comment,
  # never by directory placement. See CONTRIBUTING.md.

  # :ggen_igniter is a manufacturing-time tool only (`mix ggen_igniter.sync`,
  # see scripts/igniter_sync.sh) -- never a runtime dependency of generated
  # code. Compiling it requires a working Rust/cargo toolchain (its default
  # oxigraph query engine is a Rustler NIF). :ash IS a real runtime
  # dependency of the manufactured lib/beam4pm_ash.ex. :wasmex hosts the ONE
  # process-mining engine (rust4pm compiled to wasm32-wasip1, see
  # native/rust4pm-wasm/ and lib/beam4pm_rust4pm.ex); Elixir/Erlang/Gleam are
  # facades over it, so it is a runtime dep like :ash, not a
  # manufacturing-time dep like :ggen_igniter.
  defp deps do
    [
      {:ggen_igniter, "~> 26.8", only: [:dev, :test], runtime: false},
      {:ash, "~> 3.0"},
      {:ash_ai, "~> 1.0"},
      {:wasmex, "~> 0.15"},
      # BeamPM.OcelIngest.Router (lib/beam4pm_ocel_ingest.ex) -- beam4pm's own
      # independent network ingestion layer, real runtime deps (not
      # only: :test): a running beam4pm needs to actually listen.
      {:plug, "~> 1.14"},
      {:bandit, "~> 1.5"}
    ]
  end

  # `mix test` (default, test/test_helper.exs excludes :chicago) -- fast,
  # everyday loop. `mix test.chicago` -- full suite including any test
  # explicitly tagged :chicago (a repo-wide convention for slow,
  # full-integration-scope cases; no test currently carries the tag here,
  # so this alias is presently equivalent to `mix test --include chicago`
  # with nothing extra admitted -- it exists as the standing seam for the
  # first real :chicago-tagged integration test, not a currently-populated
  # suite).
  defp aliases do
    [
      "test.chicago": ["test --include chicago"]
    ]
  end
end
