# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.AcceptanceCriteriaNonweakeningTest do
  use ExUnit.Case, async: false

  test "acceptance_criteria_nonweakening: real Ash ETS create/read round-trips every field" do
    params =
      %{
      assessment_id: "sample_assessment_id",
      acceptance_contract_id: "sample_acceptance_contract_id",
      prior_digest: "sample_prior_digest",
      candidate_digest: "sample_candidate_digest",
      strength_result: "sample_strength_result",
      refusal_code: "sample_refusal_code"
      }

    created =
      BeamPM.Ash.Resources.AcceptanceCriteriaNonweakening
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.AcceptanceCriteriaNonweakening)
    assert read_back.id == created.id
    assert read_back.assessment_id == "sample_assessment_id"
    assert read_back.acceptance_contract_id == "sample_acceptance_contract_id"
    assert read_back.prior_digest == "sample_prior_digest"
    assert read_back.candidate_digest == "sample_candidate_digest"
    assert read_back.strength_result == "sample_strength_result"
    assert read_back.refusal_code == "sample_refusal_code"
  end
end

