# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.ActionPinEvidenceTest do
  use ExUnit.Case, async: false

  test "action_pin_evidence: real Ash ETS create/read round-trips every field" do
    params =
      %{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      action_sha: "sample_action_sha",
      observed_result: :sample_atom
      }

    created =
      BeamPM.Ash.Resources.ActionPinEvidence
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.ActionPinEvidence)
    assert read_back.id == created.id
    assert read_back.evidence_id == "sample_evidence_id"
    assert read_back.subject_sha == "sample_subject_sha"
    assert read_back.action_sha == "sample_action_sha"
    assert read_back.observed_result == :sample_atom
  end
end

