# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.AuthorityCeilingTest do
  use ExUnit.Case, async: false

  test "authority_ceiling: real Ash ETS create/read round-trips every field" do
    params =
      %{
      action_id: "sample_action_id",
      grant_id: "sample_grant_id",
      ceiling: "sample_ceiling"
      }

    created =
      BeamPM.Ash.Resources.AuthorityCeiling
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.AuthorityCeiling)
    assert read_back.id == created.id
    assert read_back.action_id == "sample_action_id"
    assert read_back.grant_id == "sample_grant_id"
    assert read_back.ceiling == "sample_ceiling"
  end
end

