# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.AutonomicTimeoutBudgetTest do
  use ExUnit.Case, async: false

  test "autonomic_timeout_budget: real Ash ETS create/read round-trips every field" do
    params =
      %{
      actuation_id: "sample_actuation_id",
      subject_sha: "sample_subject_sha",
      authority_receipt_sha: "sample_authority_receipt_sha",
      state_digest: "sample_state_digest"
      }

    created =
      BeamPM.Ash.Resources.AutonomicTimeoutBudget
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.AutonomicTimeoutBudget)
    assert read_back.id == created.id
    assert read_back.actuation_id == "sample_actuation_id"
    assert read_back.subject_sha == "sample_subject_sha"
    assert read_back.authority_receipt_sha == "sample_authority_receipt_sha"
    assert read_back.state_digest == "sample_state_digest"
  end
end

