# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.CapsuleIdentityTest do
  use ExUnit.Case, async: false

  test "capsule_identity: real Ash ETS create/read round-trips every field" do
    params =
      %{
      tenant_id: "sample_tenant_id",
      capsule_id: "sample_capsule_id",
      identity_hash: "sample_identity_hash"
      }

    created =
      BeamPM.Ash.Resources.CapsuleIdentity
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.CapsuleIdentity)
    assert read_back.id == created.id
    assert read_back.tenant_id == "sample_tenant_id"
    assert read_back.capsule_id == "sample_capsule_id"
    assert read_back.identity_hash == "sample_identity_hash"
  end
end

