# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.CaseStatsTest do
  use ExUnit.Case, async: false

  test "case_stats: real Ash ETS create/read round-trips every field" do
    params =
      %{
      case_id: "sample_case_id",
      event_count: 42,
      duration_seconds: 3.5
      }

    created =
      BeamPM.Ash.Resources.CaseStats
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.CaseStats)
    assert read_back.id == created.id
    assert read_back.case_id == "sample_case_id"
    assert read_back.event_count == 42
    assert read_back.duration_seconds == 3.5
  end
end

