# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.ConfigurationExportTest do
  use ExUnit.Case, async: false

  test "configuration_export: real Ash ETS create/read round-trips every field" do
    params =
      %{
      export_id: "sample_export_id",
      tenant_id: "sample_tenant_id",
      configuration_hash: "sample_configuration_hash",
      exported_at: "2026-08-29T12:00:00Z"
      }

    created =
      BeamPM.Ash.Resources.ConfigurationExport
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.ConfigurationExport)
    assert read_back.id == created.id
    assert read_back.export_id == "sample_export_id"
    assert read_back.tenant_id == "sample_tenant_id"
    assert read_back.configuration_hash == "sample_configuration_hash"
    assert read_back.exported_at == ~U[2026-08-29 12:00:00Z]
  end
end

