# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.ConsumerPackPinObservationTest do
  use ExUnit.Case, async: false

  test "consumer_pack_pin_observation: real Ash ETS create/read round-trips every field" do
    params =
      %{
      consumer_repository_id: "sample_consumer_repository_id",
      pack_id: "sample_pack_id",
      pack_sha: "sample_pack_sha",
      evidence_digest: "sample_evidence_digest"
      }

    created =
      BeamPM.Ash.Resources.ConsumerPackPinObservation
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.ConsumerPackPinObservation)
    assert read_back.id == created.id
    assert read_back.consumer_repository_id == "sample_consumer_repository_id"
    assert read_back.pack_id == "sample_pack_id"
    assert read_back.pack_sha == "sample_pack_sha"
    assert read_back.evidence_digest == "sample_evidence_digest"
  end
end

