# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.CostLatencyReliabilityTradeoffTest do
  use ExUnit.Case, async: false

  test "cost_latency_reliability_tradeoff: real Ash ETS create/read round-trips every field" do
    params =
      %{
      assessment_id: "sample_assessment_id",
      candidate_policy_id: "sample_candidate_policy_id",
      cost_score: 3.5,
      latency_score: 3.5,
      reliability_score: 3.5,
      utility_score: 3.5
      }

    created =
      BeamPM.Ash.Resources.CostLatencyReliabilityTradeoff
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.CostLatencyReliabilityTradeoff)
    assert read_back.id == created.id
    assert read_back.assessment_id == "sample_assessment_id"
    assert read_back.candidate_policy_id == "sample_candidate_policy_id"
    assert read_back.cost_score == 3.5
    assert read_back.latency_score == 3.5
    assert read_back.reliability_score == 3.5
    assert read_back.utility_score == 3.5
  end
end

