# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.CostToServeMeasurementTest do
  use ExUnit.Case, async: false

  test "cost_to_serve_measurement: real Ash ETS create/read round-trips every field" do
    params =
      %{
      tenant_id: "sample_tenant_id",
      billing_period_id: "sample_billing_period_id",
      measurement_hash: "sample_measurement_hash"
      }

    created =
      BeamPM.Ash.Resources.CostToServeMeasurement
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.CostToServeMeasurement)
    assert read_back.id == created.id
    assert read_back.tenant_id == "sample_tenant_id"
    assert read_back.billing_period_id == "sample_billing_period_id"
    assert read_back.measurement_hash == "sample_measurement_hash"
  end
end

