# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.CrownLatencyObservationTest do
  use ExUnit.Case, async: false

  test "crown_latency_observation: real Ash ETS create/read round-trips every field" do
    params =
      %{
      propagation_id: "sample_propagation_id",
      subject_sha: "sample_subject_sha",
      latency_millis: "sample_latency_millis",
      receipt_digest: "sample_receipt_digest"
      }

    created =
      BeamPM.Ash.Resources.CrownLatencyObservation
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.CrownLatencyObservation)
    assert read_back.id == created.id
    assert read_back.propagation_id == "sample_propagation_id"
    assert read_back.subject_sha == "sample_subject_sha"
    assert read_back.latency_millis == "sample_latency_millis"
    assert read_back.receipt_digest == "sample_receipt_digest"
  end
end

