# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.CrownKnownGoodRollbackTest do
  use ExUnit.Case, async: false

  test "crown_known_good_rollback: real Ash ETS create/read round-trips every field" do
    params =
      %{
      propagation_id: "sample_propagation_id",
      subject_sha: "sample_subject_sha",
      rollback_crown_digest: "sample_rollback_crown_digest",
      receipt_digest: "sample_receipt_digest"
      }

    created =
      BeamPM.Ash.Resources.CrownKnownGoodRollback
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.CrownKnownGoodRollback)
    assert read_back.id == created.id
    assert read_back.propagation_id == "sample_propagation_id"
    assert read_back.subject_sha == "sample_subject_sha"
    assert read_back.rollback_crown_digest == "sample_rollback_crown_digest"
    assert read_back.receipt_digest == "sample_receipt_digest"
  end
end

