# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.InvoiceScheduleTest do
  use ExUnit.Case, async: false

  test "invoice_schedule: real Ash ETS create/read round-trips every field" do
    params =
      %{
      schedule_id: "sample_schedule_id",
      billing_account_id: "sample_billing_account_id",
      cadence: :sample_atom,
      next_invoice_at: "2026-08-29T12:00:00.123456Z"
      }

    created =
      BeamPM.Ash.Resources.InvoiceSchedule
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.InvoiceSchedule)
    assert read_back.id == created.id
    # Datetime identity across the Ash boundary is DateTime.compare/2 == :eq
    # against the parsed wire fixture (Ash normalizes the ISO 8601 string the
    # Erlang/Elixir/JSON legs carry verbatim into a UTC %DateTime{} with
    # microsecond {n, 6}) -- explicitly NOT byte/struct identity: a no-fraction
    # wire value would read back {0, 6} vs a parsed {0, 0}. The six-digit fixture
    # makes a truncating attribute type (:utc_datetime) fail here with :lt.
    assert read_back.schedule_id == "sample_schedule_id"
    assert read_back.billing_account_id == "sample_billing_account_id"
    assert read_back.cadence == :sample_atom
    {:ok, next_invoice_at_wire, 0} = DateTime.from_iso8601("2026-08-29T12:00:00.123456Z")
    assert DateTime.compare(read_back.next_invoice_at, next_invoice_at_wire) == :eq
  end
end

