# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.LeakageFindingTest do
  use ExUnit.Case, async: false

  test "leakage_finding: real Ash ETS create/read round-trips every field" do
    params =
      %{
      case_id: "sample_case_id",
      fitness: 3.5,
      precision: 3.5,
      amount_at_risk: 3.5
      }

    created =
      BeamPM.Ash.Resources.LeakageFinding
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.LeakageFinding)
    assert read_back.id == created.id
    assert read_back.case_id == "sample_case_id"
    assert read_back.fitness == 3.5
    assert read_back.precision == 3.5
    assert read_back.amount_at_risk == 3.5
  end
end

