# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.MeteredUsageSampleTest do
  use ExUnit.Case, async: false

  test "metered_usage_sample: real Ash ETS create/read round-trips every field" do
    params =
      %{
      tenant_id: "sample_tenant_id",
      usage_sample_id: "sample_usage_sample_id",
      sample_hash: "sample_sample_hash"
      }

    created =
      BeamPM.Ash.Resources.MeteredUsageSample
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.MeteredUsageSample)
    assert read_back.id == created.id
    assert read_back.tenant_id == "sample_tenant_id"
    assert read_back.usage_sample_id == "sample_usage_sample_id"
    assert read_back.sample_hash == "sample_sample_hash"
  end
end

