# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.MultiarchEvidenceTest do
  use ExUnit.Case, async: false

  test "multiarch_evidence: real Ash ETS create/read round-trips every field" do
    params =
      %{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      platforms: ["alpha", "beta"],
      observed_result: :sample_atom
      }

    created =
      BeamPM.Ash.Resources.MultiarchEvidence
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.MultiarchEvidence)
    assert read_back.id == created.id
    assert read_back.evidence_id == "sample_evidence_id"
    assert read_back.subject_sha == "sample_subject_sha"
    assert read_back.platforms == ["alpha", "beta"]
    assert read_back.observed_result == :sample_atom
  end
end

