# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.NonproductionDiscountPolicyTest do
  use ExUnit.Case, async: false

  test "nonproduction_discount_policy: real Ash ETS create/read round-trips every field" do
    params =
      %{
      nonproduction_discount_policy_id: "sample_nonproduction_discount_policy_id",
      account_id: "sample_account_id",
      discount_percent: 3.5,
      evidence_digest: "sample_evidence_digest",
      effective_at: "2026-08-29T12:00:00Z"
      }

    created =
      BeamPM.Ash.Resources.NonproductionDiscountPolicy
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.NonproductionDiscountPolicy)
    assert read_back.id == created.id
    assert read_back.nonproduction_discount_policy_id == "sample_nonproduction_discount_policy_id"
    assert read_back.account_id == "sample_account_id"
    assert read_back.discount_percent == 3.5
    assert read_back.evidence_digest == "sample_evidence_digest"
    assert read_back.effective_at == ~U[2026-08-29 12:00:00Z]
  end
end

