# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.ObjectionResolutionTest do
  use ExUnit.Case, async: false

  test "objection_resolution: real Ash ETS create/read round-trips every field" do
    params =
      %{
      objection_resolution_id: "sample_objection_resolution_id",
      account_id: "sample_account_id",
      resolution_status: "sample_resolution_status",
      evidence_digest: "sample_evidence_digest",
      observed_at: "2026-08-29T12:00:00Z"
      }

    created =
      BeamPM.Ash.Resources.ObjectionResolution
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.ObjectionResolution)
    assert read_back.id == created.id
    assert read_back.objection_resolution_id == "sample_objection_resolution_id"
    assert read_back.account_id == "sample_account_id"
    assert read_back.resolution_status == "sample_resolution_status"
    assert read_back.evidence_digest == "sample_evidence_digest"
    assert read_back.observed_at == ~U[2026-08-29 12:00:00Z]
  end
end

