# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.OcelRelationshipTest do
  use ExUnit.Case, async: false

  test "ocel_relationship: real Ash ETS create/read round-trips every field" do
    params =
      %{
      qualifier: "sample_qualifier",
      object_id: "sample_object_id"
      }

    created =
      BeamPM.Ash.Resources.OcelRelationship
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.OcelRelationship)
    assert read_back.id == created.id
    assert read_back.qualifier == "sample_qualifier"
    assert read_back.object_id == "sample_object_id"
  end
end

