# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.PaymentTermsAdmissionTest do
  use ExUnit.Case, async: false

  test "payment_terms_admission: real Ash ETS create/read round-trips every field" do
    params =
      %{
      opportunity_id: "sample_opportunity_id",
      payment_terms: "sample_payment_terms",
      authority_evidence_hash: "sample_authority_evidence_hash"
      }

    created =
      BeamPM.Ash.Resources.PaymentTermsAdmission
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.PaymentTermsAdmission)
    assert read_back.id == created.id
    assert read_back.opportunity_id == "sample_opportunity_id"
    assert read_back.payment_terms == "sample_payment_terms"
    assert read_back.authority_evidence_hash == "sample_authority_evidence_hash"
  end
end

