# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.PetriArcTest do
  use ExUnit.Case, async: false

  test "petri_arc: real Ash ETS create/read round-trips every field" do
    params =
      %{
      source_id: "sample_source_id",
      target_id: "sample_target_id",
      weight: 42
      }

    created =
      BeamPM.Ash.Resources.PetriArc
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.PetriArc)
    assert read_back.id == created.id
    assert read_back.source_id == "sample_source_id"
    assert read_back.target_id == "sample_target_id"
    assert read_back.weight == 42
  end
end

