# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.PlanningActionTest do
  use ExUnit.Case, async: false

  test "planning_action: real Ash ETS create/read round-trips every field" do
    params =
      %{
      action_name: "sample_action_name",
      preconditions: ["alpha", "beta"],
      effects: ["alpha", "beta"]
      }

    created =
      BeamPM.Ash.Resources.PlanningAction
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.PlanningAction)
    assert read_back.id == created.id
    assert read_back.action_name == "sample_action_name"
    assert read_back.preconditions == ["alpha", "beta"]
    assert read_back.effects == ["alpha", "beta"]
  end
end

