# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.PlannerPortfolioTest do
  use ExUnit.Case, async: false

  test "planner_portfolio: real Ash ETS create/read round-trips every field" do
    params =
      %{
      portfolio_id: "sample_portfolio_id",
      planner_ids: "sample_planner_ids",
      diversity_hash: "sample_diversity_hash"
      }

    created =
      BeamPM.Ash.Resources.PlannerPortfolio
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.PlannerPortfolio)
    assert read_back.id == created.id
    assert read_back.portfolio_id == "sample_portfolio_id"
    assert read_back.planner_ids == "sample_planner_ids"
    assert read_back.diversity_hash == "sample_diversity_hash"
  end
end

