# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.PocExitCriteriaTest do
  use ExUnit.Case, async: false

  test "poc_exit_criteria: real Ash ETS create/read round-trips every field" do
    params =
      %{
      poc_exit_criteria_id: "sample_poc_exit_criteria_id",
      account_id: "sample_account_id",
      criteria_pass_rate: 3.5,
      evidence_digest: "sample_evidence_digest",
      observed_at: "2026-08-29T12:00:00Z"
      }

    created =
      BeamPM.Ash.Resources.PocExitCriteria
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.PocExitCriteria)
    assert read_back.id == created.id
    assert read_back.poc_exit_criteria_id == "sample_poc_exit_criteria_id"
    assert read_back.account_id == "sample_account_id"
    assert read_back.criteria_pass_rate == 3.5
    assert read_back.evidence_digest == "sample_evidence_digest"
    assert read_back.observed_at == ~U[2026-08-29 12:00:00Z]
  end
end

