# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.PolicyPayoffObservationTest do
  use ExUnit.Case, async: false

  test "policy_payoff_observation: real Ash ETS create/read round-trips every field" do
    params =
      %{
      observation_id: "sample_observation_id",
      policy_id: "sample_policy_id",
      parameter_digest: "sample_parameter_digest",
      objective_id: "sample_objective_id",
      payoff: 3.5,
      evidence_digest: "sample_evidence_digest"
      }

    created =
      BeamPM.Ash.Resources.PolicyPayoffObservation
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.PolicyPayoffObservation)
    assert read_back.id == created.id
    assert read_back.observation_id == "sample_observation_id"
    assert read_back.policy_id == "sample_policy_id"
    assert read_back.parameter_digest == "sample_parameter_digest"
    assert read_back.objective_id == "sample_objective_id"
    assert read_back.payoff == 3.5
    assert read_back.evidence_digest == "sample_evidence_digest"
  end
end

