# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.ProcurementBlockerTest do
  use ExUnit.Case, async: false

  test "procurement_blocker: real Ash ETS create/read round-trips every field" do
    params =
      %{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
      }

    created =
      BeamPM.Ash.Resources.ProcurementBlocker
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.ProcurementBlocker)
    assert read_back.id == created.id
    assert read_back.opportunity_id == "sample_opportunity_id"
    assert read_back.blocker_id == "sample_blocker_id"
    assert read_back.refusal_code == "sample_refusal_code"
  end
end

