# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.RateDistortionBudgetTest do
  use ExUnit.Case, async: false

  test "rate_distortion_budget: real Ash ETS create/read round-trips every field" do
    params =
      %{
      budget_id: "sample_budget_id",
      decision_id: "sample_decision_id",
      source_information_bits: 3.5,
      retained_information_bits: 3.5,
      maximum_distortion: 3.5
      }

    created =
      BeamPM.Ash.Resources.RateDistortionBudget
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.RateDistortionBudget)
    assert read_back.id == created.id
    assert read_back.budget_id == "sample_budget_id"
    assert read_back.decision_id == "sample_decision_id"
    assert read_back.source_information_bits == 3.5
    assert read_back.retained_information_bits == 3.5
    assert read_back.maximum_distortion == 3.5
  end
end

