# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.RecoveryPlanTest do
  use ExUnit.Case, async: false

  test "recovery_plan: real Ash ETS create/read round-trips every field" do
    params =
      %{
      recovery_plan_id: "sample_recovery_plan_id",
      account_id: "sample_account_id",
      recovery_time_hours: 3.5,
      evidence_digest: "sample_evidence_digest",
      observed_at: "2026-08-29T12:00:00.123456Z"
      }

    created =
      BeamPM.Ash.Resources.RecoveryPlan
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.RecoveryPlan)
    assert read_back.id == created.id
    # Datetime identity across the Ash boundary is DateTime.compare/2 == :eq
    # against the parsed wire fixture (Ash normalizes the ISO 8601 string the
    # Erlang/Elixir/JSON legs carry verbatim into a UTC %DateTime{} with
    # microsecond {n, 6}) -- explicitly NOT byte/struct identity: a no-fraction
    # wire value would read back {0, 6} vs a parsed {0, 0}. The six-digit fixture
    # makes a truncating attribute type (:utc_datetime) fail here with :lt.
    assert read_back.recovery_plan_id == "sample_recovery_plan_id"
    assert read_back.account_id == "sample_account_id"
    assert read_back.recovery_time_hours == 3.5
    assert read_back.evidence_digest == "sample_evidence_digest"
    {:ok, observed_at_wire, 0} = DateTime.from_iso8601("2026-08-29T12:00:00.123456Z")
    assert DateTime.compare(read_back.observed_at, observed_at_wire) == :eq
  end
end

