# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.RenewalOptionTest do
  use ExUnit.Case, async: false

  test "renewal_option: real Ash ETS create/read round-trips every field" do
    params =
      %{
      option_id: "sample_option_id",
      subscription_id: "sample_subscription_id",
      term_months: 42,
      notice_by: "2026-08-29T12:00:00.123456Z"
      }

    created =
      BeamPM.Ash.Resources.RenewalOption
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.RenewalOption)
    assert read_back.id == created.id
    # Datetime identity across the Ash boundary is DateTime.compare/2 == :eq
    # against the parsed wire fixture (Ash normalizes the ISO 8601 string the
    # Erlang/Elixir/JSON legs carry verbatim into a UTC %DateTime{} with
    # microsecond {n, 6}) -- explicitly NOT byte/struct identity: a no-fraction
    # wire value would read back {0, 6} vs a parsed {0, 0}. The six-digit fixture
    # makes a truncating attribute type (:utc_datetime) fail here with :lt.
    assert read_back.option_id == "sample_option_id"
    assert read_back.subscription_id == "sample_subscription_id"
    assert read_back.term_months == 42
    {:ok, notice_by_wire, 0} = DateTime.from_iso8601("2026-08-29T12:00:00.123456Z")
    assert DateTime.compare(read_back.notice_by, notice_by_wire) == :eq
  end
end

