# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.RenewalOptionTest do
  use ExUnit.Case, async: false

  test "renewal_option: real Ash ETS create/read round-trips every field" do
    params =
      %{
      option_id: "sample_option_id",
      subscription_id: "sample_subscription_id",
      term_months: 42,
      notice_by: "2026-08-29T12:00:00Z"
      }

    created =
      BeamPM.Ash.Resources.RenewalOption
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.RenewalOption)
    assert read_back.id == created.id
    assert read_back.option_id == "sample_option_id"
    assert read_back.subscription_id == "sample_subscription_id"
    assert read_back.term_months == 42
    assert read_back.notice_by == ~U[2026-08-29 12:00:00Z]
  end
end

