# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.ReserveWorkPromotionTest do
  use ExUnit.Case, async: false

  test "reserve_work_promotion: real Ash ETS create/read round-trips every field" do
    params =
      %{
      blocked_work_id: "sample_blocked_work_id",
      reserve_set_hash: "sample_reserve_set_hash",
      promoted_work_id: "sample_promoted_work_id"
      }

    created =
      BeamPM.Ash.Resources.ReserveWorkPromotion
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.ReserveWorkPromotion)
    assert read_back.id == created.id
    assert read_back.blocked_work_id == "sample_blocked_work_id"
    assert read_back.reserve_set_hash == "sample_reserve_set_hash"
    assert read_back.promoted_work_id == "sample_promoted_work_id"
  end
end

