# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.ResellerAuthorizationTest do
  use ExUnit.Case, async: false

  test "reseller_authorization: real Ash ETS create/read round-trips every field" do
    params =
      %{
      authorization_id: "sample_authorization_id",
      reseller_id: "sample_reseller_id",
      sku: "sample_sku",
      status: :sample_atom
      }

    created =
      BeamPM.Ash.Resources.ResellerAuthorization
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.ResellerAuthorization)
    assert read_back.id == created.id
    assert read_back.authorization_id == "sample_authorization_id"
    assert read_back.reseller_id == "sample_reseller_id"
    assert read_back.sku == "sample_sku"
    assert read_back.status == :sample_atom
  end
end

