# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.RoleCompatibilityTest do
  use ExUnit.Case, async: false

  test "role_compatibility: real Ash ETS create/read round-trips every field" do
    params =
      %{
      role_id: "sample_role_id",
      policy_id: "sample_policy_id",
      compatibility: "sample_compatibility"
      }

    created =
      BeamPM.Ash.Resources.RoleCompatibility
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.RoleCompatibility)
    assert read_back.id == created.id
    assert read_back.role_id == "sample_role_id"
    assert read_back.policy_id == "sample_policy_id"
    assert read_back.compatibility == "sample_compatibility"
  end
end

