# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.ServiceCreditLedgerTest do
  use ExUnit.Case, async: false

  test "service_credit_ledger: real Ash ETS create/read round-trips every field" do
    params =
      %{
      service_credit_ledger_id: "sample_service_credit_ledger_id",
      account_id: "sample_account_id",
      credit_amount: 3.5,
      evidence_digest: "sample_evidence_digest",
      effective_at: "2026-08-29T12:00:00Z"
      }

    created =
      BeamPM.Ash.Resources.ServiceCreditLedger
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.ServiceCreditLedger)
    assert read_back.id == created.id
    assert read_back.service_credit_ledger_id == "sample_service_credit_ledger_id"
    assert read_back.account_id == "sample_account_id"
    assert read_back.credit_amount == 3.5
    assert read_back.evidence_digest == "sample_evidence_digest"
    assert read_back.effective_at == ~U[2026-08-29 12:00:00Z]
  end
end

