# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.StoppingCriterionTest do
  use ExUnit.Case, async: false

  test "stopping_criterion: real Ash ETS create/read round-trips every field" do
    params =
      %{
      criterion_id: "sample_criterion_id",
      objective_id: "sample_objective_id",
      minimum_gain: 3.5,
      maximum_episodes: 42,
      evidence_window_digest: "sample_evidence_window_digest",
      authority_binding: "sample_authority_binding"
      }

    created =
      BeamPM.Ash.Resources.StoppingCriterion
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.StoppingCriterion)
    assert read_back.id == created.id
    assert read_back.criterion_id == "sample_criterion_id"
    assert read_back.objective_id == "sample_objective_id"
    assert read_back.minimum_gain == 3.5
    assert read_back.maximum_episodes == 42
    assert read_back.evidence_window_digest == "sample_evidence_window_digest"
    assert read_back.authority_binding == "sample_authority_binding"
  end
end

