# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.UsageEventTest do
  use ExUnit.Case, async: false

  test "usage_event: real Ash ETS create/read round-trips every field" do
    params =
      %{
      event_id: "sample_event_id",
      entitlement_id: "sample_entitlement_id",
      quantity: 3.5,
      metric_name: "sample_metric_name",
      occurred_at: "2026-08-29T12:00:00.123456Z"
      }

    created =
      BeamPM.Ash.Resources.UsageEvent
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.UsageEvent)
    assert read_back.id == created.id
    # Datetime identity across the Ash boundary is DateTime.compare/2 == :eq
    # against the parsed wire fixture (Ash normalizes the ISO 8601 string the
    # Erlang/Elixir/JSON legs carry verbatim into a UTC %DateTime{} with
    # microsecond {n, 6}) -- explicitly NOT byte/struct identity: a no-fraction
    # wire value would read back {0, 6} vs a parsed {0, 0}. The six-digit fixture
    # makes a truncating attribute type (:utc_datetime) fail here with :lt.
    assert read_back.event_id == "sample_event_id"
    assert read_back.entitlement_id == "sample_entitlement_id"
    assert read_back.quantity == 3.5
    assert read_back.metric_name == "sample_metric_name"
    {:ok, occurred_at_wire, 0} = DateTime.from_iso8601("2026-08-29T12:00:00.123456Z")
    assert DateTime.compare(read_back.occurred_at, occurred_at_wire) == :eq
  end
end

