# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.UsageReconciliationReceiptTest do
  use ExUnit.Case, async: false

  test "usage_reconciliation_receipt: real Ash ETS create/read round-trips every field" do
    params =
      %{
      tenant_id: "sample_tenant_id",
      billing_period_id: "sample_billing_period_id",
      reconciliation_hash: "sample_reconciliation_hash"
      }

    created =
      BeamPM.Ash.Resources.UsageReconciliationReceipt
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.UsageReconciliationReceipt)
    assert read_back.id == created.id
    assert read_back.tenant_id == "sample_tenant_id"
    assert read_back.billing_period_id == "sample_billing_period_id"
    assert read_back.reconciliation_hash == "sample_reconciliation_hash"
  end
end

