# GENERATED by ggen_igniter. Do not edit.
defmodule BeamPM.Ash.Resources.WorkloadExecutionIdentityTest do
  use ExUnit.Case, async: false

  test "workload_execution_identity: real Ash ETS create/read round-trips every field" do
    params =
      %{
      tenant_id: "sample_tenant_id",
      execution_id: "sample_execution_id",
      subject_digest: "sample_subject_digest"
      }

    created =
      BeamPM.Ash.Resources.WorkloadExecutionIdentity
      |> Ash.Changeset.for_create(:create, params)
      |> Ash.create!()

    [read_back] = Ash.read!(BeamPM.Ash.Resources.WorkloadExecutionIdentity)
    assert read_back.id == created.id
    assert read_back.tenant_id == "sample_tenant_id"
    assert read_back.execution_id == "sample_execution_id"
    assert read_back.subject_digest == "sample_subject_digest"
  end
end

