# GENERATED by ggen from the admitted bap:RuntimeModule graph in ontology.ttl. Do not edit.
defmodule BeamPM.FerroplanBridge.VkgConsumer do
  def request(binding, contract, subject), do: %{source: binding.id, origin: binding.origin, digest: binding.digest, contract: contract.id, subject: subject}
end
