# GENERATED by ggen from the admitted bpm:RecordType graph. Do not edit.
#
# Cross-language roundtrip sample fixtures: one deterministic sample per
# admitted record type and variant (:full | :minimal), written and verified
# through BeamPM.Codec so any drift between the Elixir and Erlang codecs
# surfaces as a real fixture mismatch, not an assumed equivalence.

defmodule BeamPM.Roundtrip do
  @moduledoc "Cross-language roundtrip sample fixtures for every admitted record type."

  @record_names [
    :account_master_match,
    :account_parent_scope,
    :action_pin_evidence,
    :alignment_move,
    :approval_separation_evidence,
    :architecture_review_evidence,
    :artifact_digest_evidence,
    :attestation_verification_evidence,
    :audit_chain_evidence,
    :availability_slo_evidence,
    :backup_restore_evidence,
    :beneficial_owner_evidence,
    :billing_reconciliation,
    :booking_readiness,
    :budget_period_alignment,
    :business_continuity_evidence,
    :canary_evidence,
    :case_stats,
    :change_control_evidence,
    :change_order_authority,
    :commercial_artifact_crown_evidence,
    :commercial_exception,
    :committed_spend_admission,
    :conformance_result,
    :contracting_entity_identity,
    :credit_risk_admission,
    :customer_managed_key_evidence,
    :data_egress_evidence,
    :data_migration_scope_admission,
    :data_processing_addendum_state,
    :deal_desk_packet,
    :deletion_proof_evidence,
    :dependency_inventory_evidence,
    :dfg_edge,
    :disaster_recovery_evidence,
    :entitlement_event,
    :entitlement_evidence,
    :entitlement_state,
    :event_log,
    :event_type,
    :evidence_freshness_evidence,
    :exception_authority,
    :funding_approval_chain,
    :heuristic_arc,
    :implementation_fee_admission,
    :incident_response_evidence,
    :indemnity_scope_admission,
    :insurance_requirement,
    :integration_scope_admission,
    :invoice_entity_identity,
    :k8s_object_ref,
    :least_authority_evidence,
    :legal_blocker,
    :liability_cap_admission,
    :license_evidence,
    :log_trace,
    :master_service_agreement_state,
    :minimum_term_admission,
    :multiarch_evidence,
    :mutable_identity_refusal_evidence,
    :object_attribute_change,
    :object_type,
    :oc_declare_constraint,
    :ocel_attribute,
    :ocel_event,
    :ocel_object,
    :ocel_relationship,
    :oci_manifest_evidence,
    :offline_bundle_evidence,
    :opportunity_currency_contract,
    :opportunity_value_range,
    :order_form_admission,
    :path_schema,
    :path_schema_query,
    :payment_terms_admission,
    :performance_slo_evidence,
    :petri_arc,
    :petri_place,
    :petri_transition,
    :planning_action,
    :planning_state,
    :policy_decision,
    :pricing_basis_contract,
    :privacy_classification_evidence,
    :private_registry_evidence,
    :process_variant,
    :procurement_acceptance_evidence,
    :procurement_blocker,
    :procurement_channel_selection,
    :proof_of_value_budget,
    :proof_of_value_exit_gate,
    :provenance_binding_evidence,
    :purchase_order_requirement,
    :purchasing_entity_identity,
    :queue_snapshot,
    :receipt_replay_evidence,
    :remediation_sla_evidence,
    :renewal_term_admission,
    :reproducible_build_evidence,
    :residency_evidence,
    :resource_allocation,
    :retention_policy_evidence,
    :revenue_contract_admission,
    :revenue_schedule_assumption,
    :rfp_response_evidence,
    :rollback_evidence,
    :sanctions_screening_result,
    :sbom_inventory_evidence,
    :secret_boundary_evidence,
    :security_addendum_state,
    :security_blocker,
    :service_credit_admission,
    :service_span,
    :signature_evidence,
    :sla_offer_admission,
    :sojourn_time,
    :stale_subject_refusal_evidence,
    :support_escalation_evidence,
    :support_sla_evidence,
    :support_tier_admission,
    :support_window_evidence,
    :sync_time,
    :tax_jurisdiction_evidence,
    :technical_blocker,
    :termination_right_admission,
    :training_scope_admission,
    :type_edge,
    :unsupported_capability_evidence,
    :upgrade_evidence,
    :usage_event,
    :vendor_registration_state,
    :vendor_risk_evidence,
    :version_lifecycle_evidence,
    :volume_tier_admission,
    :vulnerability_scan_evidence
  ]

  @variants [:full, :minimal]

  @spec record_names() :: [atom()]
  def record_names, do: @record_names

  # Deterministic sample values, keyed by bpm:fieldType:
  # string -> "sample_" <> field_name, datetime -> "2026-08-29T12:00:00Z",
  # integer -> 42, float -> 3.5, boolean -> true, atom -> :sample_atom,
  # list_string -> ["alpha", "beta"], map -> a single-entry map "k" => "v".
  # :minimal = required fields only; :full = every field.
  @spec sample(atom(), :full | :minimal) :: {:ok, struct()}

  def sample(:account_master_match, :full) do
    BeamPM.Types.AccountMasterMatch.new(%{
      source_account_id: "sample_source_account_id",
      canonical_account_id: "sample_canonical_account_id",
      match_evidence_hash: "sample_match_evidence_hash"
    })
  end

  def sample(:account_master_match, :minimal) do
    BeamPM.Types.AccountMasterMatch.new(%{
      source_account_id: "sample_source_account_id",
      canonical_account_id: "sample_canonical_account_id",
      match_evidence_hash: "sample_match_evidence_hash"
    })
  end

  def sample(:account_parent_scope, :full) do
    BeamPM.Types.AccountParentScope.new(%{
      account_id: "sample_account_id",
      parent_account_id: "sample_parent_account_id",
      scope_evidence_hash: "sample_scope_evidence_hash"
    })
  end

  def sample(:account_parent_scope, :minimal) do
    BeamPM.Types.AccountParentScope.new(%{
      account_id: "sample_account_id",
      parent_account_id: "sample_parent_account_id",
      scope_evidence_hash: "sample_scope_evidence_hash"
    })
  end

  def sample(:action_pin_evidence, :full) do
    BeamPM.Types.ActionPinEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      action_sha: "sample_action_sha",
      observed_result: :sample_atom
    })
  end

  def sample(:action_pin_evidence, :minimal) do
    BeamPM.Types.ActionPinEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      action_sha: "sample_action_sha",
      observed_result: :sample_atom
    })
  end

  def sample(:alignment_move, :full) do
    BeamPM.Types.AlignmentMove.new(%{
      move_type: :sample_atom,
      cost: 42
    })
  end

  def sample(:alignment_move, :minimal) do
    BeamPM.Types.AlignmentMove.new(%{
      move_type: :sample_atom,
      cost: 42
    })
  end

  def sample(:approval_separation_evidence, :full) do
    BeamPM.Types.ApprovalSeparationEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      approver_identity: "sample_approver_identity",
      observed_result: :sample_atom
    })
  end

  def sample(:approval_separation_evidence, :minimal) do
    BeamPM.Types.ApprovalSeparationEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      approver_identity: "sample_approver_identity",
      observed_result: :sample_atom
    })
  end

  def sample(:architecture_review_evidence, :full) do
    BeamPM.Types.ArchitectureReviewEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      review_decision: "sample_review_decision",
      observed_result: :sample_atom
    })
  end

  def sample(:architecture_review_evidence, :minimal) do
    BeamPM.Types.ArchitectureReviewEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      review_decision: "sample_review_decision",
      observed_result: :sample_atom
    })
  end

  def sample(:artifact_digest_evidence, :full) do
    BeamPM.Types.ArtifactDigestEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      digest: "sample_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:artifact_digest_evidence, :minimal) do
    BeamPM.Types.ArtifactDigestEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      digest: "sample_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:attestation_verification_evidence, :full) do
    BeamPM.Types.AttestationVerificationEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      predicate_type: "sample_predicate_type",
      observed_result: :sample_atom
    })
  end

  def sample(:attestation_verification_evidence, :minimal) do
    BeamPM.Types.AttestationVerificationEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      predicate_type: "sample_predicate_type",
      observed_result: :sample_atom
    })
  end

  def sample(:audit_chain_evidence, :full) do
    BeamPM.Types.AuditChainEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      previous_receipt_hash: "sample_previous_receipt_hash",
      observed_result: :sample_atom
    })
  end

  def sample(:audit_chain_evidence, :minimal) do
    BeamPM.Types.AuditChainEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      previous_receipt_hash: "sample_previous_receipt_hash",
      observed_result: :sample_atom
    })
  end

  def sample(:availability_slo_evidence, :full) do
    BeamPM.Types.AvailabilitySloEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      availability_percent: 3.5,
      observed_result: :sample_atom
    })
  end

  def sample(:availability_slo_evidence, :minimal) do
    BeamPM.Types.AvailabilitySloEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      availability_percent: 3.5,
      observed_result: :sample_atom
    })
  end

  def sample(:backup_restore_evidence, :full) do
    BeamPM.Types.BackupRestoreEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      backup_digest: "sample_backup_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:backup_restore_evidence, :minimal) do
    BeamPM.Types.BackupRestoreEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      backup_digest: "sample_backup_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:beneficial_owner_evidence, :full) do
    BeamPM.Types.BeneficialOwnerEvidence.new(%{
      account_id: "sample_account_id",
      owner_id: "sample_owner_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:beneficial_owner_evidence, :minimal) do
    BeamPM.Types.BeneficialOwnerEvidence.new(%{
      account_id: "sample_account_id",
      owner_id: "sample_owner_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:billing_reconciliation, :full) do
    BeamPM.Types.BillingReconciliation.new(%{
      entitlement_id: "sample_entitlement_id",
      metric_name: "sample_metric_name",
      total_quantity: 3.5,
      applied_event_ids: ["alpha", "beta"],
      period_start: "2026-08-29T12:00:00Z",
      period_end: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:billing_reconciliation, :minimal) do
    BeamPM.Types.BillingReconciliation.new(%{
      entitlement_id: "sample_entitlement_id",
      metric_name: "sample_metric_name",
      total_quantity: 3.5,
      applied_event_ids: ["alpha", "beta"],
      period_start: "2026-08-29T12:00:00Z",
      period_end: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:booking_readiness, :full) do
    BeamPM.Types.BookingReadiness.new(%{
      opportunity_id: "sample_opportunity_id",
      readiness_id: "sample_readiness_id",
      decision: "sample_decision"
    })
  end

  def sample(:booking_readiness, :minimal) do
    BeamPM.Types.BookingReadiness.new(%{
      opportunity_id: "sample_opportunity_id",
      readiness_id: "sample_readiness_id",
      decision: "sample_decision"
    })
  end

  def sample(:budget_period_alignment, :full) do
    BeamPM.Types.BudgetPeriodAlignment.new(%{
      opportunity_id: "sample_opportunity_id",
      budget_period: "sample_budget_period",
      alignment_result: "sample_alignment_result"
    })
  end

  def sample(:budget_period_alignment, :minimal) do
    BeamPM.Types.BudgetPeriodAlignment.new(%{
      opportunity_id: "sample_opportunity_id",
      budget_period: "sample_budget_period",
      alignment_result: "sample_alignment_result"
    })
  end

  def sample(:business_continuity_evidence, :full) do
    BeamPM.Types.BusinessContinuityEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      continuity_mode: "sample_continuity_mode",
      observed_result: :sample_atom
    })
  end

  def sample(:business_continuity_evidence, :minimal) do
    BeamPM.Types.BusinessContinuityEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      continuity_mode: "sample_continuity_mode",
      observed_result: :sample_atom
    })
  end

  def sample(:canary_evidence, :full) do
    BeamPM.Types.CanaryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      canary_percentage: 3.5,
      observed_result: :sample_atom
    })
  end

  def sample(:canary_evidence, :minimal) do
    BeamPM.Types.CanaryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      canary_percentage: 3.5,
      observed_result: :sample_atom
    })
  end

  def sample(:case_stats, :full) do
    BeamPM.Types.CaseStats.new(%{
      case_id: "sample_case_id",
      event_count: 42,
      duration_seconds: 3.5
    })
  end

  def sample(:case_stats, :minimal) do
    BeamPM.Types.CaseStats.new(%{
      case_id: "sample_case_id",
      event_count: 42
    })
  end

  def sample(:change_control_evidence, :full) do
    BeamPM.Types.ChangeControlEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      change_request_id: "sample_change_request_id",
      observed_result: :sample_atom
    })
  end

  def sample(:change_control_evidence, :minimal) do
    BeamPM.Types.ChangeControlEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      change_request_id: "sample_change_request_id",
      observed_result: :sample_atom
    })
  end

  def sample(:change_order_authority, :full) do
    BeamPM.Types.ChangeOrderAuthority.new(%{
      opportunity_id: "sample_opportunity_id",
      authority_id: "sample_authority_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:change_order_authority, :minimal) do
    BeamPM.Types.ChangeOrderAuthority.new(%{
      opportunity_id: "sample_opportunity_id",
      authority_id: "sample_authority_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:commercial_artifact_crown_evidence, :full) do
    BeamPM.Types.CommercialArtifactCrownEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      artifact_digest: "sample_artifact_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:commercial_artifact_crown_evidence, :minimal) do
    BeamPM.Types.CommercialArtifactCrownEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      artifact_digest: "sample_artifact_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:commercial_exception, :full) do
    BeamPM.Types.CommercialException.new(%{
      opportunity_id: "sample_opportunity_id",
      exception_id: "sample_exception_id",
      exception_state: "sample_exception_state"
    })
  end

  def sample(:commercial_exception, :minimal) do
    BeamPM.Types.CommercialException.new(%{
      opportunity_id: "sample_opportunity_id",
      exception_id: "sample_exception_id",
      exception_state: "sample_exception_state"
    })
  end

  def sample(:committed_spend_admission, :full) do
    BeamPM.Types.CommittedSpendAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      commitment_id: "sample_commitment_id",
      decision: "sample_decision"
    })
  end

  def sample(:committed_spend_admission, :minimal) do
    BeamPM.Types.CommittedSpendAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      commitment_id: "sample_commitment_id",
      decision: "sample_decision"
    })
  end

  def sample(:conformance_result, :full) do
    BeamPM.Types.ConformanceResult.new(%{
      trace_id: "sample_trace_id",
      fitness: 3.5,
      precision: 3.5
    })
  end

  def sample(:conformance_result, :minimal) do
    BeamPM.Types.ConformanceResult.new(%{
      trace_id: "sample_trace_id",
      fitness: 3.5
    })
  end

  def sample(:contracting_entity_identity, :full) do
    BeamPM.Types.ContractingEntityIdentity.new(%{
      opportunity_id: "sample_opportunity_id",
      contracting_entity_id: "sample_contracting_entity_id",
      identity_evidence_hash: "sample_identity_evidence_hash"
    })
  end

  def sample(:contracting_entity_identity, :minimal) do
    BeamPM.Types.ContractingEntityIdentity.new(%{
      opportunity_id: "sample_opportunity_id",
      contracting_entity_id: "sample_contracting_entity_id",
      identity_evidence_hash: "sample_identity_evidence_hash"
    })
  end

  def sample(:credit_risk_admission, :full) do
    BeamPM.Types.CreditRiskAdmission.new(%{
      account_id: "sample_account_id",
      risk_band: "sample_risk_band",
      decision: "sample_decision"
    })
  end

  def sample(:credit_risk_admission, :minimal) do
    BeamPM.Types.CreditRiskAdmission.new(%{
      account_id: "sample_account_id",
      risk_band: "sample_risk_band",
      decision: "sample_decision"
    })
  end

  def sample(:customer_managed_key_evidence, :full) do
    BeamPM.Types.CustomerManagedKeyEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      key_identifier: "sample_key_identifier",
      observed_result: :sample_atom
    })
  end

  def sample(:customer_managed_key_evidence, :minimal) do
    BeamPM.Types.CustomerManagedKeyEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      key_identifier: "sample_key_identifier",
      observed_result: :sample_atom
    })
  end

  def sample(:data_egress_evidence, :full) do
    BeamPM.Types.DataEgressEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      egress_bytes: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:data_egress_evidence, :minimal) do
    BeamPM.Types.DataEgressEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      egress_bytes: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:data_migration_scope_admission, :full) do
    BeamPM.Types.DataMigrationScopeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      migration_scope_id: "sample_migration_scope_id",
      decision: "sample_decision"
    })
  end

  def sample(:data_migration_scope_admission, :minimal) do
    BeamPM.Types.DataMigrationScopeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      migration_scope_id: "sample_migration_scope_id",
      decision: "sample_decision"
    })
  end

  def sample(:data_processing_addendum_state, :full) do
    BeamPM.Types.DataProcessingAddendumState.new(%{
      opportunity_id: "sample_opportunity_id",
      addendum_id: "sample_addendum_id",
      addendum_state: "sample_addendum_state"
    })
  end

  def sample(:data_processing_addendum_state, :minimal) do
    BeamPM.Types.DataProcessingAddendumState.new(%{
      opportunity_id: "sample_opportunity_id",
      addendum_id: "sample_addendum_id",
      addendum_state: "sample_addendum_state"
    })
  end

  def sample(:deal_desk_packet, :full) do
    BeamPM.Types.DealDeskPacket.new(%{
      opportunity_id: "sample_opportunity_id",
      packet_id: "sample_packet_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:deal_desk_packet, :minimal) do
    BeamPM.Types.DealDeskPacket.new(%{
      opportunity_id: "sample_opportunity_id",
      packet_id: "sample_packet_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:deletion_proof_evidence, :full) do
    BeamPM.Types.DeletionProofEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      deletion_receipt_id: "sample_deletion_receipt_id",
      observed_result: :sample_atom
    })
  end

  def sample(:deletion_proof_evidence, :minimal) do
    BeamPM.Types.DeletionProofEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      deletion_receipt_id: "sample_deletion_receipt_id",
      observed_result: :sample_atom
    })
  end

  def sample(:dependency_inventory_evidence, :full) do
    BeamPM.Types.DependencyInventoryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      dependency_count: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:dependency_inventory_evidence, :minimal) do
    BeamPM.Types.DependencyInventoryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      dependency_count: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:dfg_edge, :full) do
    BeamPM.Types.DfgEdge.new(%{
      source_activity: "sample_source_activity",
      target_activity: "sample_target_activity",
      frequency: 42
    })
  end

  def sample(:dfg_edge, :minimal) do
    BeamPM.Types.DfgEdge.new(%{
      source_activity: "sample_source_activity",
      target_activity: "sample_target_activity",
      frequency: 42
    })
  end

  def sample(:disaster_recovery_evidence, :full) do
    BeamPM.Types.DisasterRecoveryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      recovered_at: "2026-08-29T12:00:00Z",
      observed_result: :sample_atom
    })
  end

  def sample(:disaster_recovery_evidence, :minimal) do
    BeamPM.Types.DisasterRecoveryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      recovered_at: "2026-08-29T12:00:00Z",
      observed_result: :sample_atom
    })
  end

  def sample(:entitlement_event, :full) do
    BeamPM.Types.EntitlementEvent.new(%{
      event_id: "sample_event_id",
      entitlement_id: "sample_entitlement_id",
      event_type: "sample_event_type",
      effective_at: "2026-08-29T12:00:00Z",
      payload: %{"k" => "v"}
    })
  end

  def sample(:entitlement_event, :minimal) do
    BeamPM.Types.EntitlementEvent.new(%{
      event_id: "sample_event_id",
      entitlement_id: "sample_entitlement_id",
      event_type: "sample_event_type",
      effective_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:entitlement_evidence, :full) do
    BeamPM.Types.EntitlementEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      entitlement_id: "sample_entitlement_id",
      observed_result: :sample_atom
    })
  end

  def sample(:entitlement_evidence, :minimal) do
    BeamPM.Types.EntitlementEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      entitlement_id: "sample_entitlement_id",
      observed_result: :sample_atom
    })
  end

  def sample(:entitlement_state, :full) do
    BeamPM.Types.EntitlementState.new(%{
      entitlement_id: "sample_entitlement_id",
      status: "sample_status",
      last_applied_event_id: "sample_last_applied_event_id",
      updated_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:entitlement_state, :minimal) do
    BeamPM.Types.EntitlementState.new(%{
      entitlement_id: "sample_entitlement_id",
      status: "sample_status",
      last_applied_event_id: "sample_last_applied_event_id",
      updated_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:event_log, :full) do
    BeamPM.Types.EventLog.new(%{
      log_id: "sample_log_id",
      name: "sample_name",
      description: "sample_description"
    })
  end

  def sample(:event_log, :minimal) do
    BeamPM.Types.EventLog.new(%{
      log_id: "sample_log_id",
      name: "sample_name"
    })
  end

  def sample(:event_type, :full) do
    BeamPM.Types.EventType.new(%{
      type_name: "sample_type_name",
      attribute_names: ["alpha", "beta"]
    })
  end

  def sample(:event_type, :minimal) do
    BeamPM.Types.EventType.new(%{
      type_name: "sample_type_name"
    })
  end

  def sample(:evidence_freshness_evidence, :full) do
    BeamPM.Types.EvidenceFreshnessEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      observed_at: "2026-08-29T12:00:00Z",
      observed_result: :sample_atom
    })
  end

  def sample(:evidence_freshness_evidence, :minimal) do
    BeamPM.Types.EvidenceFreshnessEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      observed_at: "2026-08-29T12:00:00Z",
      observed_result: :sample_atom
    })
  end

  def sample(:exception_authority, :full) do
    BeamPM.Types.ExceptionAuthority.new(%{
      exception_id: "sample_exception_id",
      authority_id: "sample_authority_id",
      decision: "sample_decision"
    })
  end

  def sample(:exception_authority, :minimal) do
    BeamPM.Types.ExceptionAuthority.new(%{
      exception_id: "sample_exception_id",
      authority_id: "sample_authority_id",
      decision: "sample_decision"
    })
  end

  def sample(:funding_approval_chain, :full) do
    BeamPM.Types.FundingApprovalChain.new(%{
      opportunity_id: "sample_opportunity_id",
      approval_chain_id: "sample_approval_chain_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:funding_approval_chain, :minimal) do
    BeamPM.Types.FundingApprovalChain.new(%{
      opportunity_id: "sample_opportunity_id",
      approval_chain_id: "sample_approval_chain_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:heuristic_arc, :full) do
    BeamPM.Types.HeuristicArc.new(%{
      source_activity: "sample_source_activity",
      target_activity: "sample_target_activity",
      dependency_measure: 3.5
    })
  end

  def sample(:heuristic_arc, :minimal) do
    BeamPM.Types.HeuristicArc.new(%{
      source_activity: "sample_source_activity",
      target_activity: "sample_target_activity",
      dependency_measure: 3.5
    })
  end

  def sample(:implementation_fee_admission, :full) do
    BeamPM.Types.ImplementationFeeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      fee_id: "sample_fee_id",
      decision: "sample_decision"
    })
  end

  def sample(:implementation_fee_admission, :minimal) do
    BeamPM.Types.ImplementationFeeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      fee_id: "sample_fee_id",
      decision: "sample_decision"
    })
  end

  def sample(:incident_response_evidence, :full) do
    BeamPM.Types.IncidentResponseEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      incident_id: "sample_incident_id",
      observed_result: :sample_atom
    })
  end

  def sample(:incident_response_evidence, :minimal) do
    BeamPM.Types.IncidentResponseEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      incident_id: "sample_incident_id",
      observed_result: :sample_atom
    })
  end

  def sample(:indemnity_scope_admission, :full) do
    BeamPM.Types.IndemnityScopeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      indemnity_scope_id: "sample_indemnity_scope_id",
      decision: "sample_decision"
    })
  end

  def sample(:indemnity_scope_admission, :minimal) do
    BeamPM.Types.IndemnityScopeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      indemnity_scope_id: "sample_indemnity_scope_id",
      decision: "sample_decision"
    })
  end

  def sample(:insurance_requirement, :full) do
    BeamPM.Types.InsuranceRequirement.new(%{
      opportunity_id: "sample_opportunity_id",
      coverage_id: "sample_coverage_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:insurance_requirement, :minimal) do
    BeamPM.Types.InsuranceRequirement.new(%{
      opportunity_id: "sample_opportunity_id",
      coverage_id: "sample_coverage_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:integration_scope_admission, :full) do
    BeamPM.Types.IntegrationScopeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      integration_scope_id: "sample_integration_scope_id",
      decision: "sample_decision"
    })
  end

  def sample(:integration_scope_admission, :minimal) do
    BeamPM.Types.IntegrationScopeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      integration_scope_id: "sample_integration_scope_id",
      decision: "sample_decision"
    })
  end

  def sample(:invoice_entity_identity, :full) do
    BeamPM.Types.InvoiceEntityIdentity.new(%{
      opportunity_id: "sample_opportunity_id",
      invoice_entity_id: "sample_invoice_entity_id",
      identity_evidence_hash: "sample_identity_evidence_hash"
    })
  end

  def sample(:invoice_entity_identity, :minimal) do
    BeamPM.Types.InvoiceEntityIdentity.new(%{
      opportunity_id: "sample_opportunity_id",
      invoice_entity_id: "sample_invoice_entity_id",
      identity_evidence_hash: "sample_identity_evidence_hash"
    })
  end

  def sample(:k8s_object_ref, :full) do
    BeamPM.Types.K8SObjectRef.new(%{
      kind: "sample_kind",
      name: "sample_name",
      namespace: "sample_namespace"
    })
  end

  def sample(:k8s_object_ref, :minimal) do
    BeamPM.Types.K8SObjectRef.new(%{
      kind: "sample_kind",
      name: "sample_name"
    })
  end

  def sample(:least_authority_evidence, :full) do
    BeamPM.Types.LeastAuthorityEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      granted_permissions: ["alpha", "beta"],
      observed_result: :sample_atom
    })
  end

  def sample(:least_authority_evidence, :minimal) do
    BeamPM.Types.LeastAuthorityEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      granted_permissions: ["alpha", "beta"],
      observed_result: :sample_atom
    })
  end

  def sample(:legal_blocker, :full) do
    BeamPM.Types.LegalBlocker.new(%{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
    })
  end

  def sample(:legal_blocker, :minimal) do
    BeamPM.Types.LegalBlocker.new(%{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
    })
  end

  def sample(:liability_cap_admission, :full) do
    BeamPM.Types.LiabilityCapAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      liability_cap_id: "sample_liability_cap_id",
      decision: "sample_decision"
    })
  end

  def sample(:liability_cap_admission, :minimal) do
    BeamPM.Types.LiabilityCapAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      liability_cap_id: "sample_liability_cap_id",
      decision: "sample_decision"
    })
  end

  def sample(:license_evidence, :full) do
    BeamPM.Types.LicenseEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      license_expression: "sample_license_expression",
      observed_result: :sample_atom
    })
  end

  def sample(:license_evidence, :minimal) do
    BeamPM.Types.LicenseEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      license_expression: "sample_license_expression",
      observed_result: :sample_atom
    })
  end

  def sample(:log_trace, :full) do
    BeamPM.Types.LogTrace.new(%{
      case_id: "sample_case_id",
      activity_sequence: ["alpha", "beta"]
    })
  end

  def sample(:log_trace, :minimal) do
    BeamPM.Types.LogTrace.new(%{
      case_id: "sample_case_id",
      activity_sequence: ["alpha", "beta"]
    })
  end

  def sample(:master_service_agreement_state, :full) do
    BeamPM.Types.MasterServiceAgreementState.new(%{
      opportunity_id: "sample_opportunity_id",
      agreement_id: "sample_agreement_id",
      agreement_state: "sample_agreement_state"
    })
  end

  def sample(:master_service_agreement_state, :minimal) do
    BeamPM.Types.MasterServiceAgreementState.new(%{
      opportunity_id: "sample_opportunity_id",
      agreement_id: "sample_agreement_id",
      agreement_state: "sample_agreement_state"
    })
  end

  def sample(:minimum_term_admission, :full) do
    BeamPM.Types.MinimumTermAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      minimum_term: "sample_minimum_term",
      decision: "sample_decision"
    })
  end

  def sample(:minimum_term_admission, :minimal) do
    BeamPM.Types.MinimumTermAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      minimum_term: "sample_minimum_term",
      decision: "sample_decision"
    })
  end

  def sample(:multiarch_evidence, :full) do
    BeamPM.Types.MultiarchEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      platforms: ["alpha", "beta"],
      observed_result: :sample_atom
    })
  end

  def sample(:multiarch_evidence, :minimal) do
    BeamPM.Types.MultiarchEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      platforms: ["alpha", "beta"],
      observed_result: :sample_atom
    })
  end

  def sample(:mutable_identity_refusal_evidence, :full) do
    BeamPM.Types.MutableIdentityRefusalEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      mutable_reference: "sample_mutable_reference",
      observed_result: :sample_atom
    })
  end

  def sample(:mutable_identity_refusal_evidence, :minimal) do
    BeamPM.Types.MutableIdentityRefusalEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      mutable_reference: "sample_mutable_reference",
      observed_result: :sample_atom
    })
  end

  def sample(:object_attribute_change, :full) do
    BeamPM.Types.ObjectAttributeChange.new(%{
      object_id: "sample_object_id",
      attribute_name: "sample_attribute_name",
      old_value: "sample_old_value",
      new_value: "sample_new_value",
      changed_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:object_attribute_change, :minimal) do
    BeamPM.Types.ObjectAttributeChange.new(%{
      object_id: "sample_object_id",
      attribute_name: "sample_attribute_name",
      new_value: "sample_new_value",
      changed_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:object_type, :full) do
    BeamPM.Types.ObjectType.new(%{
      type_name: "sample_type_name",
      attribute_names: ["alpha", "beta"]
    })
  end

  def sample(:object_type, :minimal) do
    BeamPM.Types.ObjectType.new(%{
      type_name: "sample_type_name"
    })
  end

  def sample(:oc_declare_constraint, :full) do
    BeamPM.Types.OcDeclareConstraint.new(%{
      constraint_id: "sample_constraint_id",
      source_activity: "sample_source_activity",
      target_activity: "sample_target_activity",
      constraint_type: :sample_atom
    })
  end

  def sample(:oc_declare_constraint, :minimal) do
    BeamPM.Types.OcDeclareConstraint.new(%{
      constraint_id: "sample_constraint_id",
      source_activity: "sample_source_activity",
      target_activity: "sample_target_activity",
      constraint_type: :sample_atom
    })
  end

  def sample(:ocel_attribute, :full) do
    BeamPM.Types.OcelAttribute.new(%{
      attribute_name: "sample_attribute_name",
      attribute_value: "sample_attribute_value",
      recorded_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:ocel_attribute, :minimal) do
    BeamPM.Types.OcelAttribute.new(%{
      attribute_name: "sample_attribute_name",
      attribute_value: "sample_attribute_value"
    })
  end

  def sample(:ocel_event, :full) do
    BeamPM.Types.OcelEvent.new(%{
      event_id: "sample_event_id",
      event_type: "sample_event_type",
      event_time: "2026-08-29T12:00:00Z",
      attributes: %{"k" => "v"}
    })
  end

  def sample(:ocel_event, :minimal) do
    BeamPM.Types.OcelEvent.new(%{
      event_id: "sample_event_id",
      event_type: "sample_event_type",
      event_time: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:ocel_object, :full) do
    BeamPM.Types.OcelObject.new(%{
      object_id: "sample_object_id",
      object_type: "sample_object_type",
      attributes: %{"k" => "v"}
    })
  end

  def sample(:ocel_object, :minimal) do
    BeamPM.Types.OcelObject.new(%{
      object_id: "sample_object_id",
      object_type: "sample_object_type"
    })
  end

  def sample(:ocel_relationship, :full) do
    BeamPM.Types.OcelRelationship.new(%{
      qualifier: "sample_qualifier",
      object_id: "sample_object_id"
    })
  end

  def sample(:ocel_relationship, :minimal) do
    BeamPM.Types.OcelRelationship.new(%{
      qualifier: "sample_qualifier",
      object_id: "sample_object_id"
    })
  end

  def sample(:oci_manifest_evidence, :full) do
    BeamPM.Types.OciManifestEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      manifest_digest: "sample_manifest_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:oci_manifest_evidence, :minimal) do
    BeamPM.Types.OciManifestEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      manifest_digest: "sample_manifest_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:offline_bundle_evidence, :full) do
    BeamPM.Types.OfflineBundleEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      bundle_digest: "sample_bundle_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:offline_bundle_evidence, :minimal) do
    BeamPM.Types.OfflineBundleEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      bundle_digest: "sample_bundle_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:opportunity_currency_contract, :full) do
    BeamPM.Types.OpportunityCurrencyContract.new(%{
      opportunity_id: "sample_opportunity_id",
      currency_code: "sample_currency_code",
      fx_basis_id: "sample_fx_basis_id"
    })
  end

  def sample(:opportunity_currency_contract, :minimal) do
    BeamPM.Types.OpportunityCurrencyContract.new(%{
      opportunity_id: "sample_opportunity_id",
      currency_code: "sample_currency_code",
      fx_basis_id: "sample_fx_basis_id"
    })
  end

  def sample(:opportunity_value_range, :full) do
    BeamPM.Types.OpportunityValueRange.new(%{
      opportunity_id: "sample_opportunity_id",
      minimum_value: "sample_minimum_value",
      maximum_value: "sample_maximum_value"
    })
  end

  def sample(:opportunity_value_range, :minimal) do
    BeamPM.Types.OpportunityValueRange.new(%{
      opportunity_id: "sample_opportunity_id",
      minimum_value: "sample_minimum_value",
      maximum_value: "sample_maximum_value"
    })
  end

  def sample(:order_form_admission, :full) do
    BeamPM.Types.OrderFormAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      order_form_id: "sample_order_form_id",
      decision: "sample_decision"
    })
  end

  def sample(:order_form_admission, :minimal) do
    BeamPM.Types.OrderFormAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      order_form_id: "sample_order_form_id",
      decision: "sample_decision"
    })
  end

  def sample(:path_schema, :full) do
    BeamPM.Types.PathSchema.new(%{
      schema_id: "sample_schema_id",
      source_type: "sample_source_type",
      target_type: "sample_target_type",
      support: 42
    })
  end

  def sample(:path_schema, :minimal) do
    BeamPM.Types.PathSchema.new(%{
      schema_id: "sample_schema_id",
      source_type: "sample_source_type",
      target_type: "sample_target_type",
      support: 42
    })
  end

  def sample(:path_schema_query, :full) do
    BeamPM.Types.PathSchemaQuery.new(%{
      source_type: "sample_source_type",
      target_type: "sample_target_type",
      max_length: 42
    })
  end

  def sample(:path_schema_query, :minimal) do
    BeamPM.Types.PathSchemaQuery.new(%{
      source_type: "sample_source_type",
      target_type: "sample_target_type",
      max_length: 42
    })
  end

  def sample(:payment_terms_admission, :full) do
    BeamPM.Types.PaymentTermsAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      payment_terms: "sample_payment_terms",
      authority_evidence_hash: "sample_authority_evidence_hash"
    })
  end

  def sample(:payment_terms_admission, :minimal) do
    BeamPM.Types.PaymentTermsAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      payment_terms: "sample_payment_terms",
      authority_evidence_hash: "sample_authority_evidence_hash"
    })
  end

  def sample(:performance_slo_evidence, :full) do
    BeamPM.Types.PerformanceSloEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      latency_p95_ms: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:performance_slo_evidence, :minimal) do
    BeamPM.Types.PerformanceSloEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      latency_p95_ms: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:petri_arc, :full) do
    BeamPM.Types.PetriArc.new(%{
      source_id: "sample_source_id",
      target_id: "sample_target_id",
      weight: 42
    })
  end

  def sample(:petri_arc, :minimal) do
    BeamPM.Types.PetriArc.new(%{
      source_id: "sample_source_id",
      target_id: "sample_target_id",
      weight: 42
    })
  end

  def sample(:petri_place, :full) do
    BeamPM.Types.PetriPlace.new(%{
      place_id: "sample_place_id",
      tokens: 42
    })
  end

  def sample(:petri_place, :minimal) do
    BeamPM.Types.PetriPlace.new(%{
      place_id: "sample_place_id",
      tokens: 42
    })
  end

  def sample(:petri_transition, :full) do
    BeamPM.Types.PetriTransition.new(%{
      transition_id: "sample_transition_id",
      label: "sample_label"
    })
  end

  def sample(:petri_transition, :minimal) do
    BeamPM.Types.PetriTransition.new(%{
      transition_id: "sample_transition_id"
    })
  end

  def sample(:planning_action, :full) do
    BeamPM.Types.PlanningAction.new(%{
      action_name: "sample_action_name",
      preconditions: ["alpha", "beta"],
      effects: ["alpha", "beta"]
    })
  end

  def sample(:planning_action, :minimal) do
    BeamPM.Types.PlanningAction.new(%{
      action_name: "sample_action_name"
    })
  end

  def sample(:planning_state, :full) do
    BeamPM.Types.PlanningState.new(%{
      state_id: "sample_state_id",
      facts: ["alpha", "beta"]
    })
  end

  def sample(:planning_state, :minimal) do
    BeamPM.Types.PlanningState.new(%{
      state_id: "sample_state_id",
      facts: ["alpha", "beta"]
    })
  end

  def sample(:policy_decision, :full) do
    BeamPM.Types.PolicyDecision.new(%{
      decision_id: "sample_decision_id",
      verdict: :sample_atom,
      reason: "sample_reason"
    })
  end

  def sample(:policy_decision, :minimal) do
    BeamPM.Types.PolicyDecision.new(%{
      decision_id: "sample_decision_id",
      verdict: :sample_atom
    })
  end

  def sample(:pricing_basis_contract, :full) do
    BeamPM.Types.PricingBasisContract.new(%{
      opportunity_id: "sample_opportunity_id",
      pricing_basis_id: "sample_pricing_basis_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:pricing_basis_contract, :minimal) do
    BeamPM.Types.PricingBasisContract.new(%{
      opportunity_id: "sample_opportunity_id",
      pricing_basis_id: "sample_pricing_basis_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:privacy_classification_evidence, :full) do
    BeamPM.Types.PrivacyClassificationEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      privacy_class: "sample_privacy_class",
      observed_result: :sample_atom
    })
  end

  def sample(:privacy_classification_evidence, :minimal) do
    BeamPM.Types.PrivacyClassificationEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      privacy_class: "sample_privacy_class",
      observed_result: :sample_atom
    })
  end

  def sample(:private_registry_evidence, :full) do
    BeamPM.Types.PrivateRegistryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      registry_digest: "sample_registry_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:private_registry_evidence, :minimal) do
    BeamPM.Types.PrivateRegistryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      registry_digest: "sample_registry_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:process_variant, :full) do
    BeamPM.Types.ProcessVariant.new(%{
      variant_id: "sample_variant_id",
      activity_sequence: ["alpha", "beta"],
      frequency: 42
    })
  end

  def sample(:process_variant, :minimal) do
    BeamPM.Types.ProcessVariant.new(%{
      variant_id: "sample_variant_id",
      activity_sequence: ["alpha", "beta"],
      frequency: 42
    })
  end

  def sample(:procurement_acceptance_evidence, :full) do
    BeamPM.Types.ProcurementAcceptanceEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      acceptance_decision: "sample_acceptance_decision",
      observed_result: :sample_atom
    })
  end

  def sample(:procurement_acceptance_evidence, :minimal) do
    BeamPM.Types.ProcurementAcceptanceEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      acceptance_decision: "sample_acceptance_decision",
      observed_result: :sample_atom
    })
  end

  def sample(:procurement_blocker, :full) do
    BeamPM.Types.ProcurementBlocker.new(%{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
    })
  end

  def sample(:procurement_blocker, :minimal) do
    BeamPM.Types.ProcurementBlocker.new(%{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
    })
  end

  def sample(:procurement_channel_selection, :full) do
    BeamPM.Types.ProcurementChannelSelection.new(%{
      opportunity_id: "sample_opportunity_id",
      channel_id: "sample_channel_id",
      selection_evidence_hash: "sample_selection_evidence_hash"
    })
  end

  def sample(:procurement_channel_selection, :minimal) do
    BeamPM.Types.ProcurementChannelSelection.new(%{
      opportunity_id: "sample_opportunity_id",
      channel_id: "sample_channel_id",
      selection_evidence_hash: "sample_selection_evidence_hash"
    })
  end

  def sample(:proof_of_value_budget, :full) do
    BeamPM.Types.ProofOfValueBudget.new(%{
      opportunity_id: "sample_opportunity_id",
      budget_id: "sample_budget_id",
      decision: "sample_decision"
    })
  end

  def sample(:proof_of_value_budget, :minimal) do
    BeamPM.Types.ProofOfValueBudget.new(%{
      opportunity_id: "sample_opportunity_id",
      budget_id: "sample_budget_id",
      decision: "sample_decision"
    })
  end

  def sample(:proof_of_value_exit_gate, :full) do
    BeamPM.Types.ProofOfValueExitGate.new(%{
      pov_id: "sample_pov_id",
      exit_gate_id: "sample_exit_gate_id",
      decision: "sample_decision"
    })
  end

  def sample(:proof_of_value_exit_gate, :minimal) do
    BeamPM.Types.ProofOfValueExitGate.new(%{
      pov_id: "sample_pov_id",
      exit_gate_id: "sample_exit_gate_id",
      decision: "sample_decision"
    })
  end

  def sample(:provenance_binding_evidence, :full) do
    BeamPM.Types.ProvenanceBindingEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      builder_identity: "sample_builder_identity",
      observed_result: :sample_atom
    })
  end

  def sample(:provenance_binding_evidence, :minimal) do
    BeamPM.Types.ProvenanceBindingEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      builder_identity: "sample_builder_identity",
      observed_result: :sample_atom
    })
  end

  def sample(:purchase_order_requirement, :full) do
    BeamPM.Types.PurchaseOrderRequirement.new(%{
      opportunity_id: "sample_opportunity_id",
      requirement_id: "sample_requirement_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:purchase_order_requirement, :minimal) do
    BeamPM.Types.PurchaseOrderRequirement.new(%{
      opportunity_id: "sample_opportunity_id",
      requirement_id: "sample_requirement_id",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:purchasing_entity_identity, :full) do
    BeamPM.Types.PurchasingEntityIdentity.new(%{
      opportunity_id: "sample_opportunity_id",
      purchasing_entity_id: "sample_purchasing_entity_id",
      identity_evidence_hash: "sample_identity_evidence_hash"
    })
  end

  def sample(:purchasing_entity_identity, :minimal) do
    BeamPM.Types.PurchasingEntityIdentity.new(%{
      opportunity_id: "sample_opportunity_id",
      purchasing_entity_id: "sample_purchasing_entity_id",
      identity_evidence_hash: "sample_identity_evidence_hash"
    })
  end

  def sample(:queue_snapshot, :full) do
    BeamPM.Types.QueueSnapshot.new(%{
      queue_name: "sample_queue_name",
      depth: 42,
      observed_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:queue_snapshot, :minimal) do
    BeamPM.Types.QueueSnapshot.new(%{
      queue_name: "sample_queue_name",
      depth: 42,
      observed_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:receipt_replay_evidence, :full) do
    BeamPM.Types.ReceiptReplayEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      replay_result_hash: "sample_replay_result_hash",
      observed_result: :sample_atom
    })
  end

  def sample(:receipt_replay_evidence, :minimal) do
    BeamPM.Types.ReceiptReplayEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      replay_result_hash: "sample_replay_result_hash",
      observed_result: :sample_atom
    })
  end

  def sample(:remediation_sla_evidence, :full) do
    BeamPM.Types.RemediationSlaEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      remediation_due_at: "2026-08-29T12:00:00Z",
      observed_result: :sample_atom
    })
  end

  def sample(:remediation_sla_evidence, :minimal) do
    BeamPM.Types.RemediationSlaEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      remediation_due_at: "2026-08-29T12:00:00Z",
      observed_result: :sample_atom
    })
  end

  def sample(:renewal_term_admission, :full) do
    BeamPM.Types.RenewalTermAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      renewal_term: "sample_renewal_term",
      decision: "sample_decision"
    })
  end

  def sample(:renewal_term_admission, :minimal) do
    BeamPM.Types.RenewalTermAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      renewal_term: "sample_renewal_term",
      decision: "sample_decision"
    })
  end

  def sample(:reproducible_build_evidence, :full) do
    BeamPM.Types.ReproducibleBuildEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      build_digest: "sample_build_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:reproducible_build_evidence, :minimal) do
    BeamPM.Types.ReproducibleBuildEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      build_digest: "sample_build_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:residency_evidence, :full) do
    BeamPM.Types.ResidencyEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      region: "sample_region",
      observed_result: :sample_atom
    })
  end

  def sample(:residency_evidence, :minimal) do
    BeamPM.Types.ResidencyEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      region: "sample_region",
      observed_result: :sample_atom
    })
  end

  def sample(:resource_allocation, :full) do
    BeamPM.Types.ResourceAllocation.new(%{
      resource_id: "sample_resource_id",
      activity: "sample_activity",
      event_id: "sample_event_id"
    })
  end

  def sample(:resource_allocation, :minimal) do
    BeamPM.Types.ResourceAllocation.new(%{
      resource_id: "sample_resource_id",
      activity: "sample_activity",
      event_id: "sample_event_id"
    })
  end

  def sample(:retention_policy_evidence, :full) do
    BeamPM.Types.RetentionPolicyEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      retention_days: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:retention_policy_evidence, :minimal) do
    BeamPM.Types.RetentionPolicyEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      retention_days: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:revenue_contract_admission, :full) do
    BeamPM.Types.RevenueContractAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      contract_id: "sample_contract_id",
      admission_receipt_hash: "sample_admission_receipt_hash"
    })
  end

  def sample(:revenue_contract_admission, :minimal) do
    BeamPM.Types.RevenueContractAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      contract_id: "sample_contract_id",
      admission_receipt_hash: "sample_admission_receipt_hash"
    })
  end

  def sample(:revenue_schedule_assumption, :full) do
    BeamPM.Types.RevenueScheduleAssumption.new(%{
      opportunity_id: "sample_opportunity_id",
      schedule_id: "sample_schedule_id",
      assumption_evidence_hash: "sample_assumption_evidence_hash"
    })
  end

  def sample(:revenue_schedule_assumption, :minimal) do
    BeamPM.Types.RevenueScheduleAssumption.new(%{
      opportunity_id: "sample_opportunity_id",
      schedule_id: "sample_schedule_id",
      assumption_evidence_hash: "sample_assumption_evidence_hash"
    })
  end

  def sample(:rfp_response_evidence, :full) do
    BeamPM.Types.RfpResponseEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      answer_set_hash: "sample_answer_set_hash",
      observed_result: :sample_atom
    })
  end

  def sample(:rfp_response_evidence, :minimal) do
    BeamPM.Types.RfpResponseEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      answer_set_hash: "sample_answer_set_hash",
      observed_result: :sample_atom
    })
  end

  def sample(:rollback_evidence, :full) do
    BeamPM.Types.RollbackEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      rollback_digest: "sample_rollback_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:rollback_evidence, :minimal) do
    BeamPM.Types.RollbackEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      rollback_digest: "sample_rollback_digest",
      observed_result: :sample_atom
    })
  end

  def sample(:sanctions_screening_result, :full) do
    BeamPM.Types.SanctionsScreeningResult.new(%{
      account_id: "sample_account_id",
      screening_id: "sample_screening_id",
      screening_result: "sample_screening_result"
    })
  end

  def sample(:sanctions_screening_result, :minimal) do
    BeamPM.Types.SanctionsScreeningResult.new(%{
      account_id: "sample_account_id",
      screening_id: "sample_screening_id",
      screening_result: "sample_screening_result"
    })
  end

  def sample(:sbom_inventory_evidence, :full) do
    BeamPM.Types.SbomInventoryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      component_count: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:sbom_inventory_evidence, :minimal) do
    BeamPM.Types.SbomInventoryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      component_count: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:secret_boundary_evidence, :full) do
    BeamPM.Types.SecretBoundaryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      secret_source: "sample_secret_source",
      observed_result: :sample_atom
    })
  end

  def sample(:secret_boundary_evidence, :minimal) do
    BeamPM.Types.SecretBoundaryEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      secret_source: "sample_secret_source",
      observed_result: :sample_atom
    })
  end

  def sample(:security_addendum_state, :full) do
    BeamPM.Types.SecurityAddendumState.new(%{
      opportunity_id: "sample_opportunity_id",
      addendum_id: "sample_addendum_id",
      addendum_state: "sample_addendum_state"
    })
  end

  def sample(:security_addendum_state, :minimal) do
    BeamPM.Types.SecurityAddendumState.new(%{
      opportunity_id: "sample_opportunity_id",
      addendum_id: "sample_addendum_id",
      addendum_state: "sample_addendum_state"
    })
  end

  def sample(:security_blocker, :full) do
    BeamPM.Types.SecurityBlocker.new(%{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
    })
  end

  def sample(:security_blocker, :minimal) do
    BeamPM.Types.SecurityBlocker.new(%{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
    })
  end

  def sample(:service_credit_admission, :full) do
    BeamPM.Types.ServiceCreditAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      service_credit_id: "sample_service_credit_id",
      decision: "sample_decision"
    })
  end

  def sample(:service_credit_admission, :minimal) do
    BeamPM.Types.ServiceCreditAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      service_credit_id: "sample_service_credit_id",
      decision: "sample_decision"
    })
  end

  def sample(:service_span, :full) do
    BeamPM.Types.ServiceSpan.new(%{
      span_id: "sample_span_id",
      service_name: "sample_service_name",
      duration_ms: 42,
      parent_span_id: "sample_parent_span_id"
    })
  end

  def sample(:service_span, :minimal) do
    BeamPM.Types.ServiceSpan.new(%{
      span_id: "sample_span_id",
      service_name: "sample_service_name",
      duration_ms: 42
    })
  end

  def sample(:signature_evidence, :full) do
    BeamPM.Types.SignatureEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      signature_identity: "sample_signature_identity",
      observed_result: :sample_atom
    })
  end

  def sample(:signature_evidence, :minimal) do
    BeamPM.Types.SignatureEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      signature_identity: "sample_signature_identity",
      observed_result: :sample_atom
    })
  end

  def sample(:sla_offer_admission, :full) do
    BeamPM.Types.SlaOfferAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      sla_offer_id: "sample_sla_offer_id",
      decision: "sample_decision"
    })
  end

  def sample(:sla_offer_admission, :minimal) do
    BeamPM.Types.SlaOfferAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      sla_offer_id: "sample_sla_offer_id",
      decision: "sample_decision"
    })
  end

  def sample(:sojourn_time, :full) do
    BeamPM.Types.SojournTime.new(%{
      object_id: "sample_object_id",
      event_type: "sample_event_type",
      seconds: 3.5
    })
  end

  def sample(:sojourn_time, :minimal) do
    BeamPM.Types.SojournTime.new(%{
      object_id: "sample_object_id",
      event_type: "sample_event_type",
      seconds: 3.5
    })
  end

  def sample(:stale_subject_refusal_evidence, :full) do
    BeamPM.Types.StaleSubjectRefusalEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      stale_sha: "sample_stale_sha",
      observed_result: :sample_atom
    })
  end

  def sample(:stale_subject_refusal_evidence, :minimal) do
    BeamPM.Types.StaleSubjectRefusalEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      stale_sha: "sample_stale_sha",
      observed_result: :sample_atom
    })
  end

  def sample(:support_escalation_evidence, :full) do
    BeamPM.Types.SupportEscalationEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      escalation_owner: "sample_escalation_owner",
      observed_result: :sample_atom
    })
  end

  def sample(:support_escalation_evidence, :minimal) do
    BeamPM.Types.SupportEscalationEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      escalation_owner: "sample_escalation_owner",
      observed_result: :sample_atom
    })
  end

  def sample(:support_sla_evidence, :full) do
    BeamPM.Types.SupportSlaEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      response_minutes: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:support_sla_evidence, :minimal) do
    BeamPM.Types.SupportSlaEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      response_minutes: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:support_tier_admission, :full) do
    BeamPM.Types.SupportTierAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      support_tier_id: "sample_support_tier_id",
      decision: "sample_decision"
    })
  end

  def sample(:support_tier_admission, :minimal) do
    BeamPM.Types.SupportTierAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      support_tier_id: "sample_support_tier_id",
      decision: "sample_decision"
    })
  end

  def sample(:support_window_evidence, :full) do
    BeamPM.Types.SupportWindowEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      support_channel: "sample_support_channel",
      observed_result: :sample_atom
    })
  end

  def sample(:support_window_evidence, :minimal) do
    BeamPM.Types.SupportWindowEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      support_channel: "sample_support_channel",
      observed_result: :sample_atom
    })
  end

  def sample(:sync_time, :full) do
    BeamPM.Types.SyncTime.new(%{
      object_id: "sample_object_id",
      delaying_object_id: "sample_delaying_object_id",
      seconds: 3.5
    })
  end

  def sample(:sync_time, :minimal) do
    BeamPM.Types.SyncTime.new(%{
      object_id: "sample_object_id",
      seconds: 3.5
    })
  end

  def sample(:tax_jurisdiction_evidence, :full) do
    BeamPM.Types.TaxJurisdictionEvidence.new(%{
      contracting_entity_id: "sample_contracting_entity_id",
      tax_jurisdiction: "sample_tax_jurisdiction",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:tax_jurisdiction_evidence, :minimal) do
    BeamPM.Types.TaxJurisdictionEvidence.new(%{
      contracting_entity_id: "sample_contracting_entity_id",
      tax_jurisdiction: "sample_tax_jurisdiction",
      evidence_hash: "sample_evidence_hash"
    })
  end

  def sample(:technical_blocker, :full) do
    BeamPM.Types.TechnicalBlocker.new(%{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
    })
  end

  def sample(:technical_blocker, :minimal) do
    BeamPM.Types.TechnicalBlocker.new(%{
      opportunity_id: "sample_opportunity_id",
      blocker_id: "sample_blocker_id",
      refusal_code: "sample_refusal_code"
    })
  end

  def sample(:termination_right_admission, :full) do
    BeamPM.Types.TerminationRightAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      termination_right_id: "sample_termination_right_id",
      decision: "sample_decision"
    })
  end

  def sample(:termination_right_admission, :minimal) do
    BeamPM.Types.TerminationRightAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      termination_right_id: "sample_termination_right_id",
      decision: "sample_decision"
    })
  end

  def sample(:training_scope_admission, :full) do
    BeamPM.Types.TrainingScopeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      training_scope_id: "sample_training_scope_id",
      decision: "sample_decision"
    })
  end

  def sample(:training_scope_admission, :minimal) do
    BeamPM.Types.TrainingScopeAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      training_scope_id: "sample_training_scope_id",
      decision: "sample_decision"
    })
  end

  def sample(:type_edge, :full) do
    BeamPM.Types.TypeEdge.new(%{
      source_type: "sample_source_type",
      target_type: "sample_target_type",
      qualifier: "sample_qualifier",
      direction: :sample_atom
    })
  end

  def sample(:type_edge, :minimal) do
    BeamPM.Types.TypeEdge.new(%{
      source_type: "sample_source_type",
      target_type: "sample_target_type",
      qualifier: "sample_qualifier",
      direction: :sample_atom
    })
  end

  def sample(:unsupported_capability_evidence, :full) do
    BeamPM.Types.UnsupportedCapabilityEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      capability_name: "sample_capability_name",
      observed_result: :sample_atom
    })
  end

  def sample(:unsupported_capability_evidence, :minimal) do
    BeamPM.Types.UnsupportedCapabilityEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      capability_name: "sample_capability_name",
      observed_result: :sample_atom
    })
  end

  def sample(:upgrade_evidence, :full) do
    BeamPM.Types.UpgradeEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      from_version: "sample_from_version",
      observed_result: :sample_atom
    })
  end

  def sample(:upgrade_evidence, :minimal) do
    BeamPM.Types.UpgradeEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      from_version: "sample_from_version",
      observed_result: :sample_atom
    })
  end

  def sample(:usage_event, :full) do
    BeamPM.Types.UsageEvent.new(%{
      event_id: "sample_event_id",
      entitlement_id: "sample_entitlement_id",
      quantity: 3.5,
      metric_name: "sample_metric_name",
      occurred_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:usage_event, :minimal) do
    BeamPM.Types.UsageEvent.new(%{
      event_id: "sample_event_id",
      entitlement_id: "sample_entitlement_id",
      quantity: 3.5,
      metric_name: "sample_metric_name",
      occurred_at: "2026-08-29T12:00:00Z"
    })
  end

  def sample(:vendor_registration_state, :full) do
    BeamPM.Types.VendorRegistrationState.new(%{
      account_id: "sample_account_id",
      registration_id: "sample_registration_id",
      registration_state: "sample_registration_state"
    })
  end

  def sample(:vendor_registration_state, :minimal) do
    BeamPM.Types.VendorRegistrationState.new(%{
      account_id: "sample_account_id",
      registration_id: "sample_registration_id",
      registration_state: "sample_registration_state"
    })
  end

  def sample(:vendor_risk_evidence, :full) do
    BeamPM.Types.VendorRiskEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      risk_score: 3.5,
      observed_result: :sample_atom
    })
  end

  def sample(:vendor_risk_evidence, :minimal) do
    BeamPM.Types.VendorRiskEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      risk_score: 3.5,
      observed_result: :sample_atom
    })
  end

  def sample(:version_lifecycle_evidence, :full) do
    BeamPM.Types.VersionLifecycleEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      supported_until: "2026-08-29T12:00:00Z",
      observed_result: :sample_atom
    })
  end

  def sample(:version_lifecycle_evidence, :minimal) do
    BeamPM.Types.VersionLifecycleEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      supported_until: "2026-08-29T12:00:00Z",
      observed_result: :sample_atom
    })
  end

  def sample(:volume_tier_admission, :full) do
    BeamPM.Types.VolumeTierAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      volume_tier_id: "sample_volume_tier_id",
      decision: "sample_decision"
    })
  end

  def sample(:volume_tier_admission, :minimal) do
    BeamPM.Types.VolumeTierAdmission.new(%{
      opportunity_id: "sample_opportunity_id",
      volume_tier_id: "sample_volume_tier_id",
      decision: "sample_decision"
    })
  end

  def sample(:vulnerability_scan_evidence, :full) do
    BeamPM.Types.VulnerabilityScanEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      vulnerability_count: 42,
      observed_result: :sample_atom
    })
  end

  def sample(:vulnerability_scan_evidence, :minimal) do
    BeamPM.Types.VulnerabilityScanEvidence.new(%{
      evidence_id: "sample_evidence_id",
      subject_sha: "sample_subject_sha",
      vulnerability_count: 42,
      observed_result: :sample_atom
    })
  end

  def sample(name, variant) do
    raise ArgumentError, "unknown sample #{inspect(name)}.#{inspect(variant)}"
  end

  @doc "Write every record x variant sample as dir/<record>.<variant>.ex.json."
  @spec write_samples(Path.t()) :: :ok
  def write_samples(dir) do
    File.mkdir_p!(dir)

    Enum.each(pairs(), fn {name, variant} ->
      {:ok, struct} = sample(name, variant)
      json = BeamPM.Codec.encode(struct)
      File.write!(Path.join(dir, sample_basename(name, variant, "ex")), json)
    end)

    :ok
  end

  @doc """
  Read every record x variant fixture dir/<record>.<variant>.<suffix>.json,
  decode it, and compare its canonical map against this module's own sample.
  """
  @spec verify_samples(Path.t(), String.t()) :: {non_neg_integer(), [String.t()]}
  def verify_samples(dir, suffix) do
    Enum.reduce(pairs(), {0, []}, fn {name, variant}, {pass, failures} ->
      label = "#{name}.#{variant}"
      path = Path.join(dir, sample_basename(name, variant, suffix))
      {:ok, expected} = sample(name, variant)

      case File.read(path) do
        {:ok, bin} ->
          case BeamPM.Codec.decode(name, bin) do
            {:ok, decoded} ->
              if BeamPM.Codec.to_map(decoded) == BeamPM.Codec.to_map(expected) do
                {pass + 1, failures}
              else
                {pass, failures ++ ["#{label}: map mismatch"]}
              end

            {:error, reason} ->
              {pass, failures ++ ["#{label}: decode error #{inspect(reason)}"]}
          end

        {:error, reason} ->
          {pass, failures ++ ["#{label}: read error #{inspect(reason)}"]}
      end
    end)
  end

  defp pairs do
    for name <- @record_names, variant <- @variants, do: {name, variant}
  end

  defp sample_basename(name, variant, suffix) do
    "#{name}.#{variant}.#{suffix}.json"
  end
end
