# GENERATED by ggen from the admitted bpm:Engine graph (tract). Do not edit.
defmodule BeamPM.Tract do
  @moduledoc ~S"""
  BEAM-side wrapper over the `tract` native engine, compiled to
  `wasm32-wasip1` and hosted inside this VM by wasmex as ONE named engine
  instance. A real ONNX-inference engine (sonos/tract -- the same crate Wasmtime's own WASI-NN implementation uses for this exact target, native/tract-wasm): graph optimization, the compiled runnable plan and the actual tensor ops all happen inside the wasm module; this side only frames base64 ONNX bytes and JSON tensor descriptors. A model is compiled to a runnable plan at load time, so a malformed or unsupported-op ONNX file fails loudly at load, never on first inference; only f32 tensors are supported and anything else is refused explicitly, never coerced.

  This module -- and the Erlang facade `beam4pm_tract` and the Gleam
  facade `beam4pm/tract` that delegate to it 1:1 -- only frames JSON
  requests and unpacks JSON responses; every algorithm runs INSIDE the wasm
  module. All three files are rendered by ggen from the admitted `bpm:Engine`
  / `bpm:EngineOp` / `bpm:EngineArg` facts: the engine's surface is ontology,
  the wasmex hosting below is template, identical for every engine.

  ## Wire contract (linear-memory JSON ABI)

  The wasm module exports `tr_alloc(len) -> ptr`,
  `tr_call(ptr, len) -> packed_u64` (the response buffer packed
  as `(out_ptr << 32) | out_len`) and `tr_dealloc(ptr, len)`.
  Per call (`call/2` below): JSON-encode the request map; `tr_alloc`
  through the same exit-guarded path as the op itself (its own execution is
  microseconds, but a concurrent long op holds the single store-executor
  queue); normalize the i32-as-signed pointer and refuse a null pointer
  rather than write at offset 0; write the bytes (freeing the request buffer
  best-effort if the write fails); `tr_call`; normalize the
  packed u64 (wasmex delivers it as a signed i64) and split ptr/len; read the
  response; `tr_dealloc` the RESPONSE buffer only --
  `tr_call` consumes and frees the request buffer itself, so a
  host-side dealloc of it would be a double free; JSON-decode.

  A call exit or timeout STOPS AND DISCARDS the engine and returns
  `{:error, {:wasmex, {:engine_restarted, _}}}`: the guest builds with
  `panic = "abort"`, so a trap mid-compute may abandon guest state that cannot
  be safely reused. Every model handle is invalidated and the next
  `start/0` builds a fresh instance. Never pass `:infinity` as a timeout.

  ## Ops

  One public function per admitted `bpm:EngineOp`, each taking a trailing
  `opts` keyword list (`:timeout` overrides the op's default budget):

  `load_model/2`,
  `load_model_path/2` (host-side `File.read!/1`, then `load_model`),
  `run/3`,
  `model_info/2`,
  `free_model/2`

  ## Process model and crash semantics

  ONE named Wasmex GenServer (`BeamPM.Tract.Engine`) serves all callers; it
  never blocks during wasm execution and the underlying store executor
  serializes ops in submission order, so concurrent BEAM callers are safe.
  A restart yields a fresh store and invalidates every handle. WASI options
  are the defaults (content is passed by value, no preopens). Degradation
  when the wasm artifact is absent is a NAMED reason (`wasm_built?/0`,
  `wasm_missing_reason/0`), never a fake.
  """

  import Bitwise

  @engine_name BeamPM.Tract.Engine
  @pt_key {__MODULE__, :engine_handles}

  @wasm_rel "native/tract-wasm/target/wasm32-wasip1/release/tract_wasm.wasm"

  @heavy_timeout 60000
  @cheap_timeout 30000

  @typedoc "Decoded string-keyed JSON response from the engine."
  @type resp :: map()

  @typedoc """
  `{:engine, msg}` = the wasm engine returned an error response;
  `{:wasmex, term}` = a host-level failure (engine not started, wasmex
  call/alloc/write failure, or a call timeout/exit).
  """
  @type err :: {:engine, String.t()} | {:wasmex, term()}

  @type result :: {:ok, resp()} | {:error, err()}

  # ---------------------------------------------------------------------
  # Engine lifecycle
  # ---------------------------------------------------------------------

  @doc "Repo-root-relative wasm artifact path, expanded."
  @spec wasm_path() :: String.t()
  def wasm_path, do: Path.expand(@wasm_rel)

  @doc "Whether the wasm engine artifact has been built."
  @spec wasm_built?() :: boolean()
  def wasm_built?, do: File.exists?(wasm_path())

  @doc "Named reason used by the tests' skip tag when the wasm artifact is absent."
  @spec wasm_missing_reason() :: String.t()
  def wasm_missing_reason do
    "tract_wasm.wasm not built at #{wasm_path()} -- run " <>
      "scripts/tract_wasm_build.sh first, and run mix test from the " <>
      "project root"
  end

  @doc """
  Starts (or reuses) the one named engine instance. Idempotent:
  `{:error, {:already_started, pid}}` is normalized to `{:ok, pid}`.
  Restarting after a crash yields a fresh store -- every handle previously
  returned by this engine is invalid afterwards.
  """
  @spec start() :: {:ok, pid()} | {:error, term()}
  def start do
    case start_link_raw() do
      {:ok, pid} ->
        _ = handles!(pid)
        {:ok, pid}

      {:error, {:already_started, pid}} ->
        {:ok, pid}

      other ->
        other
    end
  end

  @doc """
  Raw `Wasmex.start_link/1` under the engine name -- the `child_spec/1`
  start function for use in a supervision tree. Prefer `start/0` for
  direct/test use.
  """
  @spec start_link_raw() :: {:ok, pid()} | {:error, term()}
  def start_link_raw do
    Wasmex.start_link(%{
      bytes: File.read!(wasm_path()),
      wasi: %Wasmex.Wasi.WasiOptions{},
      name: @engine_name
    })
  end

  @doc "Supervision-tree shim (not auto-installed; beam4pm has no Application module)."
  @spec child_spec(term()) :: Supervisor.child_spec()
  def child_spec(_opts) do
    %{
      id: @engine_name,
      start: {__MODULE__, :start_link_raw, []},
      restart: :permanent,
      type: :worker
    }
  end

  # ---------------------------------------------------------------------
  # Ops -- one per admitted bpm:EngineOp, in bpm:opOrder
  # ---------------------------------------------------------------------

  @doc ~S"""
  `{"op":"load_model","model_b64":...}` -- `model_bytes` is the raw ONNX protobuf (base64-encoded host-side; JSON strings cannot carry raw protobuf). Optimizes and compiles to a runnable plan immediately. `{:ok, %{"handle" => n, "inputs" => [%{"name" => s, "shape" => [dims|nil]}], "outputs" => [...]}}` -- a `nil` dim is a symbolic/dynamic axis tract could not fully resolve at load time, reported honestly rather than guessed.
  """
  @spec load_model(binary(), keyword()) :: result()
  def load_model(model_bytes, opts \\ [])
      when is_binary(model_bytes) do
    %{"op" => "load_model", "model_b64" => Base.encode64(model_bytes)}
    |> call(timeout(opts, @heavy_timeout))
  end

  @doc ~S"""
  `File.read!/1` host-side, then `load_model/2` (raises if the path is absent).
  """
  @spec load_model_path(Path.t(), keyword()) :: result()
  def load_model_path(path, opts \\ []) do
    load_model(File.read!(path), opts)
  end

  @doc ~S"""
  `{"op":"run","handle":h,"inputs":[{"shape":[dims],"data":[f32,...]}]}` -- one f32 tensor per declared model input, in order (`inputs` a list of `%{shape: [dims], data: [floats]}`, converted to the wire's string-keyed shape here). `{:ok, %{"outputs" => [%{"shape" => [dims], "data" => [floats]}]}}`, one per declared model output, in order. Real tensor inference, even on a tiny model, draws the heavy timeout budget.
  """
  @spec run(non_neg_integer(), [%{shape: [non_neg_integer()], data: [number()]}], keyword()) :: result()
  def run(handle, inputs, opts \\ [])
      when is_integer(handle) and is_list(inputs) do
    %{"op" => "run", "handle" => handle, "inputs" => Enum.map(inputs, fn %{shape: shape, data: data} -> %{"shape" => shape, "data" => data} end)}
    |> call(timeout(opts, @heavy_timeout))
  end

  @doc ~S"""
  `{"op":"model_info","handle":h}` -- same input/output fact shape as `load_model/2`.
  """
  @spec model_info(non_neg_integer(), keyword()) :: result()
  def model_info(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "model_info", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"free_model","handle":h}` -- releases the model handle; subsequent use errors with an unknown-handle message.
  """
  @spec free_model(non_neg_integer(), keyword()) :: result()
  def free_model(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "free_model", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  # ---------------------------------------------------------------------
  # Core private call -- the wire sequence documented in the moduledoc,
  # against the tr_* exports
  # ---------------------------------------------------------------------

  defp call(req, timeout) when is_map(req) do
    data = JSON.encode!(req)
    len = byte_size(data)

    with {:ok, {pid, store, memory}} <- engine(),
         {:ok, [raw_ptr]} <- call_export(pid, "tr_alloc", [len], timeout),
         ptr = band(raw_ptr, 0xFFFF_FFFF),
         :ok <- if(ptr == 0, do: {:error, :guest_alloc_failed}, else: :ok),
         :ok <- write_request(pid, store, memory, ptr, len, data),
         {:ok, [packed]} <- call_export(pid, "tr_call", [ptr, len], timeout) do
      read_response(pid, store, memory, packed, timeout)
    else
      {:error, {:call_exit, _} = reason} ->
        restart_engine()
        {:error, {:wasmex, {:engine_restarted, reason}}}

      {:error, reason} ->
        {:error, {:wasmex, reason}}
    end
  end

  defp call_export(pid, export, args, timeout) do
    Wasmex.call_function(pid, export, args, timeout)
  catch
    :exit, reason -> {:error, {:call_exit, reason}}
  end

  defp write_request(pid, store, memory, ptr, len, data) do
    case Wasmex.Memory.write_binary(store, memory, ptr, data) do
      :ok ->
        :ok

      {:error, _} = err ->
        _ = call_export(pid, "tr_dealloc", [ptr, len], @cheap_timeout)
        err
    end
  end

  defp read_response(pid, store, memory, packed, timeout) do
    packed = band(packed, 0xFFFF_FFFF_FFFF_FFFF)
    out_ptr = bsr(packed, 32)
    out_len = band(packed, 0xFFFF_FFFF)

    out = Wasmex.Memory.read_binary(store, memory, out_ptr, out_len)
    _ = call_export(pid, "tr_dealloc", [out_ptr, out_len], timeout)

    # bpm:ErrorCollapse_single_key_inspect: only a response whose SOLE key is
    # "error" is an op failure. A response carrying "error" alongside other
    # top-level keys is a structured refusal envelope the caller needs whole,
    # so it passes through as {:ok, decoded} untouched.
    case JSON.decode!(out) do
      %{"error" => err} = decoded when map_size(decoded) == 1 ->
        {:error, {:engine, inspect(err)}}

      decoded ->
        {:ok, decoded}
    end
  end

  defp restart_engine do
    case Process.whereis(@engine_name) do
      nil -> :ok
      pid -> GenServer.stop(pid, :kill)
    end
  catch
    :exit, _ -> :ok
  end

  defp engine do
    case Process.whereis(@engine_name) do
      nil ->
        {:error, {:engine_not_started, "call BeamPM.Tract.start/0 first"}}

      pid ->
        {:ok, handles!(pid)}
    end
  end

  defp handles!(pid) do
    case :persistent_term.get(@pt_key, nil) do
      {^pid, _store, _memory} = cached ->
        cached

      _stale_or_missing ->
        {:ok, store} = Wasmex.store(pid)
        {:ok, memory} = Wasmex.memory(pid)
        entry = {pid, store, memory}
        :persistent_term.put(@pt_key, entry)
        entry
    end
  end

  defp timeout(opts, default), do: Keyword.get(opts, :timeout, default)
end

defmodule BeamPM.Tract.Health do
  @moduledoc """
  A single-candidate engine-health status probe for the tract engine:
  a typed, structured answer to "is the one engine we have actually alive
  right now", checked for real (artifact on disk AND the engine process can
  actually start), not discovered only at the first real call. One probe per
  engine, never a `select/2`-with-fallback ranking -- there is exactly one
  candidate per domain.
  """

  @type standing :: :alive | :blocked
  @type status :: %{
          id: :tract_wasm,
          kind: :engine,
          standing: standing(),
          reason: String.t() | nil,
          evidence: %{wasm_path: String.t(), artifact_present: boolean(), engine_started: boolean() | nil}
        }

  @doc """
  Real health check: confirms the wasm artifact exists on disk AND that
  the engine can actually start (or is already started).
  """
  @spec status() :: status()
  def status do
    artifact_present = BeamPM.Tract.wasm_built?()

    if artifact_present do
      case BeamPM.Tract.start() do
        {:ok, _pid} ->
          %{
            id: :tract_wasm,
            kind: :engine,
            standing: :alive,
            reason: nil,
            evidence: %{
              wasm_path: BeamPM.Tract.wasm_path(),
              artifact_present: true,
              engine_started: true
            }
          }

        {:error, reason} ->
          %{
            id: :tract_wasm,
            kind: :engine,
            standing: :blocked,
            reason: "artifact present but engine failed to start: #{inspect(reason)}",
            evidence: %{
              wasm_path: BeamPM.Tract.wasm_path(),
              artifact_present: true,
              engine_started: false
            }
          }
      end
    else
      %{
        id: :tract_wasm,
        kind: :engine,
        standing: :blocked,
        reason: BeamPM.Tract.wasm_missing_reason(),
        evidence: %{
          wasm_path: BeamPM.Tract.wasm_path(),
          artifact_present: false,
          engine_started: nil
        }
      }
    end
  end
end
