# GENERATED by ggen from the admitted bpm:Engine graph (ferroplan). Do not edit.
defmodule BeamPM.Ferroplan do
  @moduledoc ~S"""
  BEAM-side wrapper over the `ferroplan` native engine, compiled to
  `wasm32-wasip1` and hosted inside this VM by wasmex as ONE named engine
  instance. The ferroplan PDDL planning engine (`seanchatmangpt/ferroplan`, the native/ferroplan submodule): grounding, search, temporal/PDDL3 solving and session-based replanning all happen inside the wasm module (`crates/ferroplan-wasm/src/wasi_abi.rs` upstream). The session ops mirror the native `ferroplan::Session` surface one-for-one through an integer session handle.

  This module -- and the Erlang facade `beam4pm_ferroplan` and the Gleam
  facade `beam4pm/ferroplan` that delegate to it 1:1 -- only frames JSON
  requests and unpacks JSON responses; every algorithm runs INSIDE the wasm
  module. All three files are rendered by ggen from the admitted `bpm:Engine`
  / `bpm:EngineOp` / `bpm:EngineArg` facts: the engine's surface is ontology,
  the wasmex hosting below is template, identical for every engine.

  ## Wire contract (linear-memory JSON ABI)

  The wasm module exports `fp_alloc(len) -> ptr`,
  `fp_call(ptr, len) -> packed_u64` (the response buffer packed
  as `(out_ptr << 32) | out_len`) and `fp_dealloc(ptr, len)`.
  Per call (`call/2` below): JSON-encode the request map; `fp_alloc`
  through the same exit-guarded path as the op itself (its own execution is
  microseconds, but a concurrent long op holds the single store-executor
  queue); normalize the i32-as-signed pointer and refuse a null pointer
  rather than write at offset 0; write the bytes (freeing the request buffer
  best-effort if the write fails); `fp_call`; normalize the
  packed u64 (wasmex delivers it as a signed i64) and split ptr/len; read the
  response; `fp_dealloc` the RESPONSE buffer only --
  `fp_call` consumes and frees the request buffer itself, so a
  host-side dealloc of it would be a double free; JSON-decode.

  A call exit or timeout STOPS AND DISCARDS the engine and returns
  `{:error, {:wasmex, {:engine_restarted, _}}}`: the guest builds with
  `panic = "abort"`, so a trap mid-compute may abandon guest state that cannot
  be safely reused. Every session handle is invalidated and the next
  `start/0` builds a fresh instance. Never pass `:infinity` as a timeout.

  ## Ops

  One public function per admitted `bpm:EngineOp`, each taking a trailing
  `opts` keyword list (`:timeout` overrides the op's default budget):

  `plan/4`,
  `plan_production/4`,
  `readiness/1`,
  `version/1`,
  `explain/4`,
  `session_new/3`,
  `session_fork/2`,
  `session_free/2`,
  `session_set_goal/3`,
  `session_restrict_prefix_claims/4`,
  `session_restrict_contains/3`,
  `session_think/4`,
  `session_valid?/2`,
  `session_step/2`,
  `session_suffix/2`,
  `session_advance/2`,
  `session_drop_plan/2`,
  `session_has_plan?/2`,
  `session_set_fact/4`,
  `session_set_timed_fact/5`,
  `session_observe/3`,
  `session_goal_met?/2`,
  `session_fact/3`,
  `session_apply_start/3`,
  `session_elapse/3`,
  `session_set_fluent/4`,
  `session_fluent/3`,
  `session_plan_valid?/4`,
  `session_world_bytes/2`,
  `session_mind_bytes/2`,
  `hddl_solve/3`

  ## Process model and crash semantics

  ONE named Wasmex GenServer (`BeamPM.Ferroplan.Engine`) serves all callers; it
  never blocks during wasm execution and the underlying store executor
  serializes ops in submission order, so concurrent BEAM callers are safe.
  A restart yields a fresh store and invalidates every handle. WASI options
  are the defaults (content is passed by value, no preopens). Degradation
  when the wasm artifact is absent is a NAMED reason (`wasm_built?/0`,
  `wasm_missing_reason/0`), never a fake.
  """

  import Bitwise

  @engine_name BeamPM.Ferroplan.Engine
  @pt_key {__MODULE__, :engine_handles}

  @wasm_rel "native/ferroplan/target/wasm32-wasip1/release/ferroplan_wasm.wasm"

  @heavy_timeout 120000
  @cheap_timeout 30000

  @typedoc "Decoded string-keyed JSON response from the engine."
  @type resp :: map()

  @typedoc """
  `{:engine, msg}` = the wasm engine returned an error response;
  `{:wasmex, term}` = a host-level failure (engine not started, wasmex
  call/alloc/write failure, or a call timeout/exit).
  """
  @type err :: {:engine, String.t()} | {:wasmex, term()}

  @type result :: {:ok, resp()} | {:error, err()}

  # ---------------------------------------------------------------------
  # Engine lifecycle
  # ---------------------------------------------------------------------

  @doc "Repo-root-relative wasm artifact path, expanded."
  @spec wasm_path() :: String.t()
  def wasm_path, do: Path.expand(@wasm_rel)

  @doc "Whether the wasm engine artifact has been built."
  @spec wasm_built?() :: boolean()
  def wasm_built?, do: File.exists?(wasm_path())

  @doc "Named reason used by the tests' skip tag when the wasm artifact is absent."
  @spec wasm_missing_reason() :: String.t()
  def wasm_missing_reason do
    "ferroplan_wasm.wasm not built at #{wasm_path()} -- run " <>
      "scripts/ferroplan_wasm_build.sh first (after `git submodule update --init --recursive` if native/ferroplan is empty), and run mix test from the " <>
      "project root"
  end

  @doc """
  Starts (or reuses) the one named engine instance. Idempotent:
  `{:error, {:already_started, pid}}` is normalized to `{:ok, pid}`.
  Restarting after a crash yields a fresh store -- every handle previously
  returned by this engine is invalid afterwards.
  """
  @spec start() :: {:ok, pid()} | {:error, term()}
  def start do
    case start_link_raw() do
      {:ok, pid} ->
        _ = handles!(pid)
        {:ok, pid}

      {:error, {:already_started, pid}} ->
        {:ok, pid}

      other ->
        other
    end
  end

  @doc """
  Raw `Wasmex.start_link/1` under the engine name -- the `child_spec/1`
  start function for use in a supervision tree. Prefer `start/0` for
  direct/test use.
  """
  @spec start_link_raw() :: {:ok, pid()} | {:error, term()}
  def start_link_raw do
    Wasmex.start_link(%{
      bytes: File.read!(wasm_path()),
      wasi: %Wasmex.Wasi.WasiOptions{},
      name: @engine_name
    })
  end

  @doc "Supervision-tree shim (not auto-installed; beam4pm has no Application module)."
  @spec child_spec(term()) :: Supervisor.child_spec()
  def child_spec(_opts) do
    %{
      id: @engine_name,
      start: {__MODULE__, :start_link_raw, []},
      restart: :permanent,
      type: :worker
    }
  end

  # ---------------------------------------------------------------------
  # Ops -- one per admitted bpm:EngineOp, in bpm:opOrder
  # ---------------------------------------------------------------------

  @doc ~S"""
  `{"op":"plan","domain":d,"problem":p[,"mode":m,"flags":f,"search":s]}` -- the compatibility solve surface (lenient mode/search parsing, single threaded). `extra` (default `%{}`) is merged into the request. Returns `{:ok, <Solution map>}`.
  """
  @spec plan(String.t(), String.t(), map(), keyword()) :: result()
  def plan(domain, problem, extra \\ %{}, opts \\ [])
      when is_binary(domain) and is_binary(problem) and is_map(extra) do
    %{"op" => "plan", "domain" => domain, "problem" => problem}
    |> Map.merge(extra)
    |> call(timeout(opts, @heavy_timeout))
  end

  @doc ~S"""
  `{"op":"plan_production","domain":d,"problem":p[,"mode":m,"search":s,"max_evaluated":n,"max_plan_steps":n,"max_output_bytes":n,"request_id":id]}` -- bounded production solve: strict mode/search parsing, a versioned `OperationEnvelope` response, always candidate-only. A strict-mode refusal arrives as `{:ok, envelope}` with its own `outcome`, never a bare `{:error, _}` (bpm:ErrorCollapse_single_key_inspect).
  """
  @spec plan_production(String.t(), String.t(), map(), keyword()) :: result()
  def plan_production(domain, problem, extra \\ %{}, opts \\ [])
      when is_binary(domain) and is_binary(problem) and is_map(extra) do
    %{"op" => "plan_production", "domain" => domain, "problem" => problem}
    |> Map.merge(extra)
    |> call(timeout(opts, @heavy_timeout))
  end

  @doc ~S"""
  `{"op":"readiness"}` -- capability manifest + deterministic fingerprint.
  """
  @spec readiness(keyword()) :: result()
  def readiness(opts \\ []) do
    %{"op" => "readiness"}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"version"}` -- `{:ok, %{"version" => semver}}`, the crate's own version.
  """
  @spec version(keyword()) :: result()
  def version(opts \\ []) do
    %{"op" => "version"}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"explain","domain":d,"problem":p,"plan":plan}` -- `plan` is a decoded Plan map (not a JSON string). Returns the explanation JSON.
  """
  @spec explain(String.t(), String.t(), map(), keyword()) :: result()
  def explain(domain, problem, plan, opts \\ [])
      when is_binary(domain) and is_binary(problem) and is_map(plan) do
    %{"op" => "explain", "domain" => domain, "problem" => problem, "plan" => plan}
    |> call(timeout(opts, @heavy_timeout))
  end

  @doc ~S"""
  `{"op":"session_new","domain":d,"problem":p}` -- grounds a new session. Returns `{:ok, %{"handle" => n}}`.
  """
  @spec session_new(String.t(), String.t(), keyword()) :: result()
  def session_new(domain, problem, opts \\ [])
      when is_binary(domain) and is_binary(problem) do
    %{"op" => "session_new", "domain" => domain, "problem" => problem}
    |> call(timeout(opts, @heavy_timeout))
  end

  @doc ~S"""
  `{"op":"session_fork","handle":h}` -- a cheap fork sharing the grounded world, with independent mutable state (fresh plan/cursor).
  """
  @spec session_fork(non_neg_integer(), keyword()) :: result()
  def session_fork(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_fork", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_free","handle":h}` -- releases the session handle.
  """
  @spec session_free(non_neg_integer(), keyword()) :: result()
  def session_free(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_free", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_set_goal","handle":h,"goal":g}`.
  """
  @spec session_set_goal(non_neg_integer(), String.t(), keyword()) :: result()
  def session_set_goal(handle, goal, opts \\ [])
      when is_integer(handle) and is_binary(goal) do
    %{"op" => "session_set_goal", "handle" => handle, "goal" => goal}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_restrict_prefix_claims","handle":h,"prefix":pre,"claimed":csv}` -- the bazaar's op-display-prefix-plus-claims-blackout scoping (`claimed` is a comma-separated string, as the wasm ABI expects).
  """
  @spec session_restrict_prefix_claims(non_neg_integer(), String.t(), String.t(), keyword()) :: result()
  def session_restrict_prefix_claims(handle, prefix, claimed, opts \\ [])
      when is_integer(handle) and is_binary(prefix) and is_binary(claimed) do
    %{"op" => "session_restrict_prefix_claims", "handle" => handle, "prefix" => prefix, "claimed" => claimed}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_restrict_contains","handle":h,"filter":f}`.
  """
  @spec session_restrict_contains(non_neg_integer(), String.t(), keyword()) :: result()
  def session_restrict_contains(handle, filter, opts \\ [])
      when is_integer(handle) and is_binary(filter) do
    %{"op" => "session_restrict_contains", "handle" => handle, "filter" => filter}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_think","handle":h,"evals":n,"mem_mb":n}` -- a bounded replan (bounded by evals/memory, not wall clock); stashes the resulting plan (if solved) and resets the cursor. Returns the Solution map.
  """
  @spec session_think(non_neg_integer(), non_neg_integer(), non_neg_integer(), keyword()) :: result()
  def session_think(handle, evals, mem_mb, opts \\ [])
      when is_integer(handle) and is_integer(evals) and is_integer(mem_mb) do
    %{"op" => "session_think", "handle" => handle, "evals" => evals, "mem_mb" => mem_mb}
    |> call(timeout(opts, @heavy_timeout))
  end

  @doc ~S"""
  `{"op":"session_valid","handle":h}` -- free replay check of the stashed plan's suffix from the cursor, no search spent. `{:ok, %{"valid" => bool}}`. Elixir names it `session_valid?`.
  """
  @spec session_valid?(non_neg_integer(), keyword()) :: result()
  def session_valid?(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_valid", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_step","handle":h}` -- the step under the cursor, or `null`.
  """
  @spec session_step(non_neg_integer(), keyword()) :: result()
  def session_step(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_step", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_suffix","handle":h}` -- the remaining plan steps from the cursor onward.
  """
  @spec session_suffix(non_neg_integer(), keyword()) :: result()
  def session_suffix(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_suffix", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_advance","handle":h}` -- advances the cursor by one step.
  """
  @spec session_advance(non_neg_integer(), keyword()) :: result()
  def session_advance(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_advance", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_drop_plan","handle":h}` -- clears the stashed plan and cursor.
  """
  @spec session_drop_plan(non_neg_integer(), keyword()) :: result()
  def session_drop_plan(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_drop_plan", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_has_plan","handle":h}` -- `{:ok, %{"has_plan" => bool}}`. Elixir names it `session_has_plan?`.
  """
  @spec session_has_plan?(non_neg_integer(), keyword()) :: result()
  def session_has_plan?(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_has_plan", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_set_fact","handle":h,"name":n,"value":bool}` -- sets a boolean fact in the session's world.
  """
  @spec session_set_fact(non_neg_integer(), String.t(), boolean(), keyword()) :: result()
  def session_set_fact(handle, name, value, opts \\ [])
      when is_integer(handle) and is_binary(name) and is_boolean(value) do
    %{"op" => "session_set_fact", "handle" => handle, "name" => name, "value" => value}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_set_timed_fact","handle":h,"dt":f,"name":n,"value":bool}` -- a fact scheduled at time offset `dt`.
  """
  @spec session_set_timed_fact(non_neg_integer(), number(), String.t(), boolean(), keyword()) :: result()
  def session_set_timed_fact(handle, dt, name, value, opts \\ [])
      when is_integer(handle) and is_number(dt) and is_binary(name) and is_boolean(value) do
    %{"op" => "session_set_timed_fact", "handle" => handle, "dt" => dt, "name" => name, "value" => value}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_observe","handle":h,"sight":[[name,value],...]}` -- a batch of observed (fact, value) pairs (`[{name, bool}]` tuples host-side, rendered as 2-element lists). Returns the resulting news/deltas.
  """
  @spec session_observe(non_neg_integer(), [{String.t(), boolean()}], keyword()) :: result()
  def session_observe(handle, sight, opts \\ [])
      when is_integer(handle) and is_list(sight) do
    %{"op" => "session_observe", "handle" => handle, "sight" => Enum.map(sight, &Tuple.to_list/1)}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_goal_met","handle":h}` -- `{:ok, %{"goal_met" => bool}}`. Elixir names it `session_goal_met?`.
  """
  @spec session_goal_met?(non_neg_integer(), keyword()) :: result()
  def session_goal_met?(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_goal_met", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_fact","handle":h,"name":n}` -- `{:ok, %{"value" => bool | nil}}`.
  """
  @spec session_fact(non_neg_integer(), String.t(), keyword()) :: result()
  def session_fact(handle, name, opts \\ [])
      when is_integer(handle) and is_binary(name) do
    %{"op" => "session_fact", "handle" => handle, "name" => name}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_apply_start","handle":h,"name":n}` -- applies the start of a (possibly durative) action by name.
  """
  @spec session_apply_start(non_neg_integer(), String.t(), keyword()) :: result()
  def session_apply_start(handle, name, opts \\ [])
      when is_integer(handle) and is_binary(name) do
    %{"op" => "session_apply_start", "handle" => handle, "name" => name}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_elapse","handle":h,"dt":f}` -- advances simulated time; returns the effects/events that fired.
  """
  @spec session_elapse(non_neg_integer(), number(), keyword()) :: result()
  def session_elapse(handle, dt, opts \\ [])
      when is_integer(handle) and is_number(dt) do
    %{"op" => "session_elapse", "handle" => handle, "dt" => dt}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_set_fluent","handle":h,"name":n,"value":f}` -- sets a numeric fluent.
  """
  @spec session_set_fluent(non_neg_integer(), String.t(), number(), keyword()) :: result()
  def session_set_fluent(handle, name, value, opts \\ [])
      when is_integer(handle) and is_binary(name) and is_number(value) do
    %{"op" => "session_set_fluent", "handle" => handle, "name" => name, "value" => value}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_fluent","handle":h,"name":n}` -- `{:ok, %{"value" => f64 | nil}}`.
  """
  @spec session_fluent(non_neg_integer(), String.t(), keyword()) :: result()
  def session_fluent(handle, name, opts \\ [])
      when is_integer(handle) and is_binary(name) do
    %{"op" => "session_fluent", "handle" => handle, "name" => name}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_plan_valid","handle":h,"plan":plan,"from":n}` -- checks an externally-supplied plan is still valid from step index `from`, without mutating session state. Elixir names it `session_plan_valid?`.
  """
  @spec session_plan_valid?(non_neg_integer(), map(), non_neg_integer(), keyword()) :: result()
  def session_plan_valid?(handle, plan, from, opts \\ [])
      when is_integer(handle) and is_map(plan) and is_integer(from) do
    %{"op" => "session_plan_valid", "handle" => handle, "plan" => plan, "from" => from}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_world_bytes","handle":h}` -- byte size of the shared/grounded world state.
  """
  @spec session_world_bytes(non_neg_integer(), keyword()) :: result()
  def session_world_bytes(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_world_bytes", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"session_mind_bytes","handle":h}` -- byte size of this session's private mutable state.
  """
  @spec session_mind_bytes(non_neg_integer(), keyword()) :: result()
  def session_mind_bytes(handle, opts \\ [])
      when is_integer(handle) do
    %{"op" => "session_mind_bytes", "handle" => handle}
    |> call(timeout(opts, @cheap_timeout))
  end

  @doc ~S"""
  `{"op":"hddl_solve","domain":d,"problem":p[,"limits":{...}]}` -- `domain`/`problem` are HDDL source text (not classical PDDL): parsed, grounded, and translated by `ferroplan_hddl`, then solved by the existing FOND policy solver (`ferroplan::solve_hddl`). `limits` (optional; a partial `PlannerLimits` map -- `max_depth`/`max_states`/`max_iterations`, any/all omitted) is merged into the request. Returns `{:ok, <UniversalPlan map>}`. A malformed/unsolvable HDDL document surfaces as `{:ok, %{"error" => %{"code" => ..., "message" => ..., "retryable" => bool}}}` with a code naming the failing stage (`FP_PARSE`, `FP_HDDL_GROUND`, `FP_HDDL_TRANSLATE`, `FP_MODEL`) -- never a bare `{:error, _}` -- matching every other solve op's error-in-envelope convention (bpm:ErrorCollapse_single_key_inspect).
  """
  @spec hddl_solve(String.t(), String.t(), keyword()) :: result()
  def hddl_solve(domain, problem, opts \\ [])
      when is_binary(domain) and is_binary(problem) do
    %{"op" => "hddl_solve", "domain" => domain, "problem" => problem}
    |> call(timeout(opts, @heavy_timeout))
  end

  # ---------------------------------------------------------------------
  # Core private call -- the wire sequence documented in the moduledoc,
  # against the fp_* exports
  # ---------------------------------------------------------------------

  defp call(req, timeout) when is_map(req) do
    data = JSON.encode!(req)
    len = byte_size(data)

    with {:ok, {pid, store, memory}} <- engine(),
         {:ok, [raw_ptr]} <- call_export(pid, "fp_alloc", [len], timeout),
         ptr = band(raw_ptr, 0xFFFF_FFFF),
         :ok <- if(ptr == 0, do: {:error, :guest_alloc_failed}, else: :ok),
         :ok <- write_request(pid, store, memory, ptr, len, data),
         {:ok, [packed]} <- call_export(pid, "fp_call", [ptr, len], timeout) do
      read_response(pid, store, memory, packed, timeout)
    else
      {:error, {:call_exit, _} = reason} ->
        restart_engine()
        {:error, {:wasmex, {:engine_restarted, reason}}}

      {:error, reason} ->
        {:error, {:wasmex, reason}}
    end
  end

  defp call_export(pid, export, args, timeout) do
    Wasmex.call_function(pid, export, args, timeout)
  catch
    :exit, reason -> {:error, {:call_exit, reason}}
  end

  defp write_request(pid, store, memory, ptr, len, data) do
    case Wasmex.Memory.write_binary(store, memory, ptr, data) do
      :ok ->
        :ok

      {:error, _} = err ->
        _ = call_export(pid, "fp_dealloc", [ptr, len], @cheap_timeout)
        err
    end
  end

  defp read_response(pid, store, memory, packed, timeout) do
    packed = band(packed, 0xFFFF_FFFF_FFFF_FFFF)
    out_ptr = bsr(packed, 32)
    out_len = band(packed, 0xFFFF_FFFF)

    out = Wasmex.Memory.read_binary(store, memory, out_ptr, out_len)
    _ = call_export(pid, "fp_dealloc", [out_ptr, out_len], timeout)

    # bpm:ErrorCollapse_single_key_inspect: only a response whose SOLE key is
    # "error" is an op failure. A response carrying "error" alongside other
    # top-level keys is a structured refusal envelope the caller needs whole,
    # so it passes through as {:ok, decoded} untouched.
    case JSON.decode!(out) do
      %{"error" => err} = decoded when map_size(decoded) == 1 ->
        {:error, {:engine, inspect(err)}}

      decoded ->
        {:ok, decoded}
    end
  end

  defp restart_engine do
    case Process.whereis(@engine_name) do
      nil -> :ok
      pid -> GenServer.stop(pid, :kill)
    end
  catch
    :exit, _ -> :ok
  end

  defp engine do
    case Process.whereis(@engine_name) do
      nil ->
        {:error, {:engine_not_started, "call BeamPM.Ferroplan.start/0 first"}}

      pid ->
        {:ok, handles!(pid)}
    end
  end

  defp handles!(pid) do
    case :persistent_term.get(@pt_key, nil) do
      {^pid, _store, _memory} = cached ->
        cached

      _stale_or_missing ->
        {:ok, store} = Wasmex.store(pid)
        {:ok, memory} = Wasmex.memory(pid)
        entry = {pid, store, memory}
        :persistent_term.put(@pt_key, entry)
        entry
    end
  end

  defp timeout(opts, default), do: Keyword.get(opts, :timeout, default)
end

defmodule BeamPM.Ferroplan.Health do
  @moduledoc """
  A single-candidate engine-health status probe for the ferroplan engine:
  a typed, structured answer to "is the one engine we have actually alive
  right now", checked for real (artifact on disk AND the engine process can
  actually start), not discovered only at the first real call. One probe per
  engine, never a `select/2`-with-fallback ranking -- there is exactly one
  candidate per domain.
  """

  @type standing :: :alive | :blocked
  @type status :: %{
          id: :ferroplan_wasm,
          kind: :engine,
          standing: standing(),
          reason: String.t() | nil,
          evidence: %{wasm_path: String.t(), artifact_present: boolean(), engine_started: boolean() | nil}
        }

  @doc """
  Real health check: confirms the wasm artifact exists on disk AND that
  the engine can actually start (or is already started).
  """
  @spec status() :: status()
  def status do
    artifact_present = BeamPM.Ferroplan.wasm_built?()

    if artifact_present do
      case BeamPM.Ferroplan.start() do
        {:ok, _pid} ->
          %{
            id: :ferroplan_wasm,
            kind: :engine,
            standing: :alive,
            reason: nil,
            evidence: %{
              wasm_path: BeamPM.Ferroplan.wasm_path(),
              artifact_present: true,
              engine_started: true
            }
          }

        {:error, reason} ->
          %{
            id: :ferroplan_wasm,
            kind: :engine,
            standing: :blocked,
            reason: "artifact present but engine failed to start: #{inspect(reason)}",
            evidence: %{
              wasm_path: BeamPM.Ferroplan.wasm_path(),
              artifact_present: true,
              engine_started: false
            }
          }
      end
    else
      %{
        id: :ferroplan_wasm,
        kind: :engine,
        standing: :blocked,
        reason: BeamPM.Ferroplan.wasm_missing_reason(),
        evidence: %{
          wasm_path: BeamPM.Ferroplan.wasm_path(),
          artifact_present: false,
          engine_started: nil
        }
      }
    end
  end
end
