# GENERATED by ggen from the admitted bap:RuntimeModule graph in ontology.ttl. Do not edit.
defmodule BeamPM.ResearchRuntime.Deadline do
  @moduledoc false
  def expired?(d,n \\ System.monotonic_time(:millisecond)), do: n>=d
end
