# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.AutonomicReceiptCompletenessCheck do
  @moduledoc "Refuses any actuation receipt missing subject, authority, before-state, after-state, or result identity."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:autonomic_receipt_completeness_check,
      attributes: [
        actuation_id: :string,
        subject_sha: :string,
        authority_receipt_sha: :string,
        state_digest: :string
      ]
    )

    activity(:autonomic_receipt_completeness_check_created,
      on: :create,
      object_type: :autonomic_receipt_completeness_check
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:actuation_id, :string, public?: true, allow_nil?: false)
    attribute(:subject_sha, :string, public?: true, allow_nil?: false)
    attribute(:authority_receipt_sha, :string, public?: true, allow_nil?: false)
    attribute(:state_digest, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
