# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.BaselineMetric do
  @moduledoc "Pre-POC customer baseline used to falsify or confirm realized value."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :baseline_metric_id, :string, public?: true, allow_nil?: false
    attribute :account_id, :string, public?: true, allow_nil?: false
    attribute :baseline_value, :float, public?: true, allow_nil?: false
    attribute :evidence_digest, :string, public?: true, allow_nil?: false
    attribute :observed_at, :utc_datetime, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

