# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.CommercialForecast do
  @moduledoc "Time-bound account forecast with amount and confidence."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:commercial_forecast,
      attributes: [forecast_id: :string, account_id: :string, amount: :float, confidence: :float]
    )

    activity(:commercial_forecast_created, on: :create, object_type: :commercial_forecast)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:forecast_id, :string, public?: true, allow_nil?: false)
    attribute(:account_id, :string, public?: true, allow_nil?: false)
    attribute(:amount, :float, public?: true, allow_nil?: false)
    attribute(:confidence, :float, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
