# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.CommercialApproval do
  @moduledoc "Commercial approval decision with exact subject and authority."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:commercial_approval,
      attributes: [approval_id: :string, quote_id: :string, authority: :string, status: :atom]
    )

    activity(:commercial_approval_created, on: :create, object_type: :commercial_approval)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:approval_id, :string, public?: true, allow_nil?: false)
    attribute(:quote_id, :string, public?: true, allow_nil?: false)
    attribute(:authority, :string, public?: true, allow_nil?: false)
    attribute(:status, :atom, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
