# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.CompatibilityContract do
  @moduledoc "Compatibility declaration across product, schema, and API versions."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :contract_id, :string, public?: true, allow_nil?: false
    attribute :product_version, :string, public?: true, allow_nil?: false
    attribute :schema_version, :string, public?: true, allow_nil?: false
    attribute :api_version, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

