# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.ConfigurationExport do
  @moduledoc "Receiptable export of deterministic enterprise configuration."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:configuration_export,
      attributes: [
        export_id: :string,
        tenant_id: :string,
        configuration_hash: :string,
        exported_at: :datetime
      ]
    )

    activity(:configuration_export_created, on: :create, object_type: :configuration_export)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:export_id, :string, public?: true, allow_nil?: false)
    attribute(:tenant_id, :string, public?: true, allow_nil?: false)
    attribute(:configuration_hash, :string, public?: true, allow_nil?: false)
    attribute(:exported_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
