# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.ConsumptionSubscription do
  @moduledoc "Consumption package binding plan, account, and standing."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :subscription_id, :string, public?: true, allow_nil?: false
    attribute :account_id, :string, public?: true, allow_nil?: false
    attribute :plan_id, :string, public?: true, allow_nil?: false
    attribute :status, :atom, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

