# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.CrashRecoveryReceipt do
  @moduledoc "Produces replayable evidence that a runtime crash reached a verified recovery consequence."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:crash_recovery_receipt,
      attributes: [tenant_id: :string, crash_id: :string, receipt_hash: :string]
    )

    activity(:crash_recovery_receipt_created, on: :create, object_type: :crash_recovery_receipt)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:tenant_id, :string, public?: true, allow_nil?: false)
    attribute(:crash_id, :string, public?: true, allow_nil?: false)
    attribute(:receipt_hash, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
