# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.CrownExecutionMode do
  @moduledoc "Records whether qualification ran locally, in a capsule, or on a hosted runner."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:crown_execution_mode,
      attributes: [
        propagation_id: :string,
        subject_sha: :string,
        execution_mode: :string,
        receipt_digest: :string
      ]
    )

    activity(:crown_execution_mode_created, on: :create, object_type: :crown_execution_mode)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:propagation_id, :string, public?: true, allow_nil?: false)
    attribute(:subject_sha, :string, public?: true, allow_nil?: false)
    attribute(:execution_mode, :string, public?: true, allow_nil?: false)
    attribute(:receipt_digest, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
