# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.CrownDependencyEdge do
  @moduledoc "Declares one exact upstream-to-downstream propagation edge in the ecosystem graph."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:crown_dependency_edge,
      attributes: [
        propagation_id: :string,
        subject_sha: :string,
        downstream_consumer_id: :string,
        receipt_digest: :string
      ]
    )

    activity(:crown_dependency_edge_created, on: :create, object_type: :crown_dependency_edge)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:propagation_id, :string, public?: true, allow_nil?: false)
    attribute(:subject_sha, :string, public?: true, allow_nil?: false)
    attribute(:downstream_consumer_id, :string, public?: true, allow_nil?: false)
    attribute(:receipt_digest, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
