# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.CustomerSignalObservation do
  @moduledoc "Normalizes a customer signal into typed, digest-bound evidence."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:customer_signal_observation,
      attributes: [
        customer_id: :string,
        signal_type: :string,
        signal_digest: :string,
        observed_at: :datetime
      ]
    )

    activity(:customer_signal_observation_created,
      on: :create,
      object_type: :customer_signal_observation
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:customer_id, :string, public?: true, allow_nil?: false)
    attribute(:signal_type, :string, public?: true, allow_nil?: false)
    attribute(:signal_digest, :string, public?: true, allow_nil?: false)
    attribute(:observed_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
