# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.DealDeskPacket do
  @moduledoc "Binds cross-functional deal-desk approval evidence into one replayable packet identity."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :opportunity_id, :string, public?: true, allow_nil?: false
    attribute :packet_id, :string, public?: true, allow_nil?: false
    attribute :evidence_hash, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

