# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.DemoScenario do
  @moduledoc "Account-specific executable demonstration scenario for enterprise evaluation."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:demo_scenario,
      attributes: [
        demo_scenario_id: :string,
        account_id: :string,
        scenario_name: :string,
        evidence_digest: :string,
        observed_at: :datetime
      ]
    )

    activity(:demo_scenario_created, on: :create, object_type: :demo_scenario)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:demo_scenario_id, :string, public?: true, allow_nil?: false)
    attribute(:account_id, :string, public?: true, allow_nil?: false)
    attribute(:scenario_name, :string, public?: true, allow_nil?: false)
    attribute(:evidence_digest, :string, public?: true, allow_nil?: false)
    attribute(:observed_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
