# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.EditionDowngradePath do
  @moduledoc "Controlled commercial edition downgrade path."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:edition_downgrade_path,
      attributes: [
        edition_downgrade_path_id: :string,
        account_id: :string,
        target_edition_id: :string,
        evidence_digest: :string,
        effective_at: :datetime
      ]
    )

    activity(:edition_downgrade_path_created, on: :create, object_type: :edition_downgrade_path)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:edition_downgrade_path_id, :string, public?: true, allow_nil?: false)
    attribute(:account_id, :string, public?: true, allow_nil?: false)
    attribute(:target_edition_id, :string, public?: true, allow_nil?: false)
    attribute(:evidence_digest, :string, public?: true, allow_nil?: false)
    attribute(:effective_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
