# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.EnterpriseAgreement do
  @moduledoc "Enterprise commercial umbrella agreement."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:enterprise_agreement,
      attributes: [
        enterprise_agreement_id: :string,
        account_id: :string,
        agreement_version: :string,
        evidence_digest: :string,
        effective_at: :datetime
      ]
    )

    activity(:enterprise_agreement_created, on: :create, object_type: :enterprise_agreement)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:enterprise_agreement_id, :string, public?: true, allow_nil?: false)
    attribute(:account_id, :string, public?: true, allow_nil?: false)
    attribute(:agreement_version, :string, public?: true, allow_nil?: false)
    attribute(:evidence_digest, :string, public?: true, allow_nil?: false)
    attribute(:effective_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
