# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.EnterpriseOrderLine do
  @moduledoc "Order line preserving SKU, quantity, and contracted unit price."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:enterprise_order_line,
      attributes: [order_id: :string, sku: :string, quantity: :integer, unit_price: :float]
    )

    activity(:enterprise_order_line_created, on: :create, object_type: :enterprise_order_line)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:order_id, :string, public?: true, allow_nil?: false)
    attribute(:sku, :string, public?: true, allow_nil?: false)
    attribute(:quantity, :integer, public?: true, allow_nil?: false)
    attribute(:unit_price, :float, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
