# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.ExactWorldStateAdmission do
  @moduledoc "Admits an exact immutable world-state subject before option generation."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:exact_world_state_admission,
      attributes: [subject_sha: :string, state_digest: :string, observed_at: :datetime]
    )

    activity(:exact_world_state_admission_created,
      on: :create,
      object_type: :exact_world_state_admission
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:subject_sha, :string, public?: true, allow_nil?: false)
    attribute(:state_digest, :string, public?: true, allow_nil?: false)
    attribute(:observed_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
