# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.InformationPartitionObservation do
  @moduledoc "Partitions a state vector by a decision-relevant information key."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:information_partition_observation,
      attributes: [
        partition_id: :string,
        state_vector_id: :string,
        partition_key: :string,
        information_digest: :string
      ]
    )

    activity(:information_partition_observation_created,
      on: :create,
      object_type: :information_partition_observation
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:partition_id, :string, public?: true, allow_nil?: false)
    attribute(:state_vector_id, :string, public?: true, allow_nil?: false)
    attribute(:partition_key, :string, public?: true, allow_nil?: false)
    attribute(:information_digest, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
