# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.LeaseExpiryReplan do
  @moduledoc "Invalidates stale leased plans and returns work to the lawful option frontier."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:lease_expiry_replan,
      attributes: [
        replan_id: :string,
        expired_lease_id: :string,
        returned_frontier_digest: :string
      ]
    )

    activity(:lease_expiry_replan_created, on: :create, object_type: :lease_expiry_replan)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:replan_id, :string, public?: true, allow_nil?: false)
    attribute(:expired_lease_id, :string, public?: true, allow_nil?: false)
    attribute(:returned_frontier_digest, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
