# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.MasterServiceAgreementBinding do
  @moduledoc "Exact MSA binding for an order."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :master_service_agreement_binding_id, :string, public?: true, allow_nil?: false
    attribute :account_id, :string, public?: true, allow_nil?: false
    attribute :msa_digest, :string, public?: true, allow_nil?: false
    attribute :evidence_digest, :string, public?: true, allow_nil?: false
    attribute :effective_at, :utc_datetime, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

