# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.MinimumCommitmentSchedule do
  @moduledoc "Time-phased minimum-spend commitment."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :minimum_commitment_schedule_id, :string, public?: true, allow_nil?: false
    attribute :account_id, :string, public?: true, allow_nil?: false
    attribute :committed_amount, :float, public?: true, allow_nil?: false
    attribute :evidence_digest, :string, public?: true, allow_nil?: false
    attribute :effective_at, :utc_datetime_usec, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

