# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.MutualInformationScore do
  @moduledoc "Ranks observations by expected mutual information with decision-relevant state."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:mutual_information_score,
      attributes: [observation_id: :string, target_state_id: :string, score: :string]
    )

    activity(:mutual_information_score_created,
      on: :create,
      object_type: :mutual_information_score
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:observation_id, :string, public?: true, allow_nil?: false)
    attribute(:target_state_id, :string, public?: true, allow_nil?: false)
    attribute(:score, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
