# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.OcelEvent do
  @moduledoc "An OCEL 2.0 event: one recorded occurrence in an object-centric log."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :event_id, :string, public?: true, allow_nil?: false
    attribute :event_type, :string, public?: true, allow_nil?: false
    attribute :event_time, :utc_datetime, public?: true, allow_nil?: false
    attribute :attributes, :map, public?: true
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

