# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.PlanningBlackboardFact do
  @moduledoc "Publishes a provenance-bound planning fact to the distributed blackboard."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:planning_blackboard_fact,
      attributes: [fact_id: :string, subject_sha: :string, provenance_digest: :string]
    )

    activity(:planning_blackboard_fact_created,
      on: :create,
      object_type: :planning_blackboard_fact
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:fact_id, :string, public?: true, allow_nil?: false)
    attribute(:subject_sha, :string, public?: true, allow_nil?: false)
    attribute(:provenance_digest, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
