# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.PolicyDecision do
  @moduledoc "One admission/authority policy decision recorded for an attempted action."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :decision_id, :string, public?: true, allow_nil?: false
    attribute :verdict, :atom, public?: true, allow_nil?: false
    attribute :reason, :string, public?: true
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

