# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.PolicyGraphNode do
  @moduledoc "Defines one exact state node in an executable policy graph."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:policy_graph_node,
      attributes: [node_id: :string, state_digest: :string, selected_action_id: :string]
    )

    activity(:policy_graph_node_created, on: :create, object_type: :policy_graph_node)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:node_id, :string, public?: true, allow_nil?: false)
    attribute(:state_digest, :string, public?: true, allow_nil?: false)
    attribute(:selected_action_id, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
