# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.PremiumConnectorPricing do
  @moduledoc "Paid integration-connector add-on."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:premium_connector_pricing,
      attributes: [
        premium_connector_pricing_id: :string,
        account_id: :string,
        connector_id: :string,
        evidence_digest: :string,
        effective_at: :datetime
      ]
    )

    activity(:premium_connector_pricing_created,
      on: :create,
      object_type: :premium_connector_pricing
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:premium_connector_pricing_id, :string, public?: true, allow_nil?: false)
    attribute(:account_id, :string, public?: true, allow_nil?: false)
    attribute(:connector_id, :string, public?: true, allow_nil?: false)
    attribute(:evidence_digest, :string, public?: true, allow_nil?: false)
    attribute(:effective_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
