# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.PurchaseOrderRequirement do
  @moduledoc "Makes the buyer's purchase-order requirement explicit and evidenced before booking readiness."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:purchase_order_requirement,
      attributes: [opportunity_id: :string, requirement_id: :string, evidence_hash: :string]
    )

    activity(:purchase_order_requirement_created,
      on: :create,
      object_type: :purchase_order_requirement
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:opportunity_id, :string, public?: true, allow_nil?: false)
    attribute(:requirement_id, :string, public?: true, allow_nil?: false)
    attribute(:evidence_hash, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
