# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.QueueSnapshot do
  @moduledoc "One point-in-time observation of a queue depth."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :queue_name, :string, public?: true, allow_nil?: false
    attribute :depth, :integer, public?: true, allow_nil?: false
    attribute :observed_at, :utc_datetime, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

