# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.RateDistortionBudget do
  @moduledoc "Bounds observation compression by maximum decision-relevant information distortion."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:rate_distortion_budget,
      attributes: [
        budget_id: :string,
        decision_id: :string,
        source_information_bits: :float,
        retained_information_bits: :float,
        maximum_distortion: :float
      ]
    )

    activity(:rate_distortion_budget_created, on: :create, object_type: :rate_distortion_budget)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:budget_id, :string, public?: true, allow_nil?: false)
    attribute(:decision_id, :string, public?: true, allow_nil?: false)
    attribute(:source_information_bits, :float, public?: true, allow_nil?: false)
    attribute(:retained_information_bits, :float, public?: true, allow_nil?: false)
    attribute(:maximum_distortion, :float, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
