# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.RefundPolicy do
  @moduledoc "Deterministic refund eligibility policy."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:refund_policy,
      attributes: [
        refund_policy_id: :string,
        account_id: :string,
        refund_method: :string,
        evidence_digest: :string,
        effective_at: :datetime
      ]
    )

    activity(:refund_policy_created, on: :create, object_type: :refund_policy)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:refund_policy_id, :string, public?: true, allow_nil?: false)
    attribute(:account_id, :string, public?: true, allow_nil?: false)
    attribute(:refund_method, :string, public?: true, allow_nil?: false)
    attribute(:evidence_digest, :string, public?: true, allow_nil?: false)
    attribute(:effective_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
