# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.RegressionDetector do
  @moduledoc "Detects candidate regression against a fixed baseline and metric before promotion."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :detection_id, :string, public?: true, allow_nil?: false
    attribute :baseline_policy_id, :string, public?: true, allow_nil?: false
    attribute :candidate_policy_id, :string, public?: true, allow_nil?: false
    attribute :metric_id, :string, public?: true, allow_nil?: false
    attribute :regression_delta, :float, public?: true, allow_nil?: false
    attribute :evidence_digest, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

