# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.RenewalTermAdmission do
  @moduledoc "Makes renewal duration and its decision explicit for lifetime-value qualification."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:renewal_term_admission,
      attributes: [opportunity_id: :string, renewal_term: :string, decision: :string]
    )

    activity(:renewal_term_admission_created, on: :create, object_type: :renewal_term_admission)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:opportunity_id, :string, public?: true, allow_nil?: false)
    attribute(:renewal_term, :string, public?: true, allow_nil?: false)
    attribute(:decision, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
