# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.SbomInventoryEvidence do
  @moduledoc "Executable SBOM evidence binding an exact commercial subject to the observed component inventory cardinality."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:sbom_inventory_evidence,
      attributes: [
        evidence_id: :string,
        subject_sha: :string,
        component_count: :integer,
        observed_result: :atom
      ]
    )

    activity(:sbom_inventory_evidence_created, on: :create, object_type: :sbom_inventory_evidence)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:evidence_id, :string, public?: true, allow_nil?: false)
    attribute(:subject_sha, :string, public?: true, allow_nil?: false)
    attribute(:component_count, :integer, public?: true, allow_nil?: false)
    attribute(:observed_result, :atom, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
