# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.SemanticDriftObservation do
  @moduledoc "Classifies semantic change between prior and current canonical digests."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :subject_id, :string, public?: true, allow_nil?: false
    attribute :prior_semantic_digest, :string, public?: true, allow_nil?: false
    attribute :current_semantic_digest, :string, public?: true, allow_nil?: false
    attribute :drift_class, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

