# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.ServiceLevelObjective do
  @moduledoc "Measurable service target bound to a support contract."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :slo_id, :string, public?: true, allow_nil?: false
    attribute :contract_id, :string, public?: true, allow_nil?: false
    attribute :target_percent, :float, public?: true, allow_nil?: false
    attribute :measurement_window, :atom, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

