# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.ServiceHealthSnapshot do
  @moduledoc "Captures machine-readable paid-service health for support and escalation decisions."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :tenant_id, :string, public?: true, allow_nil?: false
    attribute :service_id, :string, public?: true, allow_nil?: false
    attribute :snapshot_hash, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

