# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.StrongPlanCandidate do
  @moduledoc "Records a policy candidate that reaches the goal under every admitted outcome."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:strong_plan_candidate,
      attributes: [candidate_id: :string, policy_digest: :string, coverage_proof: :string]
    )

    activity(:strong_plan_candidate_created, on: :create, object_type: :strong_plan_candidate)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:candidate_id, :string, public?: true, allow_nil?: false)
    attribute(:policy_digest, :string, public?: true, allow_nil?: false)
    attribute(:coverage_proof, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
