# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.SubmoduleLockObservation do
  @moduledoc "Compares an exact gitlink with its declared dependency lock to expose submodule drift automatically."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:submodule_lock_observation,
      attributes: [
        submodule_path: :string,
        gitlink_sha: :string,
        lock_sha: :string,
        observed_at: :datetime
      ]
    )

    activity(:submodule_lock_observation_created,
      on: :create,
      object_type: :submodule_lock_observation
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:submodule_path, :string, public?: true, allow_nil?: false)
    attribute(:gitlink_sha, :string, public?: true, allow_nil?: false)
    attribute(:lock_sha, :string, public?: true, allow_nil?: false)
    attribute(:observed_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
