# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.SupportWindowEvidence do
  @moduledoc "Executable support-window evidence binding an exact subject to the channel available during the observed coverage window."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :evidence_id, :string, public?: true, allow_nil?: false
    attribute :subject_sha, :string, public?: true, allow_nil?: false
    attribute :support_channel, :string, public?: true, allow_nil?: false
    attribute :observed_result, :atom, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

