# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.TaxJurisdictionEvidence do
  @moduledoc "Binds the contracting entity to an evidenced tax jurisdiction before price and invoice admission."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :contracting_entity_id, :string, public?: true, allow_nil?: false
    attribute :tax_jurisdiction, :string, public?: true, allow_nil?: false
    attribute :evidence_hash, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

