# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.TenantKeyScope do
  @moduledoc "Binds tenant cryptographic material to one runtime key scope and attested key identity."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :tenant_id, :string, public?: true, allow_nil?: false
    attribute :key_scope_id, :string, public?: true, allow_nil?: false
    attribute :key_attestation_hash, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

