# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.TrainingReadiness do
  @moduledoc "Observed workforce training readiness for production adoption."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:training_readiness,
      attributes: [
        training_readiness_id: :string,
        account_id: :string,
        training_completion_rate: :float,
        evidence_digest: :string,
        observed_at: :datetime
      ]
    )

    activity(:training_readiness_created, on: :create, object_type: :training_readiness)
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:training_readiness_id, :string, public?: true, allow_nil?: false)
    attribute(:account_id, :string, public?: true, allow_nil?: false)
    attribute(:training_completion_rate, :float, public?: true, allow_nil?: false)
    attribute(:evidence_digest, :string, public?: true, allow_nil?: false)
    attribute(:observed_at, :utc_datetime_usec, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
