# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.ValidationCapsuleIdentityObservation do
  @moduledoc "Binds source capsule, validation pack, execution mode, toolchain, and immutable image."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :capsule_repository, :string, public?: true, allow_nil?: false
    attribute :capsule_sha, :string, public?: true, allow_nil?: false
    attribute :execution_mode, :string, public?: true, allow_nil?: false
    attribute :image_digest, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

