# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.WipLimitGate do
  @moduledoc "Refuses selections that would exceed the admitted work-in-process ceiling."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :episode_id, :string, public?: true, allow_nil?: false
    attribute :wip_limit, :string, public?: true, allow_nil?: false
    attribute :standing, :string, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

