# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.WorkloadExecutionIdentity do
  @moduledoc "Assigns every paid workload execution an immutable subject identity before runtime consequence."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false,
    extensions: [AshEx4pm]

  ex4pm do
    object_type(:workload_execution_identity,
      attributes: [tenant_id: :string, execution_id: :string, subject_digest: :string]
    )

    activity(:workload_execution_identity_created,
      on: :create,
      object_type: :workload_execution_identity
    )
  end

  attributes do
    uuid_primary_key(:id)
    attribute(:tenant_id, :string, public?: true, allow_nil?: false)
    attribute(:execution_id, :string, public?: true, allow_nil?: false)
    attribute(:subject_digest, :string, public?: true, allow_nil?: false)
  end

  actions do
    default_accept(:*)
    defaults([:create, :read])
  end
end
