# GENERATED by ggen_igniter from the admitted bpm:RecordType graph. Do not edit.

defmodule BeamPM.Ash.Resources.WorkflowDefinitionDigestObservation do
  @moduledoc "Binds a workflow definition to exact bytes and repository subject before trusting its runs."
  use Ash.Resource,
    domain: BeamPM.Ash.Domain,
    data_layer: Ash.DataLayer.Ets,
    validate_domain_inclusion?: false

  attributes do
    uuid_primary_key :id
    attribute :workflow_path, :string, public?: true, allow_nil?: false
    attribute :definition_sha256, :string, public?: true, allow_nil?: false
    attribute :source_sha, :string, public?: true, allow_nil?: false
    attribute :observed_at, :utc_datetime, public?: true, allow_nil?: false
  end

  actions do
    default_accept :*
    defaults [:create, :read]
  end
end

