#!/usr/bin/env bash
# GATE M2 — deterministic reprojection.
#
# Proves ggen is a pure function of (ontology.ttl, pack templates), with no
# dependency on what was already sitting on disk. Manufactured provenance is
# signalled per-FILE by the "GENERATED by ggen ... Do not edit." header
# comment (first non-shebang line), never by directory placement -- ggen
# output lives in the same src/, lib/, test/, gleam/, schema/,
# docs/reference/ directories hand-authored code uses. This script finds
# every manufactured file by that marker, deletes exactly those files (never
# a whole directory -- src/beam4pm.app.src and every other hand-authored
# file survives untouched), regenerates, and diffs.
set -euo pipefail
cd "$(dirname "$0")/.."

MARKER="GENERATED by ggen"
SEARCH_DIRS=(src lib test gleam/src gleam/test schema docs/reference)
# Deliberately NOT bare "gleam" -- gleam/src and gleam/test (now recursive,
# see find_manufactured below) already cover every real manufactured
# gleam file; a bare "gleam" entry would also recursively sweep
# gleam/build/ (255 real compiled artifacts as of 2026-08-30), which is
# never manufactured source and must never be deleted by this gate.

find_manufactured() {
  # Recursive (no -maxdepth): a real bug caught by this exact gate --
  # gleam/src/beam4pm/discovery.gleam and .../types.gleam live one level
  # NESTED under gleam/src/ (gleam's own package-name subdirectory
  # convention), so an earlier -maxdepth 1 scan of "gleam/src" silently
  # never found them, leaving them un-deleted-and-regenerated across every
  # prior GATE M2 cycle and producing real FM-WRITE-005 refusals the
  # moment their content genuinely needed to change (e.g. the admitted
  # bpm:RecordType graph growing from 31 to 35 record types). head -3:
  # marker is always within the first couple of lines (gleam.toml has no
  # comment syntax collision concern; its own header is a TOML comment).
  for d in "${SEARCH_DIRS[@]}"; do
    [ -d "$d" ] || continue
    find "$d" -type f 2>/dev/null
  done | sort -u | while read -r f; do
    # -i: case-insensitive. Another real, disclosed gap this gate found:
    # docs/reference/beam4pm_types_reference.md's own manufactured header
    # reads "*Generated by ggen ..." (lowercase g) rather than the erl/ex/
    # gleam convention's "GENERATED by ggen" -- an exact-case match missed
    # this one real file for this gate's entire prior existence.
    head -3 "$f" 2>/dev/null | grep -qi "$MARKER" && echo "$f"
  done
}

echo "== pass 1: locating manufactured files by header marker =="
mapfile -t before_files < <(find_manufactured)
echo "found ${#before_files[@]} manufactured files"

echo "== pass 2: sha256 before deletion =="
before_sums="$(for f in "${before_files[@]}"; do shasum -a 256 "$f"; done | sort)"

# Hand-authored test files (no GENERATED marker -- gate_m2_check.sh never
# deletes them) that nonetheless reference a manufactured module at compile
# time (e.g. test/beam4pm_actuation_k8s_test.exs's `alias BeamPM.Actuation`
# + direct BeamPM.Actuation.run/2 calls). Real bug caught by this gate: the
# FIRST sync script (igniter_sync.sh, rendering beam4pm_ash.ex) triggers a
# whole-project `mix compile`/`mix test` as its own internal verification,
# at a point where pass 3 has already deleted beam4pm_actuation.ex (marked)
# but not yet regenerated it (that happens later, inside
# receipt_chain_sync.sh) -- this file, unmarked and therefore never
# deleted, still gets compiled during that window and fails on an
# undefined BeamPM.Actuation. Stash it out of test/ for the regeneration
# window, restore it once every manufactured module it depends on is real
# again, right before the final byte-identity check.
#
# test/beam4pm_process_governor_k8s_test.exs (added with the continuous-
# session k8s feature) hits the identical real bug: it references
# BeamPM.ProcessGovernor.run/2 and the new BeamPM.Actuation.Session module,
# both regenerated only partway through receipt_chain_sync.sh's own
# internal actuation_sync.sh -> process_governor_sync.sh sequence. Caught
# for real the same way as the file above: left unstashed, GATE M2 reported
# 2 UndefinedFunctionError failures ("module BeamPM.ProcessGovernor is not
# available") from a `mix test` run inside that regeneration window, not a
# real regression in either module.
STASH_DIR="$(mktemp -d)"
HAND_AUTHORED_DEPENDENT_TESTS=(test/beam4pm_actuation_k8s_test.exs test/beam4pm_process_governor_k8s_test.exs)
restore_stash() {
  for f in "${HAND_AUTHORED_DEPENDENT_TESTS[@]}"; do
    stashed="$STASH_DIR/$(basename "$f")"
    [ -f "$stashed" ] && mv "$stashed" "$f"
  done
  rmdir "$STASH_DIR" 2>/dev/null || true
}

# BACKUP_DIR holds a real copy of every manufactured file (before_files),
# PLUS ggen.lock (deleted unconditionally by pass 3 below but not itself
# marker-tagged, so it is not part of before_files), taken BEFORE deletion
# -- so a delete-then-regenerate that fails partway through (either engine)
# can be rolled back to a byte-identical working tree instead of leaving
# files deleted-and-never-regenerated. This is the real root-cause fix for
# the GATE M2 destructive-deletion defect: the ggen_igniter leg
# (scripts/igniter_sync.sh) writes lib/beam4pm_ash.ex via
# `mix ggen_igniter.sync --out lib/beam4pm_ash.ex`, then immediately runs
# `mix compile --warnings-as-errors` / `mix test` as its OWN internal
# verification step. If `mix ggen_igniter.sync` itself fails (oxigraph
# Rustler NIF build failure, a bad ontology/query/template combination, a
# transient toolchain/docker issue on the primary ggen leg) the affected
# file is never (re)written -- but pass 3 above had already deleted the
# pre-existing copy. Under `set -e` that failure propagates straight to
# this script's exit with 320+ manufactured files (lib/beam4pm_ash.ex among
# them) missing from the working tree and no automatic recovery.
# BACKUP_DIR + restore_manufactured below close that gap: ANY non-zero exit
# restores every before_files entry (and ggen.lock) from BACKUP_DIR,
# verified by `git status --short` being identical before/after a FAILING
# run, not just a successful one.
BACKUP_DIR="$(mktemp -d)"
for f in "${before_files[@]}"; do
  mkdir -p "$BACKUP_DIR/$(dirname "$f")"
  cp -p "$f" "$BACKUP_DIR/$f"
done
[ -f ggen.lock ] && cp -p ggen.lock "$BACKUP_DIR/ggen.lock"

restore_manufactured() {
  # Only fires on a non-zero exit (see the trap below) -- a successful run
  # regenerates every before_files entry for real via the sync scripts and
  # pass 4 proves byte-identity, so restoring from backup on success would
  # just silently discard the sync scripts' real regenerated output.
  echo "GATE M2: regenerate step failed -- restoring ${#before_files[@]} manufactured files (+ggen.lock) from pre-delete backup" >&2
  for f in "${before_files[@]}"; do
    mkdir -p "$(dirname "$f")"
    cp -p "$BACKUP_DIR/$f" "$f"
  done
  [ -f "$BACKUP_DIR/ggen.lock" ] && cp -p "$BACKUP_DIR/ggen.lock" ggen.lock
}

on_exit() {
  status=$?
  if [ "$status" -ne 0 ]; then
    restore_manufactured
  fi
  restore_stash
  rm -rf "$BACKUP_DIR"
  exit "$status"
}
# Restore on ANY exit, not just the happy path -- an earlier round of
# debugging this exact script left manufactured files deleted-and-never-
# regenerated when a sync script aborted mid-sequence; a bare stash without
# this trap would reproduce the same class of self-inflicted damage here.
trap on_exit EXIT
for f in "${HAND_AUTHORED_DEPENDENT_TESTS[@]}"; do
  [ -f "$f" ] && mv "$f" "$STASH_DIR/$(basename "$f")"
done

echo "== pass 3: delete manufactured files, regenerate (both engines) =="
for f in "${before_files[@]}"; do rm -f "$f"; done
rm -f ggen.lock
ggen sync run
# lib/beam4pm_ash.ex, lib/beam4pm_actuation.ex, lib/beam4pm_process_governor.ex,
# lib/beam4pm_receipt_chain.ex, and their tests are manufactured by the
# SECOND engine (ggen_igniter, mix ggen_igniter.sync), not by the Rust ggen
# binary -- regenerate those too. receipt_chain_sync.sh renders
# beam4pm_receipt_chain.ex FIRST (a real compile-time dependency of
# beam4pm_actuation.ex and beam4pm_process_governor.ex), then internally
# re-runs actuation_sync.sh + process_governor_sync.sh itself -- do not
# also call those two directly here, or the second invocation's own
# `mix compile --warnings-as-errors` would race a not-yet-regenerated
# ReceiptChain (this exact ordering bug was caught for real by this gate).
bash scripts/igniter_sync.sh
bash scripts/receipt_chain_sync.sh

# RF1/RF2/RF3 (rust4pm function-surface Reactor validation) are mutually
# independent of the Ash/actuation/governor/receipt-chain modules above and
# of each other -- no compile-order constraint between them. RF2/RF3's own
# mix test verification (run internally by mix ggen_igniter.sync) needs the
# real oracle-binary/fixture env vars sourced first.
source scripts/env/rust4pm_reactor_env.sh
bash scripts/rf1_dfg_sync.sh
bash scripts/rf2_conformance_sync.sh
bash scripts/rf3_ocel_sync.sh

# Revenue suite + Claude-workflow-Reactor families (igniter-rendered like
# the rf families; mutually independent of them and of each other).
bash scripts/revenue_economics_sync.sh
bash scripts/revenue_metering_sync.sh
bash scripts/claude_workflow_reactor_sync.sh

# beam4pm_pro P0 gap-closure capabilities (PRO-001/003/007/008/010/011/012),
# igniter-rendered, fully static, mutually independent of each other and of
# every family above. PRO-011/012 (ocpm_discovery, simulation) were added
# 2026-08-31 from the deep-research synthesis on beam4pm_pro capabilities
# (OCPM flagship differentiator + what-if simulation, both verified real
# commercial-tier gaps).
bash scripts/pro_capability_manifest_sync.sh
bash scripts/pro_compatibility_sync.sh
bash scripts/pro_license_sync.sh
bash scripts/pro_doctor_sync.sh
bash scripts/pro_tenancy_sync.sh
bash scripts/pro_ocpm_discovery_sync.sh
bash scripts/pro_simulation_sync.sh

# Transplants from ex4pm/xaas: per-record-type doc fan-out (--for-each,
# xaas precedent). AshAi tools and the anti-overclaiming lint gate live in
# hand-authorable surfaces (mix.exs, scripts/, .github/) with no
# manufactured-file component, so they need no sync-script entry here.
bash scripts/pro_type_pages_sync.sh

# Restore the stashed hand-authored tests now that every manufactured
# module they depend on is real again (also happens automatically via the
# EXIT trap on any earlier failure -- calling it explicitly here too just
# means it runs before pass 4 rather than after this script exits).
restore_stash
# Every sync script above completed with exit 0 -- the working tree now
# holds real regenerated output, not a partial delete. Disarm the failure
# trap (from this point on, a pass-4 hash mismatch is a real determinism
# bug to report, never a destructive-deletion event to roll back) and drop
# the now-unneeded pre-delete backup.
trap - EXIT
rm -rf "$BACKUP_DIR"

echo "== pass 4: sha256 after regeneration =="
mapfile -t after_files < <(find_manufactured)
after_sums="$(for f in "${after_files[@]}"; do shasum -a 256 "$f"; done | sort)"

if [ "$before_sums" != "$after_sums" ]; then
  echo "GATE M2: FAIL -- regenerated output differs from the deleted originals" >&2
  diff <(echo "$before_sums") <(echo "$after_sums") >&2 || true
  exit 1
fi

echo "GATE M2: PASS -- ${#after_files[@]} manufactured files byte-identical across delete+regenerate"
