#!/usr/bin/env bash
# GATE M2 — deterministic reprojection.
#
# Proves ggen is a pure function of (ontology.ttl, pack templates), with no
# dependency on what was already sitting on disk. Manufactured provenance is
# signalled per-FILE by the "GENERATED by ggen ... Do not edit." header
# comment (first non-shebang line), never by directory placement -- ggen
# output lives in the same src/, lib/, test/, gleam/, schema/,
# docs/reference/ directories hand-authored code uses. This script finds
# every manufactured file by that marker, deletes exactly those files (never
# a whole directory -- src/beam4pm.app.src and every other hand-authored
# file survives untouched), regenerates, and diffs.
set -euo pipefail
cd "$(dirname "$0")/.."

MARKER="GENERATED by ggen"
SEARCH_DIRS=(src lib test gleam/src gleam/test schema docs/reference)
# Deliberately NOT bare "gleam" -- gleam/src and gleam/test (now recursive,
# see find_manufactured below) already cover every real manufactured
# gleam file; a bare "gleam" entry would also recursively sweep
# gleam/build/ (255 real compiled artifacts as of 2026-08-30), which is
# never manufactured source and must never be deleted by this gate.

find_manufactured() {
  # Recursive (no -maxdepth): a real bug caught by this exact gate --
  # gleam/src/beam4pm/discovery.gleam and .../types.gleam live one level
  # NESTED under gleam/src/ (gleam's own package-name subdirectory
  # convention), so an earlier -maxdepth 1 scan of "gleam/src" silently
  # never found them, leaving them un-deleted-and-regenerated across every
  # prior GATE M2 cycle and producing real FM-WRITE-005 refusals the
  # moment their content genuinely needed to change (e.g. the admitted
  # bpm:RecordType graph growing from 31 to 35 record types). head -3:
  # marker is always within the first couple of lines (gleam.toml has no
  # comment syntax collision concern; its own header is a TOML comment).
  for d in "${SEARCH_DIRS[@]}"; do
    [ -d "$d" ] || continue
    find "$d" -type f 2>/dev/null
  done | sort -u | while read -r f; do
    # -i: case-insensitive. Another real, disclosed gap this gate found:
    # docs/reference/beam4pm_types_reference.md's own manufactured header
    # reads "*Generated by ggen ..." (lowercase g) rather than the erl/ex/
    # gleam convention's "GENERATED by ggen" -- an exact-case match missed
    # this one real file for this gate's entire prior existence.
    head -3 "$f" 2>/dev/null | grep -qi "$MARKER" && echo "$f"
  done
}

echo "== pass 1: locating manufactured files by header marker =="
mapfile -t before_files < <(find_manufactured)
echo "found ${#before_files[@]} manufactured files"

echo "== pass 2: sha256 before deletion =="
before_sums="$(for f in "${before_files[@]}"; do shasum -a 256 "$f"; done | sort)"

# Hand-authored test files (no GENERATED marker -- gate_m2_check.sh never
# deletes them) that nonetheless reference a manufactured module at compile
# time (e.g. test/beam4pm_actuation_k8s_test.exs's `alias BeamPM.Actuation`
# + direct BeamPM.Actuation.run/2 calls). Real bug caught by this gate: the
# FIRST sync script (igniter_sync.sh, rendering beam4pm_ash.ex) triggers a
# whole-project `mix compile`/`mix test` as its own internal verification,
# at a point where pass 3 has already deleted beam4pm_actuation.ex (marked)
# but not yet regenerated it (that happens later, inside
# receipt_chain_sync.sh) -- this file, unmarked and therefore never
# deleted, still gets compiled during that window and fails on an
# undefined BeamPM.Actuation. Stash it out of test/ for the regeneration
# window, restore it once every manufactured module it depends on is real
# again, right before the final byte-identity check.
#
# test/beam4pm_process_governor_k8s_test.exs (added with the continuous-
# session k8s feature) hits the identical real bug: it references
# BeamPM.ProcessGovernor.run/2 and the new BeamPM.Actuation.Session module,
# both regenerated only partway through receipt_chain_sync.sh's own
# internal actuation_sync.sh -> process_governor_sync.sh sequence. Caught
# for real the same way as the file above: left unstashed, GATE M2 reported
# 2 UndefinedFunctionError failures ("module BeamPM.ProcessGovernor is not
# available") from a `mix test` run inside that regeneration window, not a
# real regression in either module.
STASH_DIR="$(mktemp -d)"
HAND_AUTHORED_DEPENDENT_TESTS=(test/beam4pm_actuation_k8s_test.exs test/beam4pm_process_governor_k8s_test.exs)
restore_stash() {
  for f in "${HAND_AUTHORED_DEPENDENT_TESTS[@]}"; do
    stashed="$STASH_DIR/$(basename "$f")"
    [ -f "$stashed" ] && mv "$stashed" "$f"
  done
  rmdir "$STASH_DIR" 2>/dev/null || true
}
# Restore on ANY exit, not just the happy path -- an earlier round of
# debugging this exact script left manufactured files deleted-and-never-
# regenerated when a sync script aborted mid-sequence; a bare stash without
# this trap would reproduce the same class of self-inflicted damage here.
trap restore_stash EXIT
for f in "${HAND_AUTHORED_DEPENDENT_TESTS[@]}"; do
  [ -f "$f" ] && mv "$f" "$STASH_DIR/$(basename "$f")"
done

echo "== pass 3: delete manufactured files, regenerate (both engines) =="
for f in "${before_files[@]}"; do rm -f "$f"; done
rm -f ggen.lock
GGEN_BIN="${GGEN_BIN:-ggen}"
"$GGEN_BIN" sync run
# lib/beam4pm_ash.ex, lib/beam4pm_actuation.ex, lib/beam4pm_process_governor.ex,
# lib/beam4pm_receipt_chain.ex, and their tests are manufactured by the
# SECOND engine (ggen_igniter, mix ggen_igniter.sync), not by the Rust ggen
# binary -- regenerate those too. receipt_chain_sync.sh renders
# beam4pm_receipt_chain.ex FIRST (a real compile-time dependency of
# beam4pm_actuation.ex and beam4pm_process_governor.ex), then internally
# re-runs actuation_sync.sh + process_governor_sync.sh itself -- do not
# also call those two directly here, or the second invocation's own
# `mix compile --warnings-as-errors` would race a not-yet-regenerated
# ReceiptChain (this exact ordering bug was caught for real by this gate).
bash scripts/igniter_sync.sh
bash scripts/receipt_chain_sync.sh

# RF1/RF2/RF3 (rust4pm function-surface Reactor validation) are mutually
# independent of the Ash/actuation/governor/receipt-chain modules above and
# of each other -- no compile-order constraint between them. RF2/RF3's own
# mix test verification (run internally by mix ggen_igniter.sync) needs the
# real oracle-binary/fixture env vars sourced first.
source scripts/env/rust4pm_reactor_env.sh
bash scripts/rf1_dfg_sync.sh
bash scripts/rf2_conformance_sync.sh
bash scripts/rf3_ocel_sync.sh

# Restore the stashed hand-authored tests now that every manufactured
# module they depend on is real again (also happens automatically via the
# EXIT trap on any earlier failure -- calling it explicitly here too just
# means it runs before pass 4 rather than after this script exits).
restore_stash
trap - EXIT

echo "== pass 4: sha256 after regeneration =="
mapfile -t after_files < <(find_manufactured)
after_sums="$(for f in "${after_files[@]}"; do shasum -a 256 "$f"; done | sort)"

if [ "$before_sums" != "$after_sums" ]; then
  echo "GATE M2: FAIL -- regenerated output differs from the deleted originals" >&2
  diff <(echo "$before_sums") <(echo "$after_sums") >&2 || true
  exit 1
fi

echo "GATE M2: PASS -- ${#after_files[@]} manufactured files byte-identical across delete+regenerate"
