#!/usr/bin/env python3
"""WS2 manufacture court (hand-authored; not a ggen projection).

Admission court for the WS2 autonomic-planning selection contracts and for
the ggen receipt that manufactures them. Authority NONE, ceiling SELECT: the
court reads files and prints a verdict; it never writes into the repository.

Subcommands
-----------
semantic       census, identity, namespace, DO-surface, collision and
               pairwise-distance court over ontology/ws2-autonomic-planning
               fragments [first, last]; with --require-projection it also
               demands a word-bounded projection in src/beam4pm_types.erl and
               test/beam4pm_types_test.exs (run after `ggen sync run`).
receipt-first  verifies .ggen-v2/receipt.json against the ownership census
               (primary + secondary target lists) and on-disk digests, and
               writes <evidence>/first-sync-identity.json.
receipt-second verifies the second sync: same graph hash, every first-run
               output byte-identical, writes second-sync-identity.json and
               refuses on any drift.

Every refusal is one stderr line `REFUSED[CODE]:detail` or
`BUILD_BROKEN[CODE]:detail` and exit status 2 (refusal) or 1 (build broken).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# The court runs inside the manufacture workspace, whose consequence is
# `git add -A`; bytecode caches must never enter that patch.
sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))
import blake3_digest  # noqa: E402

# The only bpm namespace the beam4pm-process-model-pack SPARQL selects from.
# A fragment that binds bpm: elsewhere is silently invisible to ggen, which
# is exactly how WS2-PLAN-051..100 failed to project at 23769be5.
PROJECTABLE_BPM = "https://ggen.dev/ontology/beam-process-model#"
FRAGMENT_DIR = Path("ontology/ws2-autonomic-planning")
FIELDS_PER_CONTRACT = 3
ERLANG_RESERVED = frozenset(
    "after and andalso band begin bnot bor bsl bsr bxor case catch cond div "
    "else end fun if let maybe not of or orelse receive rem try when xor".split()
)
IDENT = re.compile(r"^[a-z][a-z0-9_]*$")
DO_SURFACE = re.compile(r'\b(?:execute|actuate)\b|bpm:fieldName "do"', re.I)
MARKER = "generated by ggen"
COMPOSED_MARKER = "# ---- composed canonical fragment:"


class Refusal(Exception):
    def __init__(self, code: str, detail: str = "", kind: str = "REFUSED"):
        super().__init__(f"{kind}[{code}]" + (f":{detail}" if detail else ""))
        self.kind = kind


def _token(name: str) -> re.Pattern[str]:
    return re.compile(r"(?<![A-Za-z0-9_])" + re.escape(name) + r"(?![A-Za-z0-9_])")


def _prefix(text: str, prefix: str) -> list[str]:
    return re.findall(r"@prefix\s+" + re.escape(prefix) + r":\s*<([^>]+)>", text)


def fragment_paths(root: Path, first: int, last: int) -> list[Path]:
    base = root / FRAGMENT_DIR
    return sorted(p for p in base.glob("*.ttl") if p.name[:3].isdigit() and first <= int(p.name[:3]) <= last)


def parse_contract(path: Path) -> tuple[str, frozenset[str]]:
    text = path.read_text()
    bpm = _prefix(text, "bpm")
    if bpm != [PROJECTABLE_BPM]:
        raise Refusal("WS2_NAMESPACE_NOT_PROJECTABLE", f"{path.name}:bpm={bpm}")
    names = re.findall(r'bpm:recordName "([^"]+)"', text)
    if len(names) != 1:
        raise Refusal("WS2_RECORD_IDENTITY", f"{path.name}:{names}")
    name = names[0]
    if not IDENT.match(name) or name in ERLANG_RESERVED:
        raise Refusal("WS2_RECORD_NAME_NOT_ERLANG_ATOM", f"{path.name}:{name}")
    if f"-{name}.ttl" not in path.name:
        raise Refusal("WS2_FILENAME_IDENTITY_MISMATCH", f"{path.name}:{name}")
    if len(re.findall(r"a\s+bpm:RecordType", text)) != 1:
        raise Refusal("WS2_RECORD_TYPE_COUNT", path.name)
    field_names = re.findall(r'bpm:fieldName "([^"]+)"', text)
    required = re.findall(r'bpm:fieldRequired "true"', text)
    orders = sorted(int(o) for o in re.findall(r"bpm:fieldOrder\s+(\d+)", text))
    if (
        len(field_names) != FIELDS_PER_CONTRACT
        or len(required) != FIELDS_PER_CONTRACT
        or orders != list(range(1, FIELDS_PER_CONTRACT + 1))
    ):
        raise Refusal(
            "WS2_REQUIRED_FIELD_COUNT",
            f"{path.name}:fields={len(field_names)}:required={len(required)}:orders={orders}",
        )
    if len(set(field_names)) != len(field_names):
        raise Refusal("WS2_DUPLICATE_FIELD", f"{path.name}:{field_names}")
    for field in field_names:
        if not IDENT.match(field) or field in ERLANG_RESERVED:
            raise Refusal("WS2_FIELD_NAME_NOT_ERLANG_ATOM", f"{path.name}:{field}")
    if DO_SURFACE.search(text):
        raise Refusal("WS2_DO_SURFACE", path.name)
    return name, frozenset(field_names)


def external_record_names(root: Path, owned: set[Path]) -> set[str]:
    names: set[str] = set()
    sources = [root / "ontology.ttl"] + sorted((root / "ontology").rglob("*.ttl"))
    for src in sources:
        if src in owned or not src.is_file():
            continue
        text = src.read_text(errors="ignore")
        # Inside the manufacture job ontology.ttl has already had every
        # fragment appended after this marker; only the canonical root part
        # before it is an independent owner of record names.
        text = text.split(COMPOSED_MARKER, 1)[0]
        names.update(re.findall(r'bpm:recordName "([^"]+)"', text))
    return names


def semantic(root: Path, first: int, last: int, require_projection: bool) -> dict:
    expected = last - first + 1
    paths = fragment_paths(root, first, last)
    if len(paths) != expected:
        raise Refusal("WS2_SEMANTIC_CENSUS", f"expected={expected}:actual={len(paths)}")
    numbers = [int(p.name[:3]) for p in paths]
    if numbers != list(range(first, last + 1)):
        raise Refusal("WS2_SEMANTIC_CENSUS_GAP", f"numbers={numbers}")

    contracts: dict[str, frozenset[str]] = {}
    for path in paths:
        name, fields = parse_contract(path)
        if name in contracts:
            raise Refusal("WS2_RECORD_NAME_COLLISION", name)
        contracts[name] = fields

    external = external_record_names(root, set(paths))
    clash = sorted(set(contracts) & external)
    if clash:
        raise Refusal("WS2_RECORD_NAME_COLLISION_EXTERNAL", ",".join(clash))

    # d_semantic = Jaccard distance over field-name sets (recordName excluded
    # so identity alone cannot satisfy the court); epsilon=0 is the exact
    # semantic-duplicate boundary.
    epsilon = 0.0
    names = sorted(contracts)
    min_distance = 1.0
    min_pair = ("", "")
    for i, left in enumerate(names):
        a = contracts[left]
        for right in names[i + 1 :]:
            b = contracts[right]
            distance = 1.0 - len(a & b) / len(a | b)
            if distance < min_distance:
                min_distance, min_pair = distance, (left, right)
            if not distance > epsilon:
                raise Refusal(
                    "WS2_SEMANTIC_FRAGMENTATION",
                    f"{left}:{right}:distance={distance}:epsilon={epsilon}",
                )

    if require_projection:
        erlang = (root / "src/beam4pm_types.erl").read_text()
        tests = (root / "test/beam4pm_types_test.exs").read_text()
        missing_source = [n for n in names if not re.search(r"-record\(" + re.escape(n) + r",", erlang)]
        missing_tests = [n for n in names if not _token(n).search(tests)]
        if missing_source:
            raise Refusal("WS2_ERLANG_PROJECTION_MISSING", ",".join(missing_source), "BUILD_BROKEN")
        if missing_tests:
            raise Refusal("WS2_TEST_PROJECTION_MISSING", ",".join(missing_tests), "BUILD_BROKEN")

    return {
        "verdict": f"ALIVE[WS2_SEMANTIC_PROJECTION_{expected}]",
        "contracts": expected,
        "projection_checked": require_projection,
        "d_semantic_min": round(min_distance, 6),
        "d_semantic_min_pair": list(min_pair),
        "epsilon": epsilon,
    }


def _targets(evidence: Path) -> tuple[set[str], set[str]]:
    def read(name: str) -> set[str]:
        path = evidence / name
        if not path.is_file():
            return set()
        return {line.strip() for line in path.read_text().splitlines() if line.strip()}

    primary = read("primary-ggen-targets.txt")
    if not primary:
        raise Refusal("EMPTY_PRIMARY_TARGET_CENSUS", str(evidence))
    return primary, read("secondary-ggen-targets.txt")


def _receipt(root: Path, missing_code: str) -> dict:
    path = root / ".ggen-v2/receipt.json"
    if not path.is_file() or path.stat().st_size == 0:
        raise Refusal(missing_code)
    try:
        receipt = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise Refusal("GGEN_RECEIPT_MALFORMED", str(exc)) from exc
    payload = receipt.get("payload") if isinstance(receipt, dict) else None
    if not isinstance(payload, dict):
        raise Refusal("GGEN_RECEIPT_MALFORMED", "payload")
    graph_hash = payload.get("graph_hash")
    if not isinstance(graph_hash, str) or not re.fullmatch(r"[0-9a-f]{64}", graph_hash):
        raise Refusal("GGEN_RECEIPT_GRAPH_HASH_MALFORMED", repr(graph_hash))
    outputs = payload.get("outputs")
    if not isinstance(outputs, dict) or not outputs:
        raise Refusal("EMPTY_GGEN_OUTPUT_RECEIPT")
    for rel, digest in outputs.items():
        if not isinstance(digest, str) or not re.fullmatch(r"[0-9a-f]{64}", digest):
            raise Refusal("GGEN_RECEIPT_DIGEST_MALFORMED", f"{rel}:{digest!r}")
        if rel.startswith("/") or ".." in Path(rel).parts:
            raise Refusal("GGEN_RECEIPT_PATH_ESCAPE", rel)
    return payload


def _digest(path: Path) -> str:
    # ggen receipts bind outputs by BLAKE3, not SHA-256 (see blake3_digest.py).
    return blake3_digest.file_digest(path)


def receipt_first(root: Path, evidence: Path) -> dict:
    payload = _receipt(root, "MISSING_GGEN_RECEIPT")
    primary, secondary = _targets(evidence)
    outputs = payload["outputs"]
    uncensused = sorted(set(outputs) - primary - secondary)
    if uncensused:
        raise Refusal("OUTPUT_OUTSIDE_OWNERSHIP_CENSUS", ",".join(uncensused))
    verified: dict[str, str] = {}
    for rel, expected in sorted(outputs.items()):
        path = root / rel
        if not path.is_file():
            raise Refusal("RECEIPTED_OUTPUT_MISSING", rel)
        actual = _digest(path)
        if actual != expected:
            raise Refusal("RECEIPT_DIGEST_MISMATCH", f"{rel}:{expected}:{actual}")
        if rel in primary:
            header = "\n".join(path.read_text(errors="ignore").splitlines()[:3]).lower()
            if MARKER not in header:
                raise Refusal("OUTPUT_OWNERSHIP_UNMARKED", rel)
        verified[rel] = actual
    state = {"graph_hash": payload["graph_hash"], "outputs": verified}
    (evidence / "first-sync-identity.json").write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")
    return {
        "verdict": "ALIVE[FIRST_SYNC_RECEIPT_OWNERSHIP]",
        "outputs": len(verified),
        "digest": "blake3",
        "digest_backend": blake3_digest.backend(),
    }


def receipt_second(root: Path, evidence: Path) -> dict:
    first_path = evidence / "first-sync-identity.json"
    if not first_path.is_file():
        raise Refusal("FIRST_SYNC_IDENTITY_ABSENT")
    first = json.loads(first_path.read_text())
    payload = _receipt(root, "MISSING_SECOND_GGEN_RECEIPT")
    if payload["graph_hash"] != first.get("graph_hash"):
        raise Refusal(
            "SECOND_SYNC_GRAPH_IDENTITY_MISMATCH", f"{first.get('graph_hash')}:{payload['graph_hash']}"
        )
    primary, secondary = _targets(evidence)
    outputs = payload["outputs"]
    uncensused = sorted(set(outputs) - primary - secondary)
    if uncensused:
        raise Refusal("SECOND_OUTPUT_OUTSIDE_OWNERSHIP_CENSUS", ",".join(uncensused))
    for rel, expected in sorted(outputs.items()):
        path = root / rel
        if not path.is_file():
            raise Refusal("SECOND_RECEIPTED_OUTPUT_MISSING", rel)
        digest = _digest(path)
        if digest != expected:
            raise Refusal("SECOND_RECEIPT_DIGEST_MISMATCH", f"{rel}:{expected}:{digest}")
    # Byte identity over the exact first-run consequence set, independent of
    # whether the second receipt repeats unchanged outputs.
    actual: dict[str, str] = {}
    for rel, expected in sorted(first["outputs"].items()):
        path = root / rel
        if not path.is_file():
            raise Refusal("SECOND_SYNC_OUTPUT_MISSING", rel)
        digest = _digest(path)
        if digest != expected:
            raise Refusal("SECOND_SYNC_BYTE_DRIFT", f"{rel}:{expected}:{digest}")
        actual[rel] = digest
    second = {"graph_hash": payload["graph_hash"], "outputs": actual}
    (evidence / "second-sync-identity.json").write_text(json.dumps(second, indent=2, sort_keys=True) + "\n")
    if second != first:
        raise Refusal("SECOND_SYNC_IDENTITY_MISMATCH")
    return {"verdict": "ALIVE[SECOND_SYNC_BYTE_IDENTITY]", "outputs": len(actual)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    sem = sub.add_parser("semantic")
    sem.add_argument("--root", type=Path, default=Path("."))
    sem.add_argument("--first", type=int, default=51)
    sem.add_argument("--last", type=int, default=100)
    sem.add_argument("--require-projection", action="store_true")
    for name in ("receipt-first", "receipt-second"):
        rec = sub.add_parser(name)
        rec.add_argument("--root", type=Path, default=Path("."))
        rec.add_argument("--evidence", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        if args.cmd == "semantic":
            result = semantic(args.root, args.first, args.last, args.require_projection)
        elif args.cmd == "receipt-first":
            result = receipt_first(args.root, args.evidence)
        else:
            result = receipt_second(args.root, args.evidence)
    except Refusal as refusal:
        print(str(refusal), file=sys.stderr)
        return 1 if refusal.kind == "BUILD_BROKEN" else 2
    print(result["verdict"])
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
