%% GENERATED by ggen from the admitted bpm:RecordType graph. Do not edit.
%%
%% Cross-language roundtrip sample fixtures: one deterministic sample per
%% admitted record type and variant (full | minimal), written and verified
%% through beam4pm_codec so any drift between the Erlang and Elixir codecs
%% surfaces as a real fixture mismatch, not an assumed equivalence.

-module(beam4pm_roundtrip).

-export([record_names/0, sample/2, write_samples/1, verify_samples/2]).

-type variant() :: full | minimal.

-spec record_names() -> [atom()].
record_names() ->
    [
        account_master_match,
        account_parent_scope,
        alignment_move,
        billing_reconciliation,
        case_stats,
        conformance_result,
        dfg_edge,
        entitlement_event,
        entitlement_state,
        event_log,
        event_type,
        heuristic_arc,
        k8s_object_ref,
        log_trace,
        object_attribute_change,
        object_type,
        oc_declare_constraint,
        ocel_attribute,
        ocel_event,
        ocel_object,
        ocel_relationship,
        opportunity_currency_contract,
        opportunity_value_range,
        path_schema,
        path_schema_query,
        petri_arc,
        petri_place,
        petri_transition,
        planning_action,
        planning_state,
        policy_decision,
        process_variant,
        queue_snapshot,
        resource_allocation,
        service_span,
        sojourn_time,
        sync_time,
        type_edge,
        usage_event
    ].

%% Deterministic sample values, keyed by bpm:fieldType:
%% string -> <<"sample_" field_name>>, datetime -> <<"2026-08-29T12:00:00Z">>,
%% integer -> 42, float -> 3.5, boolean -> true, atom -> sample_atom,
%% list_string -> [<<"alpha">>, <<"beta">>], map -> #{<<"k">> => <<"v">>}.
%% minimal = required fields only; full = every field.
-spec sample(atom(), variant()) -> {ok, tuple()}.
sample(account_master_match, full) ->
    beam4pm_types:new_account_master_match(#{
        source_account_id => <<"sample_source_account_id">>,
        canonical_account_id => <<"sample_canonical_account_id">>,
        match_evidence_hash => <<"sample_match_evidence_hash">>
    });
sample(account_master_match, minimal) ->
    beam4pm_types:new_account_master_match(#{
        source_account_id => <<"sample_source_account_id">>,
        canonical_account_id => <<"sample_canonical_account_id">>,
        match_evidence_hash => <<"sample_match_evidence_hash">>
    });
sample(account_parent_scope, full) ->
    beam4pm_types:new_account_parent_scope(#{
        account_id => <<"sample_account_id">>,
        parent_account_id => <<"sample_parent_account_id">>,
        scope_evidence_hash => <<"sample_scope_evidence_hash">>
    });
sample(account_parent_scope, minimal) ->
    beam4pm_types:new_account_parent_scope(#{
        account_id => <<"sample_account_id">>,
        parent_account_id => <<"sample_parent_account_id">>,
        scope_evidence_hash => <<"sample_scope_evidence_hash">>
    });
sample(alignment_move, full) ->
    beam4pm_types:new_alignment_move(#{
        move_type => sample_atom,
        cost => 42
    });
sample(alignment_move, minimal) ->
    beam4pm_types:new_alignment_move(#{
        move_type => sample_atom,
        cost => 42
    });
sample(billing_reconciliation, full) ->
    beam4pm_types:new_billing_reconciliation(#{
        entitlement_id => <<"sample_entitlement_id">>,
        metric_name => <<"sample_metric_name">>,
        total_quantity => 3.5,
        applied_event_ids => [<<"alpha">>, <<"beta">>],
        period_start => <<"2026-08-29T12:00:00Z">>,
        period_end => <<"2026-08-29T12:00:00Z">>
    });
sample(billing_reconciliation, minimal) ->
    beam4pm_types:new_billing_reconciliation(#{
        entitlement_id => <<"sample_entitlement_id">>,
        metric_name => <<"sample_metric_name">>,
        total_quantity => 3.5,
        applied_event_ids => [<<"alpha">>, <<"beta">>],
        period_start => <<"2026-08-29T12:00:00Z">>,
        period_end => <<"2026-08-29T12:00:00Z">>
    });
sample(case_stats, full) ->
    beam4pm_types:new_case_stats(#{
        case_id => <<"sample_case_id">>,
        event_count => 42,
        duration_seconds => 3.5
    });
sample(case_stats, minimal) ->
    beam4pm_types:new_case_stats(#{
        case_id => <<"sample_case_id">>,
        event_count => 42
    });
sample(conformance_result, full) ->
    beam4pm_types:new_conformance_result(#{
        trace_id => <<"sample_trace_id">>,
        fitness => 3.5,
        precision => 3.5
    });
sample(conformance_result, minimal) ->
    beam4pm_types:new_conformance_result(#{
        trace_id => <<"sample_trace_id">>,
        fitness => 3.5
    });
sample(dfg_edge, full) ->
    beam4pm_types:new_dfg_edge(#{
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        frequency => 42
    });
sample(dfg_edge, minimal) ->
    beam4pm_types:new_dfg_edge(#{
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        frequency => 42
    });
sample(entitlement_event, full) ->
    beam4pm_types:new_entitlement_event(#{
        event_id => <<"sample_event_id">>,
        entitlement_id => <<"sample_entitlement_id">>,
        event_type => <<"sample_event_type">>,
        effective_at => <<"2026-08-29T12:00:00Z">>,
        payload => #{<<"k">> => <<"v">>}
    });
sample(entitlement_event, minimal) ->
    beam4pm_types:new_entitlement_event(#{
        event_id => <<"sample_event_id">>,
        entitlement_id => <<"sample_entitlement_id">>,
        event_type => <<"sample_event_type">>,
        effective_at => <<"2026-08-29T12:00:00Z">>
    });
sample(entitlement_state, full) ->
    beam4pm_types:new_entitlement_state(#{
        entitlement_id => <<"sample_entitlement_id">>,
        status => <<"sample_status">>,
        last_applied_event_id => <<"sample_last_applied_event_id">>,
        updated_at => <<"2026-08-29T12:00:00Z">>
    });
sample(entitlement_state, minimal) ->
    beam4pm_types:new_entitlement_state(#{
        entitlement_id => <<"sample_entitlement_id">>,
        status => <<"sample_status">>,
        last_applied_event_id => <<"sample_last_applied_event_id">>,
        updated_at => <<"2026-08-29T12:00:00Z">>
    });
sample(event_log, full) ->
    beam4pm_types:new_event_log(#{
        log_id => <<"sample_log_id">>,
        name => <<"sample_name">>,
        description => <<"sample_description">>
    });
sample(event_log, minimal) ->
    beam4pm_types:new_event_log(#{
        log_id => <<"sample_log_id">>,
        name => <<"sample_name">>
    });
sample(event_type, full) ->
    beam4pm_types:new_event_type(#{
        type_name => <<"sample_type_name">>,
        attribute_names => [<<"alpha">>, <<"beta">>]
    });
sample(event_type, minimal) ->
    beam4pm_types:new_event_type(#{
        type_name => <<"sample_type_name">>
    });
sample(heuristic_arc, full) ->
    beam4pm_types:new_heuristic_arc(#{
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        dependency_measure => 3.5
    });
sample(heuristic_arc, minimal) ->
    beam4pm_types:new_heuristic_arc(#{
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        dependency_measure => 3.5
    });
sample(k8s_object_ref, full) ->
    beam4pm_types:new_k8s_object_ref(#{
        kind => <<"sample_kind">>,
        name => <<"sample_name">>,
        namespace => <<"sample_namespace">>
    });
sample(k8s_object_ref, minimal) ->
    beam4pm_types:new_k8s_object_ref(#{
        kind => <<"sample_kind">>,
        name => <<"sample_name">>
    });
sample(log_trace, full) ->
    beam4pm_types:new_log_trace(#{
        case_id => <<"sample_case_id">>,
        activity_sequence => [<<"alpha">>, <<"beta">>]
    });
sample(log_trace, minimal) ->
    beam4pm_types:new_log_trace(#{
        case_id => <<"sample_case_id">>,
        activity_sequence => [<<"alpha">>, <<"beta">>]
    });
sample(object_attribute_change, full) ->
    beam4pm_types:new_object_attribute_change(#{
        object_id => <<"sample_object_id">>,
        attribute_name => <<"sample_attribute_name">>,
        old_value => <<"sample_old_value">>,
        new_value => <<"sample_new_value">>,
        changed_at => <<"2026-08-29T12:00:00Z">>
    });
sample(object_attribute_change, minimal) ->
    beam4pm_types:new_object_attribute_change(#{
        object_id => <<"sample_object_id">>,
        attribute_name => <<"sample_attribute_name">>,
        new_value => <<"sample_new_value">>,
        changed_at => <<"2026-08-29T12:00:00Z">>
    });
sample(object_type, full) ->
    beam4pm_types:new_object_type(#{
        type_name => <<"sample_type_name">>,
        attribute_names => [<<"alpha">>, <<"beta">>]
    });
sample(object_type, minimal) ->
    beam4pm_types:new_object_type(#{
        type_name => <<"sample_type_name">>
    });
sample(oc_declare_constraint, full) ->
    beam4pm_types:new_oc_declare_constraint(#{
        constraint_id => <<"sample_constraint_id">>,
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        constraint_type => sample_atom
    });
sample(oc_declare_constraint, minimal) ->
    beam4pm_types:new_oc_declare_constraint(#{
        constraint_id => <<"sample_constraint_id">>,
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        constraint_type => sample_atom
    });
sample(ocel_attribute, full) ->
    beam4pm_types:new_ocel_attribute(#{
        attribute_name => <<"sample_attribute_name">>,
        attribute_value => <<"sample_attribute_value">>,
        recorded_at => <<"2026-08-29T12:00:00Z">>
    });
sample(ocel_attribute, minimal) ->
    beam4pm_types:new_ocel_attribute(#{
        attribute_name => <<"sample_attribute_name">>,
        attribute_value => <<"sample_attribute_value">>
    });
sample(ocel_event, full) ->
    beam4pm_types:new_ocel_event(#{
        event_id => <<"sample_event_id">>,
        event_type => <<"sample_event_type">>,
        event_time => <<"2026-08-29T12:00:00Z">>,
        attributes => #{<<"k">> => <<"v">>}
    });
sample(ocel_event, minimal) ->
    beam4pm_types:new_ocel_event(#{
        event_id => <<"sample_event_id">>,
        event_type => <<"sample_event_type">>,
        event_time => <<"2026-08-29T12:00:00Z">>
    });
sample(ocel_object, full) ->
    beam4pm_types:new_ocel_object(#{
        object_id => <<"sample_object_id">>,
        object_type => <<"sample_object_type">>,
        attributes => #{<<"k">> => <<"v">>}
    });
sample(ocel_object, minimal) ->
    beam4pm_types:new_ocel_object(#{
        object_id => <<"sample_object_id">>,
        object_type => <<"sample_object_type">>
    });
sample(ocel_relationship, full) ->
    beam4pm_types:new_ocel_relationship(#{
        qualifier => <<"sample_qualifier">>,
        object_id => <<"sample_object_id">>
    });
sample(ocel_relationship, minimal) ->
    beam4pm_types:new_ocel_relationship(#{
        qualifier => <<"sample_qualifier">>,
        object_id => <<"sample_object_id">>
    });
sample(opportunity_currency_contract, full) ->
    beam4pm_types:new_opportunity_currency_contract(#{
        opportunity_id => <<"sample_opportunity_id">>,
        currency_code => <<"sample_currency_code">>,
        fx_basis_id => <<"sample_fx_basis_id">>
    });
sample(opportunity_currency_contract, minimal) ->
    beam4pm_types:new_opportunity_currency_contract(#{
        opportunity_id => <<"sample_opportunity_id">>,
        currency_code => <<"sample_currency_code">>,
        fx_basis_id => <<"sample_fx_basis_id">>
    });
sample(opportunity_value_range, full) ->
    beam4pm_types:new_opportunity_value_range(#{
        opportunity_id => <<"sample_opportunity_id">>,
        minimum_value => <<"sample_minimum_value">>,
        maximum_value => <<"sample_maximum_value">>
    });
sample(opportunity_value_range, minimal) ->
    beam4pm_types:new_opportunity_value_range(#{
        opportunity_id => <<"sample_opportunity_id">>,
        minimum_value => <<"sample_minimum_value">>,
        maximum_value => <<"sample_maximum_value">>
    });
sample(path_schema, full) ->
    beam4pm_types:new_path_schema(#{
        schema_id => <<"sample_schema_id">>,
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        support => 42
    });
sample(path_schema, minimal) ->
    beam4pm_types:new_path_schema(#{
        schema_id => <<"sample_schema_id">>,
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        support => 42
    });
sample(path_schema_query, full) ->
    beam4pm_types:new_path_schema_query(#{
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        max_length => 42
    });
sample(path_schema_query, minimal) ->
    beam4pm_types:new_path_schema_query(#{
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        max_length => 42
    });
sample(petri_arc, full) ->
    beam4pm_types:new_petri_arc(#{
        source_id => <<"sample_source_id">>,
        target_id => <<"sample_target_id">>,
        weight => 42
    });
sample(petri_arc, minimal) ->
    beam4pm_types:new_petri_arc(#{
        source_id => <<"sample_source_id">>,
        target_id => <<"sample_target_id">>,
        weight => 42
    });
sample(petri_place, full) ->
    beam4pm_types:new_petri_place(#{
        place_id => <<"sample_place_id">>,
        tokens => 42
    });
sample(petri_place, minimal) ->
    beam4pm_types:new_petri_place(#{
        place_id => <<"sample_place_id">>,
        tokens => 42
    });
sample(petri_transition, full) ->
    beam4pm_types:new_petri_transition(#{
        transition_id => <<"sample_transition_id">>,
        label => <<"sample_label">>
    });
sample(petri_transition, minimal) ->
    beam4pm_types:new_petri_transition(#{
        transition_id => <<"sample_transition_id">>
    });
sample(planning_action, full) ->
    beam4pm_types:new_planning_action(#{
        action_name => <<"sample_action_name">>,
        preconditions => [<<"alpha">>, <<"beta">>],
        effects => [<<"alpha">>, <<"beta">>]
    });
sample(planning_action, minimal) ->
    beam4pm_types:new_planning_action(#{
        action_name => <<"sample_action_name">>
    });
sample(planning_state, full) ->
    beam4pm_types:new_planning_state(#{
        state_id => <<"sample_state_id">>,
        facts => [<<"alpha">>, <<"beta">>]
    });
sample(planning_state, minimal) ->
    beam4pm_types:new_planning_state(#{
        state_id => <<"sample_state_id">>,
        facts => [<<"alpha">>, <<"beta">>]
    });
sample(policy_decision, full) ->
    beam4pm_types:new_policy_decision(#{
        decision_id => <<"sample_decision_id">>,
        verdict => sample_atom,
        reason => <<"sample_reason">>
    });
sample(policy_decision, minimal) ->
    beam4pm_types:new_policy_decision(#{
        decision_id => <<"sample_decision_id">>,
        verdict => sample_atom
    });
sample(process_variant, full) ->
    beam4pm_types:new_process_variant(#{
        variant_id => <<"sample_variant_id">>,
        activity_sequence => [<<"alpha">>, <<"beta">>],
        frequency => 42
    });
sample(process_variant, minimal) ->
    beam4pm_types:new_process_variant(#{
        variant_id => <<"sample_variant_id">>,
        activity_sequence => [<<"alpha">>, <<"beta">>],
        frequency => 42
    });
sample(queue_snapshot, full) ->
    beam4pm_types:new_queue_snapshot(#{
        queue_name => <<"sample_queue_name">>,
        depth => 42,
        observed_at => <<"2026-08-29T12:00:00Z">>
    });
sample(queue_snapshot, minimal) ->
    beam4pm_types:new_queue_snapshot(#{
        queue_name => <<"sample_queue_name">>,
        depth => 42,
        observed_at => <<"2026-08-29T12:00:00Z">>
    });
sample(resource_allocation, full) ->
    beam4pm_types:new_resource_allocation(#{
        resource_id => <<"sample_resource_id">>,
        activity => <<"sample_activity">>,
        event_id => <<"sample_event_id">>
    });
sample(resource_allocation, minimal) ->
    beam4pm_types:new_resource_allocation(#{
        resource_id => <<"sample_resource_id">>,
        activity => <<"sample_activity">>,
        event_id => <<"sample_event_id">>
    });
sample(service_span, full) ->
    beam4pm_types:new_service_span(#{
        span_id => <<"sample_span_id">>,
        service_name => <<"sample_service_name">>,
        duration_ms => 42,
        parent_span_id => <<"sample_parent_span_id">>
    });
sample(service_span, minimal) ->
    beam4pm_types:new_service_span(#{
        span_id => <<"sample_span_id">>,
        service_name => <<"sample_service_name">>,
        duration_ms => 42
    });
sample(sojourn_time, full) ->
    beam4pm_types:new_sojourn_time(#{
        object_id => <<"sample_object_id">>,
        event_type => <<"sample_event_type">>,
        seconds => 3.5
    });
sample(sojourn_time, minimal) ->
    beam4pm_types:new_sojourn_time(#{
        object_id => <<"sample_object_id">>,
        event_type => <<"sample_event_type">>,
        seconds => 3.5
    });
sample(sync_time, full) ->
    beam4pm_types:new_sync_time(#{
        object_id => <<"sample_object_id">>,
        delaying_object_id => <<"sample_delaying_object_id">>,
        seconds => 3.5
    });
sample(sync_time, minimal) ->
    beam4pm_types:new_sync_time(#{
        object_id => <<"sample_object_id">>,
        seconds => 3.5
    });
sample(type_edge, full) ->
    beam4pm_types:new_type_edge(#{
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        qualifier => <<"sample_qualifier">>,
        direction => sample_atom
    });
sample(type_edge, minimal) ->
    beam4pm_types:new_type_edge(#{
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        qualifier => <<"sample_qualifier">>,
        direction => sample_atom
    });
sample(usage_event, full) ->
    beam4pm_types:new_usage_event(#{
        event_id => <<"sample_event_id">>,
        entitlement_id => <<"sample_entitlement_id">>,
        quantity => 3.5,
        metric_name => <<"sample_metric_name">>,
        occurred_at => <<"2026-08-29T12:00:00Z">>
    });
sample(usage_event, minimal) ->
    beam4pm_types:new_usage_event(#{
        event_id => <<"sample_event_id">>,
        entitlement_id => <<"sample_entitlement_id">>,
        quantity => 3.5,
        metric_name => <<"sample_metric_name">>,
        occurred_at => <<"2026-08-29T12:00:00Z">>
    });
sample(Name, Variant) ->
    erlang:error({unknown_sample, Name, Variant}).

%% Write every record x variant sample as Dir/<record>.<variant>.erl.json.
-spec write_samples(file:filename_all()) -> ok.
write_samples(Dir) ->
    ok = filelib:ensure_path(Dir),
    lists:foreach(
        fun({Name, Variant}) ->
            {ok, Rec} = sample(Name, Variant),
            Json = beam4pm_codec:encode(Rec),
            Path = filename:join(Dir, sample_basename(Name, Variant, "erl")),
            ok = file:write_file(Path, Json)
        end,
        pairs()),
    ok.

%% Read every record x variant fixture Dir/<record>.<variant>.<Suffix>.json,
%% decode it, and compare its canonical map against this module's own sample.
-spec verify_samples(file:filename_all(), string()) ->
    {non_neg_integer(), [string()]}.
verify_samples(Dir, Suffix) ->
    lists:foldl(
        fun({Name, Variant}, {Pass, Failures}) ->
            Label = atom_to_list(Name) ++ "." ++ atom_to_list(Variant),
            Path = filename:join(Dir, sample_basename(Name, Variant, Suffix)),
            {ok, Expected} = sample(Name, Variant),
            case file:read_file(Path) of
                {ok, Bin} ->
                    case beam4pm_codec:decode(Name, Bin) of
                        {ok, Decoded} ->
                            case beam4pm_codec:to_map(Decoded) =:= beam4pm_codec:to_map(Expected) of
                                true -> {Pass + 1, Failures};
                                false -> {Pass, Failures ++ [Label ++ ": map mismatch"]}
                            end;
                        {error, Reason} ->
                            {Pass, Failures ++ [Label ++ ": decode error " ++ format_term(Reason)]}
                    end;
                {error, Reason} ->
                    {Pass, Failures ++ [Label ++ ": read error " ++ format_term(Reason)]}
            end
        end,
        {0, []},
        pairs()).

%% internal

pairs() ->
    [{Name, Variant} || Name <- record_names(), Variant <- [full, minimal]].

sample_basename(Name, Variant, Suffix) ->
    atom_to_list(Name) ++ "." ++ atom_to_list(Variant) ++ "." ++ Suffix ++ ".json".

format_term(Term) ->
    lists:flatten(io_lib:format("~0p", [Term])).
