%% GENERATED by ggen from the admitted bpm:RecordType graph. Do not edit.

-module(beam4pm_types).

-export([
    new_account_master_match/1,
    new_account_parent_scope/1,
    new_alignment_move/1,
    new_billing_reconciliation/1,
    new_case_stats/1,
    new_conformance_result/1,
    new_contracting_entity_identity/1,
    new_data_processing_addendum_state/1,
    new_dfg_edge/1,
    new_entitlement_event/1,
    new_entitlement_state/1,
    new_event_log/1,
    new_event_type/1,
    new_heuristic_arc/1,
    new_insurance_requirement/1,
    new_invoice_entity_identity/1,
    new_k8s_object_ref/1,
    new_log_trace/1,
    new_master_service_agreement_state/1,
    new_object_attribute_change/1,
    new_object_type/1,
    new_oc_declare_constraint/1,
    new_ocel_attribute/1,
    new_ocel_event/1,
    new_ocel_object/1,
    new_ocel_relationship/1,
    new_opportunity_currency_contract/1,
    new_opportunity_value_range/1,
    new_path_schema/1,
    new_path_schema_query/1,
    new_payment_terms_admission/1,
    new_petri_arc/1,
    new_petri_place/1,
    new_petri_transition/1,
    new_planning_action/1,
    new_planning_state/1,
    new_policy_decision/1,
    new_process_variant/1,
    new_procurement_channel_selection/1,
    new_purchase_order_requirement/1,
    new_purchasing_entity_identity/1,
    new_queue_snapshot/1,
    new_resource_allocation/1,
    new_revenue_schedule_assumption/1,
    new_sanctions_screening_result/1,
    new_security_addendum_state/1,
    new_service_span/1,
    new_sojourn_time/1,
    new_sync_time/1,
    new_tax_jurisdiction_evidence/1,
    new_type_edge/1,
    new_usage_event/1,
    new_vendor_registration_state/1
]).

-export_type([
    account_master_match/0,
    account_parent_scope/0,
    alignment_move/0,
    billing_reconciliation/0,
    case_stats/0,
    conformance_result/0,
    contracting_entity_identity/0,
    data_processing_addendum_state/0,
    dfg_edge/0,
    entitlement_event/0,
    entitlement_state/0,
    event_log/0,
    event_type/0,
    heuristic_arc/0,
    insurance_requirement/0,
    invoice_entity_identity/0,
    k8s_object_ref/0,
    log_trace/0,
    master_service_agreement_state/0,
    object_attribute_change/0,
    object_type/0,
    oc_declare_constraint/0,
    ocel_attribute/0,
    ocel_event/0,
    ocel_object/0,
    ocel_relationship/0,
    opportunity_currency_contract/0,
    opportunity_value_range/0,
    path_schema/0,
    path_schema_query/0,
    payment_terms_admission/0,
    petri_arc/0,
    petri_place/0,
    petri_transition/0,
    planning_action/0,
    planning_state/0,
    policy_decision/0,
    process_variant/0,
    procurement_channel_selection/0,
    purchase_order_requirement/0,
    purchasing_entity_identity/0,
    queue_snapshot/0,
    resource_allocation/0,
    revenue_schedule_assumption/0,
    sanctions_screening_result/0,
    security_addendum_state/0,
    service_span/0,
    sojourn_time/0,
    sync_time/0,
    tax_jurisdiction_evidence/0,
    type_edge/0,
    usage_event/0,
    vendor_registration_state/0
]).

%% Admits a source account only when it is bound to one canonical Fortune-5 account by immutable matching evidence; prevents pipeline value from being booked against an ambiguous customer identity.
-record(account_master_match, {
    source_account_id :: binary(), %% source_account_id: Required commercial-admission input for account master match. Missing input is a typed refusal.
    canonical_account_id :: binary(), %% canonical_account_id: Required commercial-admission input for account master match. Missing input is a typed refusal.
    match_evidence_hash :: binary() %% match_evidence_hash: Immutable evidence identity that makes this admission independently replayable.
}).

-type account_master_match() :: #account_master_match{}.

-spec new_account_master_match(map()) -> {ok, account_master_match()} | {error, {missing_field, atom()}}.
new_account_master_match(Map) ->
    case maps:is_key(source_account_id, Map) of
        false -> {error, {missing_field, source_account_id}};
        true ->
    case maps:is_key(canonical_account_id, Map) of
        false -> {error, {missing_field, canonical_account_id}};
        true ->
    case maps:is_key(match_evidence_hash, Map) of
        false -> {error, {missing_field, match_evidence_hash}};
        true ->
    {ok, #account_master_match{
        source_account_id = maps:get(source_account_id, Map, undefined),
        canonical_account_id = maps:get(canonical_account_id, Map, undefined),
        match_evidence_hash = maps:get(match_evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% Qualifies an account only when its buying scope is bound to the correct global parent, preventing subsidiary demand from being double-counted as independent enterprise pipeline.
-record(account_parent_scope, {
    account_id :: binary(), %% account_id: Required account parent scope input; omission is an executable typed refusal, never an inferred approval.
    parent_account_id :: binary(), %% parent_account_id: Required account parent scope input; omission is an executable typed refusal, never an inferred approval.
    scope_evidence_hash :: binary() %% scope_evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type account_parent_scope() :: #account_parent_scope{}.

-spec new_account_parent_scope(map()) -> {ok, account_parent_scope()} | {error, {missing_field, atom()}}.
new_account_parent_scope(Map) ->
    case maps:is_key(account_id, Map) of
        false -> {error, {missing_field, account_id}};
        true ->
    case maps:is_key(parent_account_id, Map) of
        false -> {error, {missing_field, parent_account_id}};
        true ->
    case maps:is_key(scope_evidence_hash, Map) of
        false -> {error, {missing_field, scope_evidence_hash}};
        true ->
    {ok, #account_parent_scope{
        account_id = maps:get(account_id, Map, undefined),
        parent_account_id = maps:get(parent_account_id, Map, undefined),
        scope_evidence_hash = maps:get(scope_evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% One step of a conformance-checking alignment between log and model.
-record(alignment_move, {
    move_type :: atom(), %% move_type: One of: sync | model | log | silent.
    cost :: integer() %% cost: Non-negative cost assigned to this move.
}).

-type alignment_move() :: #alignment_move{}.

-spec new_alignment_move(map()) -> {ok, alignment_move()} | {error, {missing_field, atom()}}.
new_alignment_move(Map) ->
    case maps:is_key(move_type, Map) of
        false -> {error, {missing_field, move_type}};
        true ->
    case maps:is_key(cost, Map) of
        false -> {error, {missing_field, cost}};
        true ->
    {ok, #alignment_move{
        move_type = maps:get(move_type, Map, undefined),
        cost = maps:get(cost, Map, undefined)
    }}
    end
    end.

%% The reconciled billable total for one (entitlement_id, metric_name) pair over one half-open period [period_start, period_end). INVARIANT: total_quantity is exactly the sum of usage_event.quantity over the distinct event_ids listed in applied_event_ids, summed in that list's ascending order; applied_event_ids is sorted and duplicate-free. Consequently the same usage_event.event_id can never contribute twice, no matter how many times or in what order it appears in the input stream.
-record(billing_reconciliation, {
    entitlement_id :: binary(), %% entitlement_id: The entitlement this total is billed against. First component of the reconciliation partition key.
    metric_name :: binary(), %% metric_name: The metered dimension this total is for. Second component of the reconciliation partition key; totals are never summed across metrics.
    total_quantity :: float(), %% total_quantity: The billable total: the sum of quantity over the distinct events named in applied_event_ids, accumulated in that list's ascending event_id order. The fixed summation order is load-bearing, not incidental -- float addition is non-associative, so only a canonical order makes the total bit-identical across arrival orders and across replays. Recomputable by any third party from applied_event_ids plus the usage_event store, which is what makes this a receipt rather than a claim.
    applied_event_ids :: [binary()], %% applied_event_ids: The exact deduplicated evidence set behind total_quantity: every usage_event.event_id counted, sorted ascending, with no duplicates. This is the dedup contract made auditable -- |applied_event_ids| is the honest count of billed occurrences, and any event_id appearing at most once here is a mechanically checkable falsifier for MP6 double-billing.
    period_start :: binary(), %% period_start: ISO8601 UTC INCLUSIVE lower bound of the billing period. An event is in-period when period_start <= occurred_at. Caller-supplied to reconcile_billing/4, never derived from the input events themselves -- see period_end's fieldDoc for why.
    period_end :: binary() %% period_end: ISO8601 UTC EXCLUSIVE upper bound of the billing period. An event is in-period when occurred_at < period_end. The exclusive bound is what prevents an event landing exactly on a period boundary from being counted by both the closing and the opening period -- a boundary double-bill that per-period dedup alone would not catch. reconcile_billing/4 takes {PeriodStart, PeriodEnd} as an explicit argument and filters events by it before dedup, which is what makes this guarantee real.
}).

-type billing_reconciliation() :: #billing_reconciliation{}.

-spec new_billing_reconciliation(map()) -> {ok, billing_reconciliation()} | {error, {missing_field, atom()}}.
new_billing_reconciliation(Map) ->
    case maps:is_key(entitlement_id, Map) of
        false -> {error, {missing_field, entitlement_id}};
        true ->
    case maps:is_key(metric_name, Map) of
        false -> {error, {missing_field, metric_name}};
        true ->
    case maps:is_key(total_quantity, Map) of
        false -> {error, {missing_field, total_quantity}};
        true ->
    case maps:is_key(applied_event_ids, Map) of
        false -> {error, {missing_field, applied_event_ids}};
        true ->
    case maps:is_key(period_start, Map) of
        false -> {error, {missing_field, period_start}};
        true ->
    case maps:is_key(period_end, Map) of
        false -> {error, {missing_field, period_end}};
        true ->
    {ok, #billing_reconciliation{
        entitlement_id = maps:get(entitlement_id, Map, undefined),
        metric_name = maps:get(metric_name, Map, undefined),
        total_quantity = maps:get(total_quantity, Map, undefined),
        applied_event_ids = maps:get(applied_event_ids, Map, undefined),
        period_start = maps:get(period_start, Map, undefined),
        period_end = maps:get(period_end, Map, undefined)
    }}
    end
    end
    end
    end
    end
    end.

%% Aggregate statistics computed for one process instance (case).
-record(case_stats, {
    case_id :: binary(), %% case_id: Unique case identifier.
    event_count :: integer(), %% event_count: Number of events observed for this case.
    duration_seconds :: float() | undefined %% duration_seconds: Optional case duration in seconds (end minus start).
}).

-type case_stats() :: #case_stats{}.

-spec new_case_stats(map()) -> {ok, case_stats()} | {error, {missing_field, atom()}}.
new_case_stats(Map) ->
    case maps:is_key(case_id, Map) of
        false -> {error, {missing_field, case_id}};
        true ->
    case maps:is_key(event_count, Map) of
        false -> {error, {missing_field, event_count}};
        true ->
    {ok, #case_stats{
        case_id = maps:get(case_id, Map, undefined),
        event_count = maps:get(event_count, Map, undefined),
        duration_seconds = maps:get(duration_seconds, Map, undefined)
    }}
    end
    end.

%% Conformance-checking metrics computed for one trace against a model.
-record(conformance_result, {
    trace_id :: binary(), %% trace_id: Identifier of the trace this result was computed for.
    fitness :: float(), %% fitness: Fitness score in [0.0, 1.0].
    precision :: float() | undefined %% precision: Optional precision score in [0.0, 1.0].
}).

-type conformance_result() :: #conformance_result{}.

-spec new_conformance_result(map()) -> {ok, conformance_result()} | {error, {missing_field, atom()}}.
new_conformance_result(Map) ->
    case maps:is_key(trace_id, Map) of
        false -> {error, {missing_field, trace_id}};
        true ->
    case maps:is_key(fitness, Map) of
        false -> {error, {missing_field, fitness}};
        true ->
    {ok, #conformance_result{
        trace_id = maps:get(trace_id, Map, undefined),
        fitness = maps:get(fitness, Map, undefined),
        precision = maps:get(precision, Map, undefined)
    }}
    end
    end.

%% Requires the counterparty that will sign the agreement, separating contractual authority from account interest.
-record(contracting_entity_identity, {
    opportunity_id :: binary(), %% opportunity_id: Required contracting entity identity input; omission is an executable typed refusal, never an inferred approval.
    contracting_entity_id :: binary(), %% contracting_entity_id: Required contracting entity identity input; omission is an executable typed refusal, never an inferred approval.
    identity_evidence_hash :: binary() %% identity_evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type contracting_entity_identity() :: #contracting_entity_identity{}.

-spec new_contracting_entity_identity(map()) -> {ok, contracting_entity_identity()} | {error, {missing_field, atom()}}.
new_contracting_entity_identity(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(contracting_entity_id, Map) of
        false -> {error, {missing_field, contracting_entity_id}};
        true ->
    case maps:is_key(identity_evidence_hash, Map) of
        false -> {error, {missing_field, identity_evidence_hash}};
        true ->
    {ok, #contracting_entity_identity{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        contracting_entity_id = maps:get(contracting_entity_id, Map, undefined),
        identity_evidence_hash = maps:get(identity_evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% Requires an identified data-processing addendum state for workloads involving regulated enterprise data.
-record(data_processing_addendum_state, {
    opportunity_id :: binary(), %% opportunity_id: Required data processing addendum state input; omission is an executable typed refusal, never an inferred approval.
    addendum_id :: binary(), %% addendum_id: Required data processing addendum state input; omission is an executable typed refusal, never an inferred approval.
    addendum_state :: binary() %% addendum_state: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type data_processing_addendum_state() :: #data_processing_addendum_state{}.

-spec new_data_processing_addendum_state(map()) -> {ok, data_processing_addendum_state()} | {error, {missing_field, atom()}}.
new_data_processing_addendum_state(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(addendum_id, Map) of
        false -> {error, {missing_field, addendum_id}};
        true ->
    case maps:is_key(addendum_state, Map) of
        false -> {error, {missing_field, addendum_state}};
        true ->
    {ok, #data_processing_addendum_state{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        addendum_id = maps:get(addendum_id, Map, undefined),
        addendum_state = maps:get(addendum_state, Map, undefined)
    }}
    end
    end
    end.

%% One frequency-annotated directly-follows edge between two activities.
-record(dfg_edge, {
    source_activity :: binary(), %% source_activity: The preceding activity name.
    target_activity :: binary(), %% target_activity: The following activity name.
    frequency :: integer() %% frequency: Observed occurrence count of this edge.
}).

-type dfg_edge() :: #dfg_edge{}.

-spec new_dfg_edge(map()) -> {ok, dfg_edge()} | {error, {missing_field, atom()}}.
new_dfg_edge(Map) ->
    case maps:is_key(source_activity, Map) of
        false -> {error, {missing_field, source_activity}};
        true ->
    case maps:is_key(target_activity, Map) of
        false -> {error, {missing_field, target_activity}};
        true ->
    case maps:is_key(frequency, Map) of
        false -> {error, {missing_field, frequency}};
        true ->
    {ok, #dfg_edge{
        source_activity = maps:get(source_activity, Map, undefined),
        target_activity = maps:get(target_activity, Map, undefined),
        frequency = maps:get(frequency, Map, undefined)
    }}
    end
    end
    end.

%% One inbound marketplace entitlement/order/agreement lifecycle event, as delivered by the provider's notification topic. Append-only and at-least-once: the same event_id may be delivered any number of times, in any order relative to other events. Modeled on the Google Cloud Commerce Partner Procurement API Pub/Sub notification message, whose payload carries both an eventId and an entitlement id.
-record(entitlement_event, {
    event_id :: binary(), %% event_id: DEDUP KEY. The provider's own globally unique notification identifier (the eventId field of the Partner Procurement Pub/Sub message). Two deliveries carrying the same event_id are the same event and must fold to the same entitlement_state exactly once. This is provider-assigned, never locally minted -- a locally generated id would make redelivery indistinguishable from a genuine new event.
    entitlement_id :: binary(), %% entitlement_id: The commercial identity this event applies to (Partner Procurement ENTITLEMENT_ID). Reconciliation partitions strictly by this key. Google supports multiple concurrent orders of the same product, so entitlement_id -- not account id and not product id -- is the only admissible partition key.
    event_type :: binary(), %% event_type: CLOSED SET, exactly the 13 entitlement event types published by Google Cloud Marketplace for integrated SaaS products: ENTITLEMENT_CREATION_REQUESTED | ENTITLEMENT_OFFER_ACCEPTED | ENTITLEMENT_ACTIVE | ENTITLEMENT_PLAN_CHANGE_REQUESTED | ENTITLEMENT_PLAN_CHANGED | ENTITLEMENT_PLAN_CHANGE_CANCELLED | ENTITLEMENT_PENDING_CANCELLATION | ENTITLEMENT_CANCELLATION_REVERTED | ENTITLEMENT_CANCELLED | ENTITLEMENT_CANCELLING | ENTITLEMENT_RENEWED | ENTITLEMENT_OFFER_ENDED | ENTITLEMENT_DELETED. Typed string, deliberately NOT atom: these values arrive verbatim from an external wire and binary_to_atom/2 over untrusted input is an unbounded atom-table growth path on the BEAM. An unrecognized value is a typed refusal, never a silently ignored event.
    effective_at :: binary(), %% effective_at: ISO8601 UTC instant at which this event takes commercial effect (provider-assigned, not local receipt time). Primary component of the reconciliation watermark; ties are broken by event_id so that the fold is a total order and therefore order-independent. Local receipt time is deliberately not modeled: it would make the fold non-deterministic under replay.
    payload :: map() | undefined %% payload: Optional provider-specific extra fields carried verbatim (e.g. account id, product/plan id, offer id, newPlan, newOffer, scheduled start time). Retained for receipt/audit fidelity; the reconciliation fold reads NO field from this map -- everything the fold depends on is promoted to a typed top-level field above.
}).

-type entitlement_event() :: #entitlement_event{}.

-spec new_entitlement_event(map()) -> {ok, entitlement_event()} | {error, {missing_field, atom()}}.
new_entitlement_event(Map) ->
    case maps:is_key(event_id, Map) of
        false -> {error, {missing_field, event_id}};
        true ->
    case maps:is_key(entitlement_id, Map) of
        false -> {error, {missing_field, entitlement_id}};
        true ->
    case maps:is_key(event_type, Map) of
        false -> {error, {missing_field, event_type}};
        true ->
    case maps:is_key(effective_at, Map) of
        false -> {error, {missing_field, effective_at}};
        true ->
    {ok, #entitlement_event{
        event_id = maps:get(event_id, Map, undefined),
        entitlement_id = maps:get(entitlement_id, Map, undefined),
        event_type = maps:get(event_type, Map, undefined),
        effective_at = maps:get(effective_at, Map, undefined),
        payload = maps:get(payload, Map, undefined)
    }}
    end
    end
    end
    end.

%% The reconciled current state of one entitlement, derived purely by folding its entitlement_event set. The fold is idempotent (replaying an already-applied event is a no-op) and commutative in arrival order (an older event arriving after a newer one is a no-op), because an event is applied if and only if its (effective_at, event_id) pair is strictly greater than the state's (updated_at, last_applied_event_id) watermark.
-record(entitlement_state, {
    entitlement_id :: binary(), %% entitlement_id: The commercial identity this state describes (Partner Procurement ENTITLEMENT_ID). Unique key: at most one entitlement_state exists per entitlement_id.
    status :: binary(), %% status: CLOSED SET, exactly the 8 values of the Cloud Commerce Partner Procurement API's EntitlementState enum: ENTITLEMENT_STATE_UNSPECIFIED | ENTITLEMENT_ACTIVATION_REQUESTED | ENTITLEMENT_ACTIVE | ENTITLEMENT_PENDING_CANCELLATION | ENTITLEMENT_CANCELLED | ENTITLEMENT_PENDING_PLAN_CHANGE | ENTITLEMENT_PENDING_PLAN_CHANGE_APPROVAL | ENTITLEMENT_SUSPENDED. This is the provider's STATE enum, which is deliberately not the same closed set as entitlement_event.event_type: ENTITLEMENT_SUSPENDED is a reachable state with no corresponding notification event type, and ENTITLEMENT_RENEWED / ENTITLEMENT_OFFER_ENDED / ENTITLEMENT_DELETED are event types with no distinct state. The event_type -> status transition table is therefore an explicit, non-identity mapping, never a string rename.
    last_applied_event_id :: binary(), %% last_applied_event_id: The event_id of the single entitlement_event that produced this state. Second (tiebreak) component of the reconciliation watermark, and the audit link from a commercial state back to the exact provider notification that caused it. Required, never undefined: an entitlement_state may only be constructed by applying a real event, so there is no lawful state without a causing event id.
    updated_at :: binary() %% updated_at: The effective_at of the last applied event -- NOT wall-clock ingestion time. First component of the reconciliation watermark. Defining it as provider effective time (a) makes the state a pure function of the event set, so the same events replayed in any order at any later date rebuild a byte-identical state, and (b) makes the strictly-greater-than admission test well-founded. A wall-clock updated_at would silently admit an out-of-order older event, because it always advances.
}).

-type entitlement_state() :: #entitlement_state{}.

-spec new_entitlement_state(map()) -> {ok, entitlement_state()} | {error, {missing_field, atom()}}.
new_entitlement_state(Map) ->
    case maps:is_key(entitlement_id, Map) of
        false -> {error, {missing_field, entitlement_id}};
        true ->
    case maps:is_key(status, Map) of
        false -> {error, {missing_field, status}};
        true ->
    case maps:is_key(last_applied_event_id, Map) of
        false -> {error, {missing_field, last_applied_event_id}};
        true ->
    case maps:is_key(updated_at, Map) of
        false -> {error, {missing_field, updated_at}};
        true ->
    {ok, #entitlement_state{
        entitlement_id = maps:get(entitlement_id, Map, undefined),
        status = maps:get(status, Map, undefined),
        last_applied_event_id = maps:get(last_applied_event_id, Map, undefined),
        updated_at = maps:get(updated_at, Map, undefined)
    }}
    end
    end
    end
    end.

%% A named collection of events forming one process-mining log.
-record(event_log, {
    log_id :: binary(), %% log_id: Unique log identifier.
    name :: binary(), %% name: Human-readable log name.
    description :: binary() | undefined %% description: Optional free-text description of this log.
}).

-type event_log() :: #event_log{}.

-spec new_event_log(map()) -> {ok, event_log()} | {error, {missing_field, atom()}}.
new_event_log(Map) ->
    case maps:is_key(log_id, Map) of
        false -> {error, {missing_field, log_id}};
        true ->
    case maps:is_key(name, Map) of
        false -> {error, {missing_field, name}};
        true ->
    {ok, #event_log{
        log_id = maps:get(log_id, Map, undefined),
        name = maps:get(name, Map, undefined),
        description = maps:get(description, Map, undefined)
    }}
    end
    end.

%% A declared OCEL event type and its attribute schema.
-record(event_type, {
    type_name :: binary(), %% type_name: The event type name.
    attribute_names :: [binary()] | undefined %% attribute_names: Optional declared attribute names for events of this type (name-only; per-attribute value types are not yet modeled).
}).

-type event_type() :: #event_type{}.

-spec new_event_type(map()) -> {ok, event_type()} | {error, {missing_field, atom()}}.
new_event_type(Map) ->
    case maps:is_key(type_name, Map) of
        false -> {error, {missing_field, type_name}};
        true ->
    {ok, #event_type{
        type_name = maps:get(type_name, Map, undefined),
        attribute_names = maps:get(attribute_names, Map, undefined)
    }}
    end.

%% One dependency-scored candidate arc considered during heuristic-net discovery.
-record(heuristic_arc, {
    source_activity :: binary(), %% source_activity: The candidate arc source activity.
    target_activity :: binary(), %% target_activity: The candidate arc target activity.
    dependency_measure :: float() %% dependency_measure: The computed dependency/confidence score for this candidate arc.
}).

-type heuristic_arc() :: #heuristic_arc{}.

-spec new_heuristic_arc(map()) -> {ok, heuristic_arc()} | {error, {missing_field, atom()}}.
new_heuristic_arc(Map) ->
    case maps:is_key(source_activity, Map) of
        false -> {error, {missing_field, source_activity}};
        true ->
    case maps:is_key(target_activity, Map) of
        false -> {error, {missing_field, target_activity}};
        true ->
    case maps:is_key(dependency_measure, Map) of
        false -> {error, {missing_field, dependency_measure}};
        true ->
    {ok, #heuristic_arc{
        source_activity = maps:get(source_activity, Map, undefined),
        target_activity = maps:get(target_activity, Map, undefined),
        dependency_measure = maps:get(dependency_measure, Map, undefined)
    }}
    end
    end
    end.

%% Admits contractual insurance coverage only with an exact coverage identity and supporting evidence.
-record(insurance_requirement, {
    opportunity_id :: binary(), %% opportunity_id: Required insurance requirement input; omission is an executable typed refusal, never an inferred approval.
    coverage_id :: binary(), %% coverage_id: Required insurance requirement input; omission is an executable typed refusal, never an inferred approval.
    evidence_hash :: binary() %% evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type insurance_requirement() :: #insurance_requirement{}.

-spec new_insurance_requirement(map()) -> {ok, insurance_requirement()} | {error, {missing_field, atom()}}.
new_insurance_requirement(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(coverage_id, Map) of
        false -> {error, {missing_field, coverage_id}};
        true ->
    case maps:is_key(evidence_hash, Map) of
        false -> {error, {missing_field, evidence_hash}};
        true ->
    {ok, #insurance_requirement{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        coverage_id = maps:get(coverage_id, Map, undefined),
        evidence_hash = maps:get(evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% Requires the entity responsible for invoice acceptance, preventing qualified demand from becoming uncollectable revenue.
-record(invoice_entity_identity, {
    opportunity_id :: binary(), %% opportunity_id: Required invoice entity identity input; omission is an executable typed refusal, never an inferred approval.
    invoice_entity_id :: binary(), %% invoice_entity_id: Required invoice entity identity input; omission is an executable typed refusal, never an inferred approval.
    identity_evidence_hash :: binary() %% identity_evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type invoice_entity_identity() :: #invoice_entity_identity{}.

-spec new_invoice_entity_identity(map()) -> {ok, invoice_entity_identity()} | {error, {missing_field, atom()}}.
new_invoice_entity_identity(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(invoice_entity_id, Map) of
        false -> {error, {missing_field, invoice_entity_id}};
        true ->
    case maps:is_key(identity_evidence_hash, Map) of
        false -> {error, {missing_field, identity_evidence_hash}};
        true ->
    {ok, #invoice_entity_identity{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        invoice_entity_id = maps:get(invoice_entity_id, Map, undefined),
        identity_evidence_hash = maps:get(identity_evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% A reference to one Kubernetes object observed in the runtime topology.
-record(k8s_object_ref, {
    kind :: binary(), %% kind: The Kubernetes object kind (e.g. Pod, Deployment).
    name :: binary(), %% name: The object name.
    namespace :: binary() | undefined %% namespace: Optional object namespace (absent for cluster-scoped kinds such as Node, PersistentVolume, ClusterRole, or Namespace itself).
}).

-type k8s_object_ref() :: #k8s_object_ref{}.

-spec new_k8s_object_ref(map()) -> {ok, k8s_object_ref()} | {error, {missing_field, atom()}}.
new_k8s_object_ref(Map) ->
    case maps:is_key(kind, Map) of
        false -> {error, {missing_field, kind}};
        true ->
    case maps:is_key(name, Map) of
        false -> {error, {missing_field, name}};
        true ->
    {ok, #k8s_object_ref{
        kind = maps:get(kind, Map, undefined),
        name = maps:get(name, Map, undefined),
        namespace = maps:get(namespace, Map, undefined)
    }}
    end
    end.

%% One case-centric trace: an ordered activity sequence for a single case.
-record(log_trace, {
    case_id :: binary(), %% case_id: Identifier of the case this trace belongs to.
    activity_sequence :: [binary()] %% activity_sequence: Ordered list of activity names observed for this case.
}).

-type log_trace() :: #log_trace{}.

-spec new_log_trace(map()) -> {ok, log_trace()} | {error, {missing_field, atom()}}.
new_log_trace(Map) ->
    case maps:is_key(case_id, Map) of
        false -> {error, {missing_field, case_id}};
        true ->
    case maps:is_key(activity_sequence, Map) of
        false -> {error, {missing_field, activity_sequence}};
        true ->
    {ok, #log_trace{
        case_id = maps:get(case_id, Map, undefined),
        activity_sequence = maps:get(activity_sequence, Map, undefined)
    }}
    end
    end.

%% Tracks the exact master service agreement and its executable admission state rather than treating legal review as a boolean.
-record(master_service_agreement_state, {
    opportunity_id :: binary(), %% opportunity_id: Required master service agreement state input; omission is an executable typed refusal, never an inferred approval.
    agreement_id :: binary(), %% agreement_id: Required master service agreement state input; omission is an executable typed refusal, never an inferred approval.
    agreement_state :: binary() %% agreement_state: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type master_service_agreement_state() :: #master_service_agreement_state{}.

-spec new_master_service_agreement_state(map()) -> {ok, master_service_agreement_state()} | {error, {missing_field, atom()}}.
new_master_service_agreement_state(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(agreement_id, Map) of
        false -> {error, {missing_field, agreement_id}};
        true ->
    case maps:is_key(agreement_state, Map) of
        false -> {error, {missing_field, agreement_state}};
        true ->
    {ok, #master_service_agreement_state{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        agreement_id = maps:get(agreement_id, Map, undefined),
        agreement_state = maps:get(agreement_state, Map, undefined)
    }}
    end
    end
    end.

%% One recorded change to a time-indexed object attribute.
-record(object_attribute_change, {
    object_id :: binary(), %% object_id: Identifier of the object whose attribute changed.
    attribute_name :: binary(), %% attribute_name: The changed attribute name.
    old_value :: binary() | undefined, %% old_value: Optional previous value (absent if this is the first recorded value).
    new_value :: binary(), %% new_value: The new value after the change.
    changed_at :: binary() %% changed_at: ISO8601 timestamp the change took effect.
}).

-type object_attribute_change() :: #object_attribute_change{}.

-spec new_object_attribute_change(map()) -> {ok, object_attribute_change()} | {error, {missing_field, atom()}}.
new_object_attribute_change(Map) ->
    case maps:is_key(object_id, Map) of
        false -> {error, {missing_field, object_id}};
        true ->
    case maps:is_key(attribute_name, Map) of
        false -> {error, {missing_field, attribute_name}};
        true ->
    case maps:is_key(new_value, Map) of
        false -> {error, {missing_field, new_value}};
        true ->
    case maps:is_key(changed_at, Map) of
        false -> {error, {missing_field, changed_at}};
        true ->
    {ok, #object_attribute_change{
        object_id = maps:get(object_id, Map, undefined),
        attribute_name = maps:get(attribute_name, Map, undefined),
        old_value = maps:get(old_value, Map, undefined),
        new_value = maps:get(new_value, Map, undefined),
        changed_at = maps:get(changed_at, Map, undefined)
    }}
    end
    end
    end
    end.

%% A declared OCEL object type and its attribute schema.
-record(object_type, {
    type_name :: binary(), %% type_name: The object type name.
    attribute_names :: [binary()] | undefined %% attribute_names: Optional declared attribute names for objects of this type (name-only; per-attribute value types are not yet modeled).
}).

-type object_type() :: #object_type{}.

-spec new_object_type(map()) -> {ok, object_type()} | {error, {missing_field, atom()}}.
new_object_type(Map) ->
    case maps:is_key(type_name, Map) of
        false -> {error, {missing_field, type_name}};
        true ->
    {ok, #object_type{
        type_name = maps:get(type_name, Map, undefined),
        attribute_names = maps:get(attribute_names, Map, undefined)
    }}
    end.

%% One declarative object-centric behavioral constraint between two activities.
-record(oc_declare_constraint, {
    constraint_id :: binary(), %% constraint_id: Unique constraint identifier.
    source_activity :: binary(), %% source_activity: The constraint source activity.
    target_activity :: binary(), %% target_activity: The constraint target activity.
    constraint_type :: atom() %% constraint_type: One of: response | precedence | succession | non_coexistence (standard DECLARE constraint template names).
}).

-type oc_declare_constraint() :: #oc_declare_constraint{}.

-spec new_oc_declare_constraint(map()) -> {ok, oc_declare_constraint()} | {error, {missing_field, atom()}}.
new_oc_declare_constraint(Map) ->
    case maps:is_key(constraint_id, Map) of
        false -> {error, {missing_field, constraint_id}};
        true ->
    case maps:is_key(source_activity, Map) of
        false -> {error, {missing_field, source_activity}};
        true ->
    case maps:is_key(target_activity, Map) of
        false -> {error, {missing_field, target_activity}};
        true ->
    case maps:is_key(constraint_type, Map) of
        false -> {error, {missing_field, constraint_type}};
        true ->
    {ok, #oc_declare_constraint{
        constraint_id = maps:get(constraint_id, Map, undefined),
        source_activity = maps:get(source_activity, Map, undefined),
        target_activity = maps:get(target_activity, Map, undefined),
        constraint_type = maps:get(constraint_type, Map, undefined)
    }}
    end
    end
    end
    end.

%% One named, timestamped attribute value on an OCEL event or object.
-record(ocel_attribute, {
    attribute_name :: binary(), %% attribute_name: The attribute name.
    attribute_value :: binary(), %% attribute_value: The attribute value, serialized as a string.
    recorded_at :: binary() | undefined %% recorded_at: Optional ISO8601 timestamp this value was recorded/became effective.
}).

-type ocel_attribute() :: #ocel_attribute{}.

-spec new_ocel_attribute(map()) -> {ok, ocel_attribute()} | {error, {missing_field, atom()}}.
new_ocel_attribute(Map) ->
    case maps:is_key(attribute_name, Map) of
        false -> {error, {missing_field, attribute_name}};
        true ->
    case maps:is_key(attribute_value, Map) of
        false -> {error, {missing_field, attribute_value}};
        true ->
    {ok, #ocel_attribute{
        attribute_name = maps:get(attribute_name, Map, undefined),
        attribute_value = maps:get(attribute_value, Map, undefined),
        recorded_at = maps:get(recorded_at, Map, undefined)
    }}
    end
    end.

%% An OCEL 2.0 event: one recorded occurrence in an object-centric log.
-record(ocel_event, {
    event_id :: binary(), %% event_id: Unique event identifier.
    event_type :: binary(), %% event_type: The event's type/activity name.
    event_time :: binary(), %% event_time: ISO8601 timestamp the event occurred.
    attributes :: map() | undefined %% attributes: Arbitrary named event attributes.
}).

-type ocel_event() :: #ocel_event{}.

-spec new_ocel_event(map()) -> {ok, ocel_event()} | {error, {missing_field, atom()}}.
new_ocel_event(Map) ->
    case maps:is_key(event_id, Map) of
        false -> {error, {missing_field, event_id}};
        true ->
    case maps:is_key(event_type, Map) of
        false -> {error, {missing_field, event_type}};
        true ->
    case maps:is_key(event_time, Map) of
        false -> {error, {missing_field, event_time}};
        true ->
    {ok, #ocel_event{
        event_id = maps:get(event_id, Map, undefined),
        event_type = maps:get(event_type, Map, undefined),
        event_time = maps:get(event_time, Map, undefined),
        attributes = maps:get(attributes, Map, undefined)
    }}
    end
    end
    end.

%% An OCEL 2.0 object: one entity participating in the process.
-record(ocel_object, {
    object_id :: binary(), %% object_id: Unique object identifier.
    object_type :: binary(), %% object_type: The object's type.
    attributes :: map() | undefined %% attributes: Arbitrary named current attribute values (a flat snapshot, not the time-indexed history -- see bpm:ocel_attribute and bpm:object_attribute_change for per-timestamp values).
}).

-type ocel_object() :: #ocel_object{}.

-spec new_ocel_object(map()) -> {ok, ocel_object()} | {error, {missing_field, atom()}}.
new_ocel_object(Map) ->
    case maps:is_key(object_id, Map) of
        false -> {error, {missing_field, object_id}};
        true ->
    case maps:is_key(object_type, Map) of
        false -> {error, {missing_field, object_type}};
        true ->
    {ok, #ocel_object{
        object_id = maps:get(object_id, Map, undefined),
        object_type = maps:get(object_type, Map, undefined),
        attributes = maps:get(attributes, Map, undefined)
    }}
    end
    end.

%% A qualified relationship linking an event or object to an object.
-record(ocel_relationship, {
    qualifier :: binary(), %% qualifier: The relationship qualifier/role name.
    object_id :: binary() %% object_id: The related object's identifier.
}).

-type ocel_relationship() :: #ocel_relationship{}.

-spec new_ocel_relationship(map()) -> {ok, ocel_relationship()} | {error, {missing_field, atom()}}.
new_ocel_relationship(Map) ->
    case maps:is_key(qualifier, Map) of
        false -> {error, {missing_field, qualifier}};
        true ->
    case maps:is_key(object_id, Map) of
        false -> {error, {missing_field, object_id}};
        true ->
    {ok, #ocel_relationship{
        qualifier = maps:get(qualifier, Map, undefined),
        object_id = maps:get(object_id, Map, undefined)
    }}
    end
    end.

%% Admits opportunity value only with an explicit deal currency and immutable foreign-exchange basis, making forecast value comparable and replayable.
-record(opportunity_currency_contract, {
    opportunity_id :: binary(), %% opportunity_id: Required opportunity currency contract input; omission is an executable typed refusal, never an inferred approval.
    currency_code :: binary(), %% currency_code: Required opportunity currency contract input; omission is an executable typed refusal, never an inferred approval.
    fx_basis_id :: binary() %% fx_basis_id: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type opportunity_currency_contract() :: #opportunity_currency_contract{}.

-spec new_opportunity_currency_contract(map()) -> {ok, opportunity_currency_contract()} | {error, {missing_field, atom()}}.
new_opportunity_currency_contract(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(currency_code, Map) of
        false -> {error, {missing_field, currency_code}};
        true ->
    case maps:is_key(fx_basis_id, Map) of
        false -> {error, {missing_field, fx_basis_id}};
        true ->
    {ok, #opportunity_currency_contract{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        currency_code = maps:get(currency_code, Map, undefined),
        fx_basis_id = maps:get(fx_basis_id, Map, undefined)
    }}
    end
    end
    end.

%% Represents commercial value as an evidenced range rather than false point precision, enabling downside-aware qualification.
-record(opportunity_value_range, {
    opportunity_id :: binary(), %% opportunity_id: Required opportunity value range input; omission is an executable typed refusal, never an inferred approval.
    minimum_value :: binary(), %% minimum_value: Required opportunity value range input; omission is an executable typed refusal, never an inferred approval.
    maximum_value :: binary() %% maximum_value: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type opportunity_value_range() :: #opportunity_value_range{}.

-spec new_opportunity_value_range(map()) -> {ok, opportunity_value_range()} | {error, {missing_field, atom()}}.
new_opportunity_value_range(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(minimum_value, Map) of
        false -> {error, {missing_field, minimum_value}};
        true ->
    case maps:is_key(maximum_value, Map) of
        false -> {error, {missing_field, maximum_value}};
        true ->
    {ok, #opportunity_value_range{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        minimum_value = maps:get(minimum_value, Map, undefined),
        maximum_value = maps:get(maximum_value, Map, undefined)
    }}
    end
    end
    end.

%% One reusable, scored connection pattern between two OCEL types.
-record(path_schema, {
    schema_id :: binary(), %% schema_id: Unique path schema identifier.
    source_type :: binary(), %% source_type: The source event/object type name.
    target_type :: binary(), %% target_type: The target event/object type name.
    support :: integer() %% support: Observed instance count supporting this schema.
}).

-type path_schema() :: #path_schema{}.

-spec new_path_schema(map()) -> {ok, path_schema()} | {error, {missing_field, atom()}}.
new_path_schema(Map) ->
    case maps:is_key(schema_id, Map) of
        false -> {error, {missing_field, schema_id}};
        true ->
    case maps:is_key(source_type, Map) of
        false -> {error, {missing_field, source_type}};
        true ->
    case maps:is_key(target_type, Map) of
        false -> {error, {missing_field, target_type}};
        true ->
    case maps:is_key(support, Map) of
        false -> {error, {missing_field, support}};
        true ->
    {ok, #path_schema{
        schema_id = maps:get(schema_id, Map, undefined),
        source_type = maps:get(source_type, Map, undefined),
        target_type = maps:get(target_type, Map, undefined),
        support = maps:get(support, Map, undefined)
    }}
    end
    end
    end
    end.

%% A discovery query bounding source/target types and maximum schema length.
-record(path_schema_query, {
    source_type :: binary(), %% source_type: The query source type name.
    target_type :: binary(), %% target_type: The query target type name.
    max_length :: integer() %% max_length: Maximum number of hops to search.
}).

-type path_schema_query() :: #path_schema_query{}.

-spec new_path_schema_query(map()) -> {ok, path_schema_query()} | {error, {missing_field, atom()}}.
new_path_schema_query(Map) ->
    case maps:is_key(source_type, Map) of
        false -> {error, {missing_field, source_type}};
        true ->
    case maps:is_key(target_type, Map) of
        false -> {error, {missing_field, target_type}};
        true ->
    case maps:is_key(max_length, Map) of
        false -> {error, {missing_field, max_length}};
        true ->
    {ok, #path_schema_query{
        source_type = maps:get(source_type, Map, undefined),
        target_type = maps:get(target_type, Map, undefined),
        max_length = maps:get(max_length, Map, undefined)
    }}
    end
    end
    end.

%% Admits payment terms only when authorized evidence supports the cash-conversion assumption.
-record(payment_terms_admission, {
    opportunity_id :: binary(), %% opportunity_id: Required payment terms admission input; omission is an executable typed refusal, never an inferred approval.
    payment_terms :: binary(), %% payment_terms: Required payment terms admission input; omission is an executable typed refusal, never an inferred approval.
    authority_evidence_hash :: binary() %% authority_evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type payment_terms_admission() :: #payment_terms_admission{}.

-spec new_payment_terms_admission(map()) -> {ok, payment_terms_admission()} | {error, {missing_field, atom()}}.
new_payment_terms_admission(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(payment_terms, Map) of
        false -> {error, {missing_field, payment_terms}};
        true ->
    case maps:is_key(authority_evidence_hash, Map) of
        false -> {error, {missing_field, authority_evidence_hash}};
        true ->
    {ok, #payment_terms_admission{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        payment_terms = maps:get(payment_terms, Map, undefined),
        authority_evidence_hash = maps:get(authority_evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% A weighted arc connecting a place and a transition (either direction).
-record(petri_arc, {
    source_id :: binary(), %% source_id: Identifier of the arc's source node.
    target_id :: binary(), %% target_id: Identifier of the arc's target node.
    weight :: integer() %% weight: Arc weight (tokens consumed/produced per firing).
}).

-type petri_arc() :: #petri_arc{}.

-spec new_petri_arc(map()) -> {ok, petri_arc()} | {error, {missing_field, atom()}}.
new_petri_arc(Map) ->
    case maps:is_key(source_id, Map) of
        false -> {error, {missing_field, source_id}};
        true ->
    case maps:is_key(target_id, Map) of
        false -> {error, {missing_field, target_id}};
        true ->
    case maps:is_key(weight, Map) of
        false -> {error, {missing_field, weight}};
        true ->
    {ok, #petri_arc{
        source_id = maps:get(source_id, Map, undefined),
        target_id = maps:get(target_id, Map, undefined),
        weight = maps:get(weight, Map, undefined)
    }}
    end
    end
    end.

%% A place in a Petri net, holding a non-negative token count.
-record(petri_place, {
    place_id :: binary(), %% place_id: Unique place identifier.
    tokens :: integer() %% tokens: Current token count (marking) at this place.
}).

-type petri_place() :: #petri_place{}.

-spec new_petri_place(map()) -> {ok, petri_place()} | {error, {missing_field, atom()}}.
new_petri_place(Map) ->
    case maps:is_key(place_id, Map) of
        false -> {error, {missing_field, place_id}};
        true ->
    case maps:is_key(tokens, Map) of
        false -> {error, {missing_field, tokens}};
        true ->
    {ok, #petri_place{
        place_id = maps:get(place_id, Map, undefined),
        tokens = maps:get(tokens, Map, undefined)
    }}
    end
    end.

%% A transition in a Petri net.
-record(petri_transition, {
    transition_id :: binary(), %% transition_id: Unique transition identifier.
    label :: binary() | undefined %% label: Optional human-readable/activity label (silent transition if absent).
}).

-type petri_transition() :: #petri_transition{}.

-spec new_petri_transition(map()) -> {ok, petri_transition()} | {error, {missing_field, atom()}}.
new_petri_transition(Map) ->
    case maps:is_key(transition_id, Map) of
        false -> {error, {missing_field, transition_id}};
        true ->
    {ok, #petri_transition{
        transition_id = maps:get(transition_id, Map, undefined),
        label = maps:get(label, Map, undefined)
    }}
    end.

%% One PDDL-style planning action with its preconditions and effects.
-record(planning_action, {
    action_name :: binary(), %% action_name: The action name.
    preconditions :: [binary()] | undefined, %% preconditions: Optional list of precondition fact names.
    effects :: [binary()] | undefined %% effects: Optional list of effect fact names this action produces.
}).

-type planning_action() :: #planning_action{}.

-spec new_planning_action(map()) -> {ok, planning_action()} | {error, {missing_field, atom()}}.
new_planning_action(Map) ->
    case maps:is_key(action_name, Map) of
        false -> {error, {missing_field, action_name}};
        true ->
    {ok, #planning_action{
        action_name = maps:get(action_name, Map, undefined),
        preconditions = maps:get(preconditions, Map, undefined),
        effects = maps:get(effects, Map, undefined)
    }}
    end.

%% One planning-search state as a bounded set of true facts.
-record(planning_state, {
    state_id :: binary(), %% state_id: Unique state identifier.
    facts :: [binary()] %% facts: List of fact names true in this state.
}).

-type planning_state() :: #planning_state{}.

-spec new_planning_state(map()) -> {ok, planning_state()} | {error, {missing_field, atom()}}.
new_planning_state(Map) ->
    case maps:is_key(state_id, Map) of
        false -> {error, {missing_field, state_id}};
        true ->
    case maps:is_key(facts, Map) of
        false -> {error, {missing_field, facts}};
        true ->
    {ok, #planning_state{
        state_id = maps:get(state_id, Map, undefined),
        facts = maps:get(facts, Map, undefined)
    }}
    end
    end.

%% One admission/authority policy decision recorded for an attempted action.
-record(policy_decision, {
    decision_id :: binary(), %% decision_id: Unique decision identifier.
    verdict :: atom(), %% verdict: One of: admitted | refused | blocked.
    reason :: binary() | undefined %% reason: Optional human-readable reason for this verdict.
}).

-type policy_decision() :: #policy_decision{}.

-spec new_policy_decision(map()) -> {ok, policy_decision()} | {error, {missing_field, atom()}}.
new_policy_decision(Map) ->
    case maps:is_key(decision_id, Map) of
        false -> {error, {missing_field, decision_id}};
        true ->
    case maps:is_key(verdict, Map) of
        false -> {error, {missing_field, verdict}};
        true ->
    {ok, #policy_decision{
        decision_id = maps:get(decision_id, Map, undefined),
        verdict = maps:get(verdict, Map, undefined),
        reason = maps:get(reason, Map, undefined)
    }}
    end
    end.

%% One distinct activity-sequence variant observed in a log, with its frequency.
-record(process_variant, {
    variant_id :: binary(), %% variant_id: Unique variant identifier.
    activity_sequence :: [binary()], %% activity_sequence: Ordered list of activity names making up this variant.
    frequency :: integer() %% frequency: Number of traces observed with exactly this activity sequence.
}).

-type process_variant() :: #process_variant{}.

-spec new_process_variant(map()) -> {ok, process_variant()} | {error, {missing_field, atom()}}.
new_process_variant(Map) ->
    case maps:is_key(variant_id, Map) of
        false -> {error, {missing_field, variant_id}};
        true ->
    case maps:is_key(activity_sequence, Map) of
        false -> {error, {missing_field, activity_sequence}};
        true ->
    case maps:is_key(frequency, Map) of
        false -> {error, {missing_field, frequency}};
        true ->
    {ok, #process_variant{
        variant_id = maps:get(variant_id, Map, undefined),
        activity_sequence = maps:get(activity_sequence, Map, undefined),
        frequency = maps:get(frequency, Map, undefined)
    }}
    end
    end
    end.

%% Admits exactly one purchasing channel with evidence, preventing direct, marketplace, reseller, and distributor routes from conflicting.
-record(procurement_channel_selection, {
    opportunity_id :: binary(), %% opportunity_id: Required procurement channel selection input; omission is an executable typed refusal, never an inferred approval.
    channel_id :: binary(), %% channel_id: Required procurement channel selection input; omission is an executable typed refusal, never an inferred approval.
    selection_evidence_hash :: binary() %% selection_evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type procurement_channel_selection() :: #procurement_channel_selection{}.

-spec new_procurement_channel_selection(map()) -> {ok, procurement_channel_selection()} | {error, {missing_field, atom()}}.
new_procurement_channel_selection(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(channel_id, Map) of
        false -> {error, {missing_field, channel_id}};
        true ->
    case maps:is_key(selection_evidence_hash, Map) of
        false -> {error, {missing_field, selection_evidence_hash}};
        true ->
    {ok, #procurement_channel_selection{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        channel_id = maps:get(channel_id, Map, undefined),
        selection_evidence_hash = maps:get(selection_evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% Makes the buyer's purchase-order requirement explicit and evidenced before booking readiness.
-record(purchase_order_requirement, {
    opportunity_id :: binary(), %% opportunity_id: Required purchase order requirement input; omission is an executable typed refusal, never an inferred approval.
    requirement_id :: binary(), %% requirement_id: Required purchase order requirement input; omission is an executable typed refusal, never an inferred approval.
    evidence_hash :: binary() %% evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type purchase_order_requirement() :: #purchase_order_requirement{}.

-spec new_purchase_order_requirement(map()) -> {ok, purchase_order_requirement()} | {error, {missing_field, atom()}}.
new_purchase_order_requirement(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(requirement_id, Map) of
        false -> {error, {missing_field, requirement_id}};
        true ->
    case maps:is_key(evidence_hash, Map) of
        false -> {error, {missing_field, evidence_hash}};
        true ->
    {ok, #purchase_order_requirement{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        requirement_id = maps:get(requirement_id, Map, undefined),
        evidence_hash = maps:get(evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% Requires the legal entity that will issue purchasing authority before commercial progression.
-record(purchasing_entity_identity, {
    opportunity_id :: binary(), %% opportunity_id: Required purchasing entity identity input; omission is an executable typed refusal, never an inferred approval.
    purchasing_entity_id :: binary(), %% purchasing_entity_id: Required purchasing entity identity input; omission is an executable typed refusal, never an inferred approval.
    identity_evidence_hash :: binary() %% identity_evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type purchasing_entity_identity() :: #purchasing_entity_identity{}.

-spec new_purchasing_entity_identity(map()) -> {ok, purchasing_entity_identity()} | {error, {missing_field, atom()}}.
new_purchasing_entity_identity(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(purchasing_entity_id, Map) of
        false -> {error, {missing_field, purchasing_entity_id}};
        true ->
    case maps:is_key(identity_evidence_hash, Map) of
        false -> {error, {missing_field, identity_evidence_hash}};
        true ->
    {ok, #purchasing_entity_identity{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        purchasing_entity_id = maps:get(purchasing_entity_id, Map, undefined),
        identity_evidence_hash = maps:get(identity_evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% One point-in-time observation of a queue depth.
-record(queue_snapshot, {
    queue_name :: binary(), %% queue_name: Name of the observed queue.
    depth :: integer(), %% depth: Observed queue depth at this point in time.
    observed_at :: binary() %% observed_at: ISO8601 timestamp of this observation.
}).

-type queue_snapshot() :: #queue_snapshot{}.

-spec new_queue_snapshot(map()) -> {ok, queue_snapshot()} | {error, {missing_field, atom()}}.
new_queue_snapshot(Map) ->
    case maps:is_key(queue_name, Map) of
        false -> {error, {missing_field, queue_name}};
        true ->
    case maps:is_key(depth, Map) of
        false -> {error, {missing_field, depth}};
        true ->
    case maps:is_key(observed_at, Map) of
        false -> {error, {missing_field, observed_at}};
        true ->
    {ok, #queue_snapshot{
        queue_name = maps:get(queue_name, Map, undefined),
        depth = maps:get(depth, Map, undefined),
        observed_at = maps:get(observed_at, Map, undefined)
    }}
    end
    end
    end.

%% One recorded assignment of a resource to an activity occurrence.
-record(resource_allocation, {
    resource_id :: binary(), %% resource_id: Identifier of the assigned resource.
    activity :: binary(), %% activity: The activity the resource was assigned to.
    event_id :: binary() %% event_id: Identifier of the specific event occurrence.
}).

-type resource_allocation() :: #resource_allocation{}.

-spec new_resource_allocation(map()) -> {ok, resource_allocation()} | {error, {missing_field, atom()}}.
new_resource_allocation(Map) ->
    case maps:is_key(resource_id, Map) of
        false -> {error, {missing_field, resource_id}};
        true ->
    case maps:is_key(activity, Map) of
        false -> {error, {missing_field, activity}};
        true ->
    case maps:is_key(event_id, Map) of
        false -> {error, {missing_field, event_id}};
        true ->
    {ok, #resource_allocation{
        resource_id = maps:get(resource_id, Map, undefined),
        activity = maps:get(activity, Map, undefined),
        event_id = maps:get(event_id, Map, undefined)
    }}
    end
    end
    end.

%% Binds forecast revenue timing to a named schedule and evidence identity so bookings and realization assumptions can be independently challenged.
-record(revenue_schedule_assumption, {
    opportunity_id :: binary(), %% opportunity_id: Required revenue schedule assumption input; omission is an executable typed refusal, never an inferred approval.
    schedule_id :: binary(), %% schedule_id: Required revenue schedule assumption input; omission is an executable typed refusal, never an inferred approval.
    assumption_evidence_hash :: binary() %% assumption_evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type revenue_schedule_assumption() :: #revenue_schedule_assumption{}.

-spec new_revenue_schedule_assumption(map()) -> {ok, revenue_schedule_assumption()} | {error, {missing_field, atom()}}.
new_revenue_schedule_assumption(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(schedule_id, Map) of
        false -> {error, {missing_field, schedule_id}};
        true ->
    case maps:is_key(assumption_evidence_hash, Map) of
        false -> {error, {missing_field, assumption_evidence_hash}};
        true ->
    {ok, #revenue_schedule_assumption{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        schedule_id = maps:get(schedule_id, Map, undefined),
        assumption_evidence_hash = maps:get(assumption_evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% Requires a named sanctions screening result before accepting the commercial counterparty.
-record(sanctions_screening_result, {
    account_id :: binary(), %% account_id: Required sanctions screening result input; omission is an executable typed refusal, never an inferred approval.
    screening_id :: binary(), %% screening_id: Required sanctions screening result input; omission is an executable typed refusal, never an inferred approval.
    screening_result :: binary() %% screening_result: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type sanctions_screening_result() :: #sanctions_screening_result{}.

-spec new_sanctions_screening_result(map()) -> {ok, sanctions_screening_result()} | {error, {missing_field, atom()}}.
new_sanctions_screening_result(Map) ->
    case maps:is_key(account_id, Map) of
        false -> {error, {missing_field, account_id}};
        true ->
    case maps:is_key(screening_id, Map) of
        false -> {error, {missing_field, screening_id}};
        true ->
    case maps:is_key(screening_result, Map) of
        false -> {error, {missing_field, screening_result}};
        true ->
    {ok, #sanctions_screening_result{
        account_id = maps:get(account_id, Map, undefined),
        screening_id = maps:get(screening_id, Map, undefined),
        screening_result = maps:get(screening_result, Map, undefined)
    }}
    end
    end
    end.

%% Requires an identified security addendum state before promising a paid production deployment.
-record(security_addendum_state, {
    opportunity_id :: binary(), %% opportunity_id: Required security addendum state input; omission is an executable typed refusal, never an inferred approval.
    addendum_id :: binary(), %% addendum_id: Required security addendum state input; omission is an executable typed refusal, never an inferred approval.
    addendum_state :: binary() %% addendum_state: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type security_addendum_state() :: #security_addendum_state{}.

-spec new_security_addendum_state(map()) -> {ok, security_addendum_state()} | {error, {missing_field, atom()}}.
new_security_addendum_state(Map) ->
    case maps:is_key(opportunity_id, Map) of
        false -> {error, {missing_field, opportunity_id}};
        true ->
    case maps:is_key(addendum_id, Map) of
        false -> {error, {missing_field, addendum_id}};
        true ->
    case maps:is_key(addendum_state, Map) of
        false -> {error, {missing_field, addendum_state}};
        true ->
    {ok, #security_addendum_state{
        opportunity_id = maps:get(opportunity_id, Map, undefined),
        addendum_id = maps:get(addendum_id, Map, undefined),
        addendum_state = maps:get(addendum_state, Map, undefined)
    }}
    end
    end
    end.

%% One OpenTelemetry-style tracing span observed for a service call.
-record(service_span, {
    span_id :: binary(), %% span_id: Unique span identifier.
    service_name :: binary(), %% service_name: Name of the service that produced this span.
    duration_ms :: integer(), %% duration_ms: Span duration in milliseconds.
    parent_span_id :: binary() | undefined %% parent_span_id: Optional identifier of the parent span.
}).

-type service_span() :: #service_span{}.

-spec new_service_span(map()) -> {ok, service_span()} | {error, {missing_field, atom()}}.
new_service_span(Map) ->
    case maps:is_key(span_id, Map) of
        false -> {error, {missing_field, span_id}};
        true ->
    case maps:is_key(service_name, Map) of
        false -> {error, {missing_field, service_name}};
        true ->
    case maps:is_key(duration_ms, Map) of
        false -> {error, {missing_field, duration_ms}};
        true ->
    {ok, #service_span{
        span_id = maps:get(span_id, Map, undefined),
        service_name = maps:get(service_name, Map, undefined),
        duration_ms = maps:get(duration_ms, Map, undefined),
        parent_span_id = maps:get(parent_span_id, Map, undefined)
    }}
    end
    end
    end.

%% The total dwell/duration time an object was associated with one event/activity (object-centric sojourn time -- a duration metric, distinct from bpm:sync_time's wait-for-another-object metric).
-record(sojourn_time, {
    object_id :: binary(), %% object_id: Identifier of the object this measurement is for.
    event_type :: binary(), %% event_type: The event type/activity this sojourn measurement is at.
    seconds :: float() %% seconds: Sojourn duration in seconds.
}).

-type sojourn_time() :: #sojourn_time{}.

-spec new_sojourn_time(map()) -> {ok, sojourn_time()} | {error, {missing_field, atom()}}.
new_sojourn_time(Map) ->
    case maps:is_key(object_id, Map) of
        false -> {error, {missing_field, object_id}};
        true ->
    case maps:is_key(event_type, Map) of
        false -> {error, {missing_field, event_type}};
        true ->
    case maps:is_key(seconds, Map) of
        false -> {error, {missing_field, seconds}};
        true ->
    {ok, #sojourn_time{
        object_id = maps:get(object_id, Map, undefined),
        event_type = maps:get(event_type, Map, undefined),
        seconds = maps:get(seconds, Map, undefined)
    }}
    end
    end
    end.

%% The time one object waited to synchronize with another object at a shared event.
-record(sync_time, {
    object_id :: binary(), %% object_id: Identifier of the object this measurement is for.
    delaying_object_id :: binary() | undefined, %% delaying_object_id: Optional identifier of the object that caused the delay.
    seconds :: float() %% seconds: Synchronization wait duration in seconds.
}).

-type sync_time() :: #sync_time{}.

-spec new_sync_time(map()) -> {ok, sync_time()} | {error, {missing_field, atom()}}.
new_sync_time(Map) ->
    case maps:is_key(object_id, Map) of
        false -> {error, {missing_field, object_id}};
        true ->
    case maps:is_key(seconds, Map) of
        false -> {error, {missing_field, seconds}};
        true ->
    {ok, #sync_time{
        object_id = maps:get(object_id, Map, undefined),
        delaying_object_id = maps:get(delaying_object_id, Map, undefined),
        seconds = maps:get(seconds, Map, undefined)
    }}
    end
    end.

%% Binds the contracting entity to an evidenced tax jurisdiction before price and invoice admission.
-record(tax_jurisdiction_evidence, {
    contracting_entity_id :: binary(), %% contracting_entity_id: Required tax jurisdiction evidence input; omission is an executable typed refusal, never an inferred approval.
    tax_jurisdiction :: binary(), %% tax_jurisdiction: Required tax jurisdiction evidence input; omission is an executable typed refusal, never an inferred approval.
    evidence_hash :: binary() %% evidence_hash: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type tax_jurisdiction_evidence() :: #tax_jurisdiction_evidence{}.

-spec new_tax_jurisdiction_evidence(map()) -> {ok, tax_jurisdiction_evidence()} | {error, {missing_field, atom()}}.
new_tax_jurisdiction_evidence(Map) ->
    case maps:is_key(contracting_entity_id, Map) of
        false -> {error, {missing_field, contracting_entity_id}};
        true ->
    case maps:is_key(tax_jurisdiction, Map) of
        false -> {error, {missing_field, tax_jurisdiction}};
        true ->
    case maps:is_key(evidence_hash, Map) of
        false -> {error, {missing_field, evidence_hash}};
        true ->
    {ok, #tax_jurisdiction_evidence{
        contracting_entity_id = maps:get(contracting_entity_id, Map, undefined),
        tax_jurisdiction = maps:get(tax_jurisdiction, Map, undefined),
        evidence_hash = maps:get(evidence_hash, Map, undefined)
    }}
    end
    end
    end.

%% A directed, qualified edge in the OCEL type graph between two types.
-record(type_edge, {
    source_type :: binary(), %% source_type: The edge source type name.
    target_type :: binary(), %% target_type: The edge target type name.
    qualifier :: binary(), %% qualifier: The relationship qualifier/role name for this edge.
    direction :: atom() %% direction: One of: e2o | o2o.
}).

-type type_edge() :: #type_edge{}.

-spec new_type_edge(map()) -> {ok, type_edge()} | {error, {missing_field, atom()}}.
new_type_edge(Map) ->
    case maps:is_key(source_type, Map) of
        false -> {error, {missing_field, source_type}};
        true ->
    case maps:is_key(target_type, Map) of
        false -> {error, {missing_field, target_type}};
        true ->
    case maps:is_key(qualifier, Map) of
        false -> {error, {missing_field, qualifier}};
        true ->
    case maps:is_key(direction, Map) of
        false -> {error, {missing_field, direction}};
        true ->
    {ok, #type_edge{
        source_type = maps:get(source_type, Map, undefined),
        target_type = maps:get(target_type, Map, undefined),
        qualifier = maps:get(qualifier, Map, undefined),
        direction = maps:get(direction, Map, undefined)
    }}
    end
    end
    end
    end.

%% One metered usage/consumption occurrence to be billed against an entitlement. event_id is the idempotency key that is ALSO the operationId reported to the provider's usage API, so local dedup and provider-side dedup are keyed identically and can never disagree.
-record(usage_event, {
    event_id :: binary(), %% event_id: DEDUP KEY. Stable, deterministic, locally minted identifier for this metered occurrence -- and the exact value sent as operationId on the Service Control services.report call, which is the provider's own documented deduplication mechanism. It MUST be derived from the occurrence itself, never from a random UUID or a wall clock: a re-minted id on retry would defeat both local and provider-side dedup and double bill. Counting the same event_id twice in a billing_reconciliation.total_quantity is the exact MP6 failure.
    entitlement_id :: binary(), %% entitlement_id: The entitlement this usage is billed against (Partner Procurement ENTITLEMENT_ID); resolves to the provider's consumerId at report time. Usage whose entitlement_id has no reconciled entitlement_state is a typed refusal, never silently billed and never silently dropped.
    quantity :: float(), %% quantity: The measured amount for this single occurrence, in the unit implied by metric_name. Non-negative: a correction is a separate, explicitly-typed adjustment, never a negative usage_event, because negative quantities make the dedup-set sum order-sensitive at the boundaries and make a double-counted event cancellable rather than detectable.
    metric_name :: binary(), %% metric_name: The fully qualified metered dimension this occurrence counts against. Reconciliation partitions by (entitlement_id, metric_name): quantities in different metrics are never summed together.
    occurred_at :: binary() %% occurred_at: ISO8601 UTC instant the usage actually occurred (not when it was observed, queued, or reported).
}).

-type usage_event() :: #usage_event{}.

-spec new_usage_event(map()) -> {ok, usage_event()} | {error, {missing_field, atom()}}.
new_usage_event(Map) ->
    case maps:is_key(event_id, Map) of
        false -> {error, {missing_field, event_id}};
        true ->
    case maps:is_key(entitlement_id, Map) of
        false -> {error, {missing_field, entitlement_id}};
        true ->
    case maps:is_key(quantity, Map) of
        false -> {error, {missing_field, quantity}};
        true ->
    case maps:is_key(metric_name, Map) of
        false -> {error, {missing_field, metric_name}};
        true ->
    case maps:is_key(occurred_at, Map) of
        false -> {error, {missing_field, occurred_at}};
        true ->
    {ok, #usage_event{
        event_id = maps:get(event_id, Map, undefined),
        entitlement_id = maps:get(entitlement_id, Map, undefined),
        quantity = maps:get(quantity, Map, undefined),
        metric_name = maps:get(metric_name, Map, undefined),
        occurred_at = maps:get(occurred_at, Map, undefined)
    }}
    end
    end
    end
    end
    end.

%% Makes buyer vendor-registration completion an explicit revenue gate instead of an invisible procurement delay.
-record(vendor_registration_state, {
    account_id :: binary(), %% account_id: Required vendor registration state input; omission is an executable typed refusal, never an inferred approval.
    registration_id :: binary(), %% registration_id: Required vendor registration state input; omission is an executable typed refusal, never an inferred approval.
    registration_state :: binary() %% registration_state: Immutable decision or evidence identity used to verify and replay this bounded commercial admission.
}).

-type vendor_registration_state() :: #vendor_registration_state{}.

-spec new_vendor_registration_state(map()) -> {ok, vendor_registration_state()} | {error, {missing_field, atom()}}.
new_vendor_registration_state(Map) ->
    case maps:is_key(account_id, Map) of
        false -> {error, {missing_field, account_id}};
        true ->
    case maps:is_key(registration_id, Map) of
        false -> {error, {missing_field, registration_id}};
        true ->
    case maps:is_key(registration_state, Map) of
        false -> {error, {missing_field, registration_state}};
        true ->
    {ok, #vendor_registration_state{
        account_id = maps:get(account_id, Map, undefined),
        registration_id = maps:get(registration_id, Map, undefined),
        registration_state = maps:get(registration_state, Map, undefined)
    }}
    end
    end
    end.

