%% GENERATED by ggen from the admitted bpm:RecordType graph. Do not edit.
%%
%% Cross-language roundtrip sample fixtures: one deterministic sample per
%% admitted record type and variant (full | minimal), written and verified
%% through beam4pm_codec so any drift between the Erlang and Elixir codecs
%% surfaces as a real fixture mismatch, not an assumed equivalence.

-module(beam4pm_roundtrip).

-export([record_names/0, sample/2, write_samples/1, verify_samples/2]).

-type variant() :: full | minimal.

-spec record_names() -> [atom()].
record_names() ->
    [
        account_master_match,
        account_parent_scope,
        add_on_bundle,
        alignment_move,
        annual_subscription,
        beneficial_owner_evidence,
        billing_account,
        billing_reconciliation,
        booking_readiness,
        budget_period_alignment,
        capability_bundle,
        case_stats,
        catalog_release,
        change_order_authority,
        channel_agreement,
        chargeback_rule,
        commercial_approval,
        commercial_exception,
        commercial_execution_receipt,
        commercial_forecast,
        commercial_quote,
        commercial_quote_line,
        committed_spend,
        committed_spend_admission,
        compatibility_contract,
        configuration_export,
        configuration_import,
        conformance_result,
        consumption_pool,
        consumption_subscription,
        contracting_entity_identity,
        credit_risk_admission,
        data_migration_scope_admission,
        data_processing_addendum_state,
        data_residency_policy,
        deal_desk_packet,
        deployment_entitlement,
        dfg_edge,
        discount_schedule,
        edition_definition,
        enterprise_order,
        enterprise_order_line,
        entitlement_event,
        entitlement_grant,
        entitlement_revocation,
        entitlement_state,
        environment_profile,
        event_log,
        event_type,
        exception_authority,
        expansion_option,
        funding_approval_chain,
        heuristic_arc,
        implementation_fee_admission,
        indemnity_scope_admission,
        insurance_requirement,
        integration_scope_admission,
        invoice_entity_identity,
        invoice_schedule,
        k8s_object_ref,
        legal_blocker,
        liability_cap_admission,
        log_trace,
        master_service_agreement_state,
        migration_contract,
        minimum_term_admission,
        object_attribute_change,
        object_type,
        oc_declare_constraint,
        ocel_attribute,
        ocel_event,
        ocel_object,
        ocel_relationship,
        opportunity_currency_contract,
        opportunity_value_range,
        order_form_admission,
        overage_policy,
        path_schema,
        path_schema_query,
        payment_terms,
        payment_terms_admission,
        petri_arc,
        petri_place,
        petri_transition,
        planning_action,
        planning_state,
        policy_decision,
        pricing_basis_contract,
        private_offer,
        process_variant,
        procurement_blocker,
        procurement_channel_selection,
        proof_of_value_budget,
        proof_of_value_exit_gate,
        purchase_order_binding,
        purchase_order_requirement,
        purchasing_entity_identity,
        queue_snapshot,
        quota_policy,
        ramp_commitment,
        renewal_option,
        renewal_term_admission,
        reseller_authorization,
        resource_allocation,
        revenue_contract_admission,
        revenue_schedule_assumption,
        sanctions_screening_result,
        security_addendum_state,
        security_blocker,
        service_credit,
        service_credit_admission,
        service_level_objective,
        service_span,
        showback_allocation,
        sku_definition,
        sla_offer_admission,
        sojourn_time,
        support_contract,
        support_tier_admission,
        sync_time,
        tax_jurisdiction_evidence,
        technical_blocker,
        tenant_account,
        tenant_project,
        term_subscription,
        termination_right_admission,
        training_scope_admission,
        true_up_policy,
        type_edge,
        usage_event,
        usage_plan,
        value_baseline,
        value_realization,
        vendor_registration_state,
        volume_tier_admission
    ].

%% Deterministic sample values, keyed by bpm:fieldType:
%% string -> <<"sample_" field_name>>, datetime -> <<"2026-08-29T12:00:00Z">>,
%% integer -> 42, float -> 3.5, boolean -> true, atom -> sample_atom,
%% list_string -> [<<"alpha">>, <<"beta">>], map -> #{<<"k">> => <<"v">>}.
%% minimal = required fields only; full = every field.
-spec sample(atom(), variant()) -> {ok, tuple()}.
sample(account_master_match, full) ->
    beam4pm_types:new_account_master_match(#{
        source_account_id => <<"sample_source_account_id">>,
        canonical_account_id => <<"sample_canonical_account_id">>,
        match_evidence_hash => <<"sample_match_evidence_hash">>
    });
sample(account_master_match, minimal) ->
    beam4pm_types:new_account_master_match(#{
        source_account_id => <<"sample_source_account_id">>,
        canonical_account_id => <<"sample_canonical_account_id">>,
        match_evidence_hash => <<"sample_match_evidence_hash">>
    });
sample(account_parent_scope, full) ->
    beam4pm_types:new_account_parent_scope(#{
        account_id => <<"sample_account_id">>,
        parent_account_id => <<"sample_parent_account_id">>,
        scope_evidence_hash => <<"sample_scope_evidence_hash">>
    });
sample(account_parent_scope, minimal) ->
    beam4pm_types:new_account_parent_scope(#{
        account_id => <<"sample_account_id">>,
        parent_account_id => <<"sample_parent_account_id">>,
        scope_evidence_hash => <<"sample_scope_evidence_hash">>
    });
sample(add_on_bundle, full) ->
    beam4pm_types:new_add_on_bundle(#{
        add_on_id => <<"sample_add_on_id">>,
        name => <<"sample_name">>,
        capability_ids => [<<"alpha">>, <<"beta">>],
        status => sample_atom
    });
sample(add_on_bundle, minimal) ->
    beam4pm_types:new_add_on_bundle(#{
        add_on_id => <<"sample_add_on_id">>,
        name => <<"sample_name">>,
        capability_ids => [<<"alpha">>, <<"beta">>],
        status => sample_atom
    });
sample(alignment_move, full) ->
    beam4pm_types:new_alignment_move(#{
        move_type => sample_atom,
        cost => 42
    });
sample(alignment_move, minimal) ->
    beam4pm_types:new_alignment_move(#{
        move_type => sample_atom,
        cost => 42
    });
sample(annual_subscription, full) ->
    beam4pm_types:new_annual_subscription(#{
        subscription_id => <<"sample_subscription_id">>,
        sku => <<"sample_sku">>,
        seat_count => 42,
        renews_at => <<"2026-08-29T12:00:00Z">>
    });
sample(annual_subscription, minimal) ->
    beam4pm_types:new_annual_subscription(#{
        subscription_id => <<"sample_subscription_id">>,
        sku => <<"sample_sku">>,
        seat_count => 42,
        renews_at => <<"2026-08-29T12:00:00Z">>
    });
sample(beneficial_owner_evidence, full) ->
    beam4pm_types:new_beneficial_owner_evidence(#{
        account_id => <<"sample_account_id">>,
        owner_id => <<"sample_owner_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(beneficial_owner_evidence, minimal) ->
    beam4pm_types:new_beneficial_owner_evidence(#{
        account_id => <<"sample_account_id">>,
        owner_id => <<"sample_owner_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(billing_account, full) ->
    beam4pm_types:new_billing_account(#{
        billing_account_id => <<"sample_billing_account_id">>,
        account_id => <<"sample_account_id">>,
        currency => <<"sample_currency">>,
        invoice_profile => <<"sample_invoice_profile">>
    });
sample(billing_account, minimal) ->
    beam4pm_types:new_billing_account(#{
        billing_account_id => <<"sample_billing_account_id">>,
        account_id => <<"sample_account_id">>,
        currency => <<"sample_currency">>,
        invoice_profile => <<"sample_invoice_profile">>
    });
sample(billing_reconciliation, full) ->
    beam4pm_types:new_billing_reconciliation(#{
        entitlement_id => <<"sample_entitlement_id">>,
        metric_name => <<"sample_metric_name">>,
        total_quantity => 3.5,
        applied_event_ids => [<<"alpha">>, <<"beta">>],
        period_start => <<"2026-08-29T12:00:00Z">>,
        period_end => <<"2026-08-29T12:00:00Z">>
    });
sample(billing_reconciliation, minimal) ->
    beam4pm_types:new_billing_reconciliation(#{
        entitlement_id => <<"sample_entitlement_id">>,
        metric_name => <<"sample_metric_name">>,
        total_quantity => 3.5,
        applied_event_ids => [<<"alpha">>, <<"beta">>],
        period_start => <<"2026-08-29T12:00:00Z">>,
        period_end => <<"2026-08-29T12:00:00Z">>
    });
sample(booking_readiness, full) ->
    beam4pm_types:new_booking_readiness(#{
        opportunity_id => <<"sample_opportunity_id">>,
        readiness_id => <<"sample_readiness_id">>,
        decision => <<"sample_decision">>
    });
sample(booking_readiness, minimal) ->
    beam4pm_types:new_booking_readiness(#{
        opportunity_id => <<"sample_opportunity_id">>,
        readiness_id => <<"sample_readiness_id">>,
        decision => <<"sample_decision">>
    });
sample(budget_period_alignment, full) ->
    beam4pm_types:new_budget_period_alignment(#{
        opportunity_id => <<"sample_opportunity_id">>,
        budget_period => <<"sample_budget_period">>,
        alignment_result => <<"sample_alignment_result">>
    });
sample(budget_period_alignment, minimal) ->
    beam4pm_types:new_budget_period_alignment(#{
        opportunity_id => <<"sample_opportunity_id">>,
        budget_period => <<"sample_budget_period">>,
        alignment_result => <<"sample_alignment_result">>
    });
sample(capability_bundle, full) ->
    beam4pm_types:new_capability_bundle(#{
        bundle_id => <<"sample_bundle_id">>,
        name => <<"sample_name">>,
        capability_ids => [<<"alpha">>, <<"beta">>],
        version => <<"sample_version">>
    });
sample(capability_bundle, minimal) ->
    beam4pm_types:new_capability_bundle(#{
        bundle_id => <<"sample_bundle_id">>,
        name => <<"sample_name">>,
        capability_ids => [<<"alpha">>, <<"beta">>],
        version => <<"sample_version">>
    });
sample(case_stats, full) ->
    beam4pm_types:new_case_stats(#{
        case_id => <<"sample_case_id">>,
        event_count => 42,
        duration_seconds => 3.5
    });
sample(case_stats, minimal) ->
    beam4pm_types:new_case_stats(#{
        case_id => <<"sample_case_id">>,
        event_count => 42
    });
sample(catalog_release, full) ->
    beam4pm_types:new_catalog_release(#{
        release_id => <<"sample_release_id">>,
        version => <<"sample_version">>,
        sku_ids => [<<"alpha">>, <<"beta">>],
        effective_at => <<"2026-08-29T12:00:00Z">>
    });
sample(catalog_release, minimal) ->
    beam4pm_types:new_catalog_release(#{
        release_id => <<"sample_release_id">>,
        version => <<"sample_version">>,
        sku_ids => [<<"alpha">>, <<"beta">>],
        effective_at => <<"2026-08-29T12:00:00Z">>
    });
sample(change_order_authority, full) ->
    beam4pm_types:new_change_order_authority(#{
        opportunity_id => <<"sample_opportunity_id">>,
        authority_id => <<"sample_authority_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(change_order_authority, minimal) ->
    beam4pm_types:new_change_order_authority(#{
        opportunity_id => <<"sample_opportunity_id">>,
        authority_id => <<"sample_authority_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(channel_agreement, full) ->
    beam4pm_types:new_channel_agreement(#{
        agreement_id => <<"sample_agreement_id">>,
        partner_id => <<"sample_partner_id">>,
        territory => <<"sample_territory">>,
        valid_until => <<"2026-08-29T12:00:00Z">>
    });
sample(channel_agreement, minimal) ->
    beam4pm_types:new_channel_agreement(#{
        agreement_id => <<"sample_agreement_id">>,
        partner_id => <<"sample_partner_id">>,
        territory => <<"sample_territory">>,
        valid_until => <<"2026-08-29T12:00:00Z">>
    });
sample(chargeback_rule, full) ->
    beam4pm_types:new_chargeback_rule(#{
        rule_id => <<"sample_rule_id">>,
        cost_center => <<"sample_cost_center">>,
        metric_name => <<"sample_metric_name">>,
        rate => 3.5
    });
sample(chargeback_rule, minimal) ->
    beam4pm_types:new_chargeback_rule(#{
        rule_id => <<"sample_rule_id">>,
        cost_center => <<"sample_cost_center">>,
        metric_name => <<"sample_metric_name">>,
        rate => 3.5
    });
sample(commercial_approval, full) ->
    beam4pm_types:new_commercial_approval(#{
        approval_id => <<"sample_approval_id">>,
        quote_id => <<"sample_quote_id">>,
        authority => <<"sample_authority">>,
        status => sample_atom
    });
sample(commercial_approval, minimal) ->
    beam4pm_types:new_commercial_approval(#{
        approval_id => <<"sample_approval_id">>,
        quote_id => <<"sample_quote_id">>,
        authority => <<"sample_authority">>,
        status => sample_atom
    });
sample(commercial_exception, full) ->
    beam4pm_types:new_commercial_exception(#{
        opportunity_id => <<"sample_opportunity_id">>,
        exception_id => <<"sample_exception_id">>,
        exception_state => <<"sample_exception_state">>
    });
sample(commercial_exception, minimal) ->
    beam4pm_types:new_commercial_exception(#{
        opportunity_id => <<"sample_opportunity_id">>,
        exception_id => <<"sample_exception_id">>,
        exception_state => <<"sample_exception_state">>
    });
sample(commercial_execution_receipt, full) ->
    beam4pm_types:new_commercial_execution_receipt(#{
        receipt_id => <<"sample_receipt_id">>,
        subject_id => <<"sample_subject_id">>,
        operation => <<"sample_operation">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(commercial_execution_receipt, minimal) ->
    beam4pm_types:new_commercial_execution_receipt(#{
        receipt_id => <<"sample_receipt_id">>,
        subject_id => <<"sample_subject_id">>,
        operation => <<"sample_operation">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(commercial_forecast, full) ->
    beam4pm_types:new_commercial_forecast(#{
        forecast_id => <<"sample_forecast_id">>,
        account_id => <<"sample_account_id">>,
        amount => 3.5,
        confidence => 3.5
    });
sample(commercial_forecast, minimal) ->
    beam4pm_types:new_commercial_forecast(#{
        forecast_id => <<"sample_forecast_id">>,
        account_id => <<"sample_account_id">>,
        amount => 3.5,
        confidence => 3.5
    });
sample(commercial_quote, full) ->
    beam4pm_types:new_commercial_quote(#{
        quote_id => <<"sample_quote_id">>,
        account_id => <<"sample_account_id">>,
        currency => <<"sample_currency">>,
        status => sample_atom
    });
sample(commercial_quote, minimal) ->
    beam4pm_types:new_commercial_quote(#{
        quote_id => <<"sample_quote_id">>,
        account_id => <<"sample_account_id">>,
        currency => <<"sample_currency">>,
        status => sample_atom
    });
sample(commercial_quote_line, full) ->
    beam4pm_types:new_commercial_quote_line(#{
        quote_id => <<"sample_quote_id">>,
        sku => <<"sample_sku">>,
        quantity => 42,
        unit_price => 3.5
    });
sample(commercial_quote_line, minimal) ->
    beam4pm_types:new_commercial_quote_line(#{
        quote_id => <<"sample_quote_id">>,
        sku => <<"sample_sku">>,
        quantity => 42,
        unit_price => 3.5
    });
sample(committed_spend, full) ->
    beam4pm_types:new_committed_spend(#{
        commitment_id => <<"sample_commitment_id">>,
        amount => 3.5,
        currency => <<"sample_currency">>,
        expires_at => <<"2026-08-29T12:00:00Z">>
    });
sample(committed_spend, minimal) ->
    beam4pm_types:new_committed_spend(#{
        commitment_id => <<"sample_commitment_id">>,
        amount => 3.5,
        currency => <<"sample_currency">>,
        expires_at => <<"2026-08-29T12:00:00Z">>
    });
sample(committed_spend_admission, full) ->
    beam4pm_types:new_committed_spend_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        commitment_id => <<"sample_commitment_id">>,
        decision => <<"sample_decision">>
    });
sample(committed_spend_admission, minimal) ->
    beam4pm_types:new_committed_spend_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        commitment_id => <<"sample_commitment_id">>,
        decision => <<"sample_decision">>
    });
sample(compatibility_contract, full) ->
    beam4pm_types:new_compatibility_contract(#{
        contract_id => <<"sample_contract_id">>,
        product_version => <<"sample_product_version">>,
        schema_version => <<"sample_schema_version">>,
        api_version => <<"sample_api_version">>
    });
sample(compatibility_contract, minimal) ->
    beam4pm_types:new_compatibility_contract(#{
        contract_id => <<"sample_contract_id">>,
        product_version => <<"sample_product_version">>,
        schema_version => <<"sample_schema_version">>,
        api_version => <<"sample_api_version">>
    });
sample(configuration_export, full) ->
    beam4pm_types:new_configuration_export(#{
        export_id => <<"sample_export_id">>,
        tenant_id => <<"sample_tenant_id">>,
        configuration_hash => <<"sample_configuration_hash">>,
        exported_at => <<"2026-08-29T12:00:00Z">>
    });
sample(configuration_export, minimal) ->
    beam4pm_types:new_configuration_export(#{
        export_id => <<"sample_export_id">>,
        tenant_id => <<"sample_tenant_id">>,
        configuration_hash => <<"sample_configuration_hash">>,
        exported_at => <<"2026-08-29T12:00:00Z">>
    });
sample(configuration_import, full) ->
    beam4pm_types:new_configuration_import(#{
        import_id => <<"sample_import_id">>,
        tenant_id => <<"sample_tenant_id">>,
        configuration_hash => <<"sample_configuration_hash">>,
        status => sample_atom
    });
sample(configuration_import, minimal) ->
    beam4pm_types:new_configuration_import(#{
        import_id => <<"sample_import_id">>,
        tenant_id => <<"sample_tenant_id">>,
        configuration_hash => <<"sample_configuration_hash">>,
        status => sample_atom
    });
sample(conformance_result, full) ->
    beam4pm_types:new_conformance_result(#{
        trace_id => <<"sample_trace_id">>,
        fitness => 3.5,
        precision => 3.5
    });
sample(conformance_result, minimal) ->
    beam4pm_types:new_conformance_result(#{
        trace_id => <<"sample_trace_id">>,
        fitness => 3.5
    });
sample(consumption_pool, full) ->
    beam4pm_types:new_consumption_pool(#{
        pool_id => <<"sample_pool_id">>,
        account_id => <<"sample_account_id">>,
        unit => <<"sample_unit">>,
        remaining_quantity => 3.5
    });
sample(consumption_pool, minimal) ->
    beam4pm_types:new_consumption_pool(#{
        pool_id => <<"sample_pool_id">>,
        account_id => <<"sample_account_id">>,
        unit => <<"sample_unit">>,
        remaining_quantity => 3.5
    });
sample(consumption_subscription, full) ->
    beam4pm_types:new_consumption_subscription(#{
        subscription_id => <<"sample_subscription_id">>,
        account_id => <<"sample_account_id">>,
        plan_id => <<"sample_plan_id">>,
        status => sample_atom
    });
sample(consumption_subscription, minimal) ->
    beam4pm_types:new_consumption_subscription(#{
        subscription_id => <<"sample_subscription_id">>,
        account_id => <<"sample_account_id">>,
        plan_id => <<"sample_plan_id">>,
        status => sample_atom
    });
sample(contracting_entity_identity, full) ->
    beam4pm_types:new_contracting_entity_identity(#{
        opportunity_id => <<"sample_opportunity_id">>,
        contracting_entity_id => <<"sample_contracting_entity_id">>,
        identity_evidence_hash => <<"sample_identity_evidence_hash">>
    });
sample(contracting_entity_identity, minimal) ->
    beam4pm_types:new_contracting_entity_identity(#{
        opportunity_id => <<"sample_opportunity_id">>,
        contracting_entity_id => <<"sample_contracting_entity_id">>,
        identity_evidence_hash => <<"sample_identity_evidence_hash">>
    });
sample(credit_risk_admission, full) ->
    beam4pm_types:new_credit_risk_admission(#{
        account_id => <<"sample_account_id">>,
        risk_band => <<"sample_risk_band">>,
        decision => <<"sample_decision">>
    });
sample(credit_risk_admission, minimal) ->
    beam4pm_types:new_credit_risk_admission(#{
        account_id => <<"sample_account_id">>,
        risk_band => <<"sample_risk_band">>,
        decision => <<"sample_decision">>
    });
sample(data_migration_scope_admission, full) ->
    beam4pm_types:new_data_migration_scope_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        migration_scope_id => <<"sample_migration_scope_id">>,
        decision => <<"sample_decision">>
    });
sample(data_migration_scope_admission, minimal) ->
    beam4pm_types:new_data_migration_scope_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        migration_scope_id => <<"sample_migration_scope_id">>,
        decision => <<"sample_decision">>
    });
sample(data_processing_addendum_state, full) ->
    beam4pm_types:new_data_processing_addendum_state(#{
        opportunity_id => <<"sample_opportunity_id">>,
        addendum_id => <<"sample_addendum_id">>,
        addendum_state => <<"sample_addendum_state">>
    });
sample(data_processing_addendum_state, minimal) ->
    beam4pm_types:new_data_processing_addendum_state(#{
        opportunity_id => <<"sample_opportunity_id">>,
        addendum_id => <<"sample_addendum_id">>,
        addendum_state => <<"sample_addendum_state">>
    });
sample(data_residency_policy, full) ->
    beam4pm_types:new_data_residency_policy(#{
        policy_id => <<"sample_policy_id">>,
        tenant_id => <<"sample_tenant_id">>,
        allowed_regions => [<<"alpha">>, <<"beta">>],
        status => sample_atom
    });
sample(data_residency_policy, minimal) ->
    beam4pm_types:new_data_residency_policy(#{
        policy_id => <<"sample_policy_id">>,
        tenant_id => <<"sample_tenant_id">>,
        allowed_regions => [<<"alpha">>, <<"beta">>],
        status => sample_atom
    });
sample(deal_desk_packet, full) ->
    beam4pm_types:new_deal_desk_packet(#{
        opportunity_id => <<"sample_opportunity_id">>,
        packet_id => <<"sample_packet_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(deal_desk_packet, minimal) ->
    beam4pm_types:new_deal_desk_packet(#{
        opportunity_id => <<"sample_opportunity_id">>,
        packet_id => <<"sample_packet_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(deployment_entitlement, full) ->
    beam4pm_types:new_deployment_entitlement(#{
        entitlement_id => <<"sample_entitlement_id">>,
        tenant_id => <<"sample_tenant_id">>,
        profile_id => <<"sample_profile_id">>,
        valid_until => <<"2026-08-29T12:00:00Z">>
    });
sample(deployment_entitlement, minimal) ->
    beam4pm_types:new_deployment_entitlement(#{
        entitlement_id => <<"sample_entitlement_id">>,
        tenant_id => <<"sample_tenant_id">>,
        profile_id => <<"sample_profile_id">>,
        valid_until => <<"2026-08-29T12:00:00Z">>
    });
sample(dfg_edge, full) ->
    beam4pm_types:new_dfg_edge(#{
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        frequency => 42
    });
sample(dfg_edge, minimal) ->
    beam4pm_types:new_dfg_edge(#{
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        frequency => 42
    });
sample(discount_schedule, full) ->
    beam4pm_types:new_discount_schedule(#{
        schedule_id => <<"sample_schedule_id">>,
        threshold => 3.5,
        discount_percent => 3.5,
        currency => <<"sample_currency">>
    });
sample(discount_schedule, minimal) ->
    beam4pm_types:new_discount_schedule(#{
        schedule_id => <<"sample_schedule_id">>,
        threshold => 3.5,
        discount_percent => 3.5,
        currency => <<"sample_currency">>
    });
sample(edition_definition, full) ->
    beam4pm_types:new_edition_definition(#{
        edition_id => <<"sample_edition_id">>,
        name => <<"sample_name">>,
        bundle_ids => [<<"alpha">>, <<"beta">>],
        support_tier => <<"sample_support_tier">>
    });
sample(edition_definition, minimal) ->
    beam4pm_types:new_edition_definition(#{
        edition_id => <<"sample_edition_id">>,
        name => <<"sample_name">>,
        bundle_ids => [<<"alpha">>, <<"beta">>],
        support_tier => <<"sample_support_tier">>
    });
sample(enterprise_order, full) ->
    beam4pm_types:new_enterprise_order(#{
        order_id => <<"sample_order_id">>,
        account_id => <<"sample_account_id">>,
        quote_id => <<"sample_quote_id">>,
        status => sample_atom
    });
sample(enterprise_order, minimal) ->
    beam4pm_types:new_enterprise_order(#{
        order_id => <<"sample_order_id">>,
        account_id => <<"sample_account_id">>,
        quote_id => <<"sample_quote_id">>,
        status => sample_atom
    });
sample(enterprise_order_line, full) ->
    beam4pm_types:new_enterprise_order_line(#{
        order_id => <<"sample_order_id">>,
        sku => <<"sample_sku">>,
        quantity => 42,
        unit_price => 3.5
    });
sample(enterprise_order_line, minimal) ->
    beam4pm_types:new_enterprise_order_line(#{
        order_id => <<"sample_order_id">>,
        sku => <<"sample_sku">>,
        quantity => 42,
        unit_price => 3.5
    });
sample(entitlement_event, full) ->
    beam4pm_types:new_entitlement_event(#{
        event_id => <<"sample_event_id">>,
        entitlement_id => <<"sample_entitlement_id">>,
        event_type => <<"sample_event_type">>,
        effective_at => <<"2026-08-29T12:00:00Z">>,
        payload => #{<<"k">> => <<"v">>}
    });
sample(entitlement_event, minimal) ->
    beam4pm_types:new_entitlement_event(#{
        event_id => <<"sample_event_id">>,
        entitlement_id => <<"sample_entitlement_id">>,
        event_type => <<"sample_event_type">>,
        effective_at => <<"2026-08-29T12:00:00Z">>
    });
sample(entitlement_grant, full) ->
    beam4pm_types:new_entitlement_grant(#{
        grant_id => <<"sample_grant_id">>,
        tenant_id => <<"sample_tenant_id">>,
        capability_id => <<"sample_capability_id">>,
        valid_until => <<"2026-08-29T12:00:00Z">>
    });
sample(entitlement_grant, minimal) ->
    beam4pm_types:new_entitlement_grant(#{
        grant_id => <<"sample_grant_id">>,
        tenant_id => <<"sample_tenant_id">>,
        capability_id => <<"sample_capability_id">>,
        valid_until => <<"2026-08-29T12:00:00Z">>
    });
sample(entitlement_revocation, full) ->
    beam4pm_types:new_entitlement_revocation(#{
        revocation_id => <<"sample_revocation_id">>,
        grant_id => <<"sample_grant_id">>,
        reason => <<"sample_reason">>,
        revoked_at => <<"2026-08-29T12:00:00Z">>
    });
sample(entitlement_revocation, minimal) ->
    beam4pm_types:new_entitlement_revocation(#{
        revocation_id => <<"sample_revocation_id">>,
        grant_id => <<"sample_grant_id">>,
        reason => <<"sample_reason">>,
        revoked_at => <<"2026-08-29T12:00:00Z">>
    });
sample(entitlement_state, full) ->
    beam4pm_types:new_entitlement_state(#{
        entitlement_id => <<"sample_entitlement_id">>,
        status => <<"sample_status">>,
        last_applied_event_id => <<"sample_last_applied_event_id">>,
        updated_at => <<"2026-08-29T12:00:00Z">>
    });
sample(entitlement_state, minimal) ->
    beam4pm_types:new_entitlement_state(#{
        entitlement_id => <<"sample_entitlement_id">>,
        status => <<"sample_status">>,
        last_applied_event_id => <<"sample_last_applied_event_id">>,
        updated_at => <<"2026-08-29T12:00:00Z">>
    });
sample(environment_profile, full) ->
    beam4pm_types:new_environment_profile(#{
        profile_id => <<"sample_profile_id">>,
        environment => sample_atom,
        region => <<"sample_region">>,
        configuration_hash => <<"sample_configuration_hash">>
    });
sample(environment_profile, minimal) ->
    beam4pm_types:new_environment_profile(#{
        profile_id => <<"sample_profile_id">>,
        environment => sample_atom,
        region => <<"sample_region">>,
        configuration_hash => <<"sample_configuration_hash">>
    });
sample(event_log, full) ->
    beam4pm_types:new_event_log(#{
        log_id => <<"sample_log_id">>,
        name => <<"sample_name">>,
        description => <<"sample_description">>
    });
sample(event_log, minimal) ->
    beam4pm_types:new_event_log(#{
        log_id => <<"sample_log_id">>,
        name => <<"sample_name">>
    });
sample(event_type, full) ->
    beam4pm_types:new_event_type(#{
        type_name => <<"sample_type_name">>,
        attribute_names => [<<"alpha">>, <<"beta">>]
    });
sample(event_type, minimal) ->
    beam4pm_types:new_event_type(#{
        type_name => <<"sample_type_name">>
    });
sample(exception_authority, full) ->
    beam4pm_types:new_exception_authority(#{
        exception_id => <<"sample_exception_id">>,
        authority_id => <<"sample_authority_id">>,
        decision => <<"sample_decision">>
    });
sample(exception_authority, minimal) ->
    beam4pm_types:new_exception_authority(#{
        exception_id => <<"sample_exception_id">>,
        authority_id => <<"sample_authority_id">>,
        decision => <<"sample_decision">>
    });
sample(expansion_option, full) ->
    beam4pm_types:new_expansion_option(#{
        option_id => <<"sample_option_id">>,
        account_id => <<"sample_account_id">>,
        sku => <<"sample_sku">>,
        max_quantity => 42
    });
sample(expansion_option, minimal) ->
    beam4pm_types:new_expansion_option(#{
        option_id => <<"sample_option_id">>,
        account_id => <<"sample_account_id">>,
        sku => <<"sample_sku">>,
        max_quantity => 42
    });
sample(funding_approval_chain, full) ->
    beam4pm_types:new_funding_approval_chain(#{
        opportunity_id => <<"sample_opportunity_id">>,
        approval_chain_id => <<"sample_approval_chain_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(funding_approval_chain, minimal) ->
    beam4pm_types:new_funding_approval_chain(#{
        opportunity_id => <<"sample_opportunity_id">>,
        approval_chain_id => <<"sample_approval_chain_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(heuristic_arc, full) ->
    beam4pm_types:new_heuristic_arc(#{
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        dependency_measure => 3.5
    });
sample(heuristic_arc, minimal) ->
    beam4pm_types:new_heuristic_arc(#{
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        dependency_measure => 3.5
    });
sample(implementation_fee_admission, full) ->
    beam4pm_types:new_implementation_fee_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        fee_id => <<"sample_fee_id">>,
        decision => <<"sample_decision">>
    });
sample(implementation_fee_admission, minimal) ->
    beam4pm_types:new_implementation_fee_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        fee_id => <<"sample_fee_id">>,
        decision => <<"sample_decision">>
    });
sample(indemnity_scope_admission, full) ->
    beam4pm_types:new_indemnity_scope_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        indemnity_scope_id => <<"sample_indemnity_scope_id">>,
        decision => <<"sample_decision">>
    });
sample(indemnity_scope_admission, minimal) ->
    beam4pm_types:new_indemnity_scope_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        indemnity_scope_id => <<"sample_indemnity_scope_id">>,
        decision => <<"sample_decision">>
    });
sample(insurance_requirement, full) ->
    beam4pm_types:new_insurance_requirement(#{
        opportunity_id => <<"sample_opportunity_id">>,
        coverage_id => <<"sample_coverage_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(insurance_requirement, minimal) ->
    beam4pm_types:new_insurance_requirement(#{
        opportunity_id => <<"sample_opportunity_id">>,
        coverage_id => <<"sample_coverage_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(integration_scope_admission, full) ->
    beam4pm_types:new_integration_scope_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        integration_scope_id => <<"sample_integration_scope_id">>,
        decision => <<"sample_decision">>
    });
sample(integration_scope_admission, minimal) ->
    beam4pm_types:new_integration_scope_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        integration_scope_id => <<"sample_integration_scope_id">>,
        decision => <<"sample_decision">>
    });
sample(invoice_entity_identity, full) ->
    beam4pm_types:new_invoice_entity_identity(#{
        opportunity_id => <<"sample_opportunity_id">>,
        invoice_entity_id => <<"sample_invoice_entity_id">>,
        identity_evidence_hash => <<"sample_identity_evidence_hash">>
    });
sample(invoice_entity_identity, minimal) ->
    beam4pm_types:new_invoice_entity_identity(#{
        opportunity_id => <<"sample_opportunity_id">>,
        invoice_entity_id => <<"sample_invoice_entity_id">>,
        identity_evidence_hash => <<"sample_identity_evidence_hash">>
    });
sample(invoice_schedule, full) ->
    beam4pm_types:new_invoice_schedule(#{
        schedule_id => <<"sample_schedule_id">>,
        billing_account_id => <<"sample_billing_account_id">>,
        cadence => sample_atom,
        next_invoice_at => <<"2026-08-29T12:00:00Z">>
    });
sample(invoice_schedule, minimal) ->
    beam4pm_types:new_invoice_schedule(#{
        schedule_id => <<"sample_schedule_id">>,
        billing_account_id => <<"sample_billing_account_id">>,
        cadence => sample_atom,
        next_invoice_at => <<"2026-08-29T12:00:00Z">>
    });
sample(k8s_object_ref, full) ->
    beam4pm_types:new_k8s_object_ref(#{
        kind => <<"sample_kind">>,
        name => <<"sample_name">>,
        namespace => <<"sample_namespace">>
    });
sample(k8s_object_ref, minimal) ->
    beam4pm_types:new_k8s_object_ref(#{
        kind => <<"sample_kind">>,
        name => <<"sample_name">>
    });
sample(legal_blocker, full) ->
    beam4pm_types:new_legal_blocker(#{
        opportunity_id => <<"sample_opportunity_id">>,
        blocker_id => <<"sample_blocker_id">>,
        refusal_code => <<"sample_refusal_code">>
    });
sample(legal_blocker, minimal) ->
    beam4pm_types:new_legal_blocker(#{
        opportunity_id => <<"sample_opportunity_id">>,
        blocker_id => <<"sample_blocker_id">>,
        refusal_code => <<"sample_refusal_code">>
    });
sample(liability_cap_admission, full) ->
    beam4pm_types:new_liability_cap_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        liability_cap_id => <<"sample_liability_cap_id">>,
        decision => <<"sample_decision">>
    });
sample(liability_cap_admission, minimal) ->
    beam4pm_types:new_liability_cap_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        liability_cap_id => <<"sample_liability_cap_id">>,
        decision => <<"sample_decision">>
    });
sample(log_trace, full) ->
    beam4pm_types:new_log_trace(#{
        case_id => <<"sample_case_id">>,
        activity_sequence => [<<"alpha">>, <<"beta">>]
    });
sample(log_trace, minimal) ->
    beam4pm_types:new_log_trace(#{
        case_id => <<"sample_case_id">>,
        activity_sequence => [<<"alpha">>, <<"beta">>]
    });
sample(master_service_agreement_state, full) ->
    beam4pm_types:new_master_service_agreement_state(#{
        opportunity_id => <<"sample_opportunity_id">>,
        agreement_id => <<"sample_agreement_id">>,
        agreement_state => <<"sample_agreement_state">>
    });
sample(master_service_agreement_state, minimal) ->
    beam4pm_types:new_master_service_agreement_state(#{
        opportunity_id => <<"sample_opportunity_id">>,
        agreement_id => <<"sample_agreement_id">>,
        agreement_state => <<"sample_agreement_state">>
    });
sample(migration_contract, full) ->
    beam4pm_types:new_migration_contract(#{
        migration_id => <<"sample_migration_id">>,
        from_version => <<"sample_from_version">>,
        to_version => <<"sample_to_version">>,
        rollback_plan => <<"sample_rollback_plan">>
    });
sample(migration_contract, minimal) ->
    beam4pm_types:new_migration_contract(#{
        migration_id => <<"sample_migration_id">>,
        from_version => <<"sample_from_version">>,
        to_version => <<"sample_to_version">>,
        rollback_plan => <<"sample_rollback_plan">>
    });
sample(minimum_term_admission, full) ->
    beam4pm_types:new_minimum_term_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        minimum_term => <<"sample_minimum_term">>,
        decision => <<"sample_decision">>
    });
sample(minimum_term_admission, minimal) ->
    beam4pm_types:new_minimum_term_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        minimum_term => <<"sample_minimum_term">>,
        decision => <<"sample_decision">>
    });
sample(object_attribute_change, full) ->
    beam4pm_types:new_object_attribute_change(#{
        object_id => <<"sample_object_id">>,
        attribute_name => <<"sample_attribute_name">>,
        old_value => <<"sample_old_value">>,
        new_value => <<"sample_new_value">>,
        changed_at => <<"2026-08-29T12:00:00Z">>
    });
sample(object_attribute_change, minimal) ->
    beam4pm_types:new_object_attribute_change(#{
        object_id => <<"sample_object_id">>,
        attribute_name => <<"sample_attribute_name">>,
        new_value => <<"sample_new_value">>,
        changed_at => <<"2026-08-29T12:00:00Z">>
    });
sample(object_type, full) ->
    beam4pm_types:new_object_type(#{
        type_name => <<"sample_type_name">>,
        attribute_names => [<<"alpha">>, <<"beta">>]
    });
sample(object_type, minimal) ->
    beam4pm_types:new_object_type(#{
        type_name => <<"sample_type_name">>
    });
sample(oc_declare_constraint, full) ->
    beam4pm_types:new_oc_declare_constraint(#{
        constraint_id => <<"sample_constraint_id">>,
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        constraint_type => sample_atom
    });
sample(oc_declare_constraint, minimal) ->
    beam4pm_types:new_oc_declare_constraint(#{
        constraint_id => <<"sample_constraint_id">>,
        source_activity => <<"sample_source_activity">>,
        target_activity => <<"sample_target_activity">>,
        constraint_type => sample_atom
    });
sample(ocel_attribute, full) ->
    beam4pm_types:new_ocel_attribute(#{
        attribute_name => <<"sample_attribute_name">>,
        attribute_value => <<"sample_attribute_value">>,
        recorded_at => <<"2026-08-29T12:00:00Z">>
    });
sample(ocel_attribute, minimal) ->
    beam4pm_types:new_ocel_attribute(#{
        attribute_name => <<"sample_attribute_name">>,
        attribute_value => <<"sample_attribute_value">>
    });
sample(ocel_event, full) ->
    beam4pm_types:new_ocel_event(#{
        event_id => <<"sample_event_id">>,
        event_type => <<"sample_event_type">>,
        event_time => <<"2026-08-29T12:00:00Z">>,
        attributes => #{<<"k">> => <<"v">>}
    });
sample(ocel_event, minimal) ->
    beam4pm_types:new_ocel_event(#{
        event_id => <<"sample_event_id">>,
        event_type => <<"sample_event_type">>,
        event_time => <<"2026-08-29T12:00:00Z">>
    });
sample(ocel_object, full) ->
    beam4pm_types:new_ocel_object(#{
        object_id => <<"sample_object_id">>,
        object_type => <<"sample_object_type">>,
        attributes => #{<<"k">> => <<"v">>}
    });
sample(ocel_object, minimal) ->
    beam4pm_types:new_ocel_object(#{
        object_id => <<"sample_object_id">>,
        object_type => <<"sample_object_type">>
    });
sample(ocel_relationship, full) ->
    beam4pm_types:new_ocel_relationship(#{
        qualifier => <<"sample_qualifier">>,
        object_id => <<"sample_object_id">>
    });
sample(ocel_relationship, minimal) ->
    beam4pm_types:new_ocel_relationship(#{
        qualifier => <<"sample_qualifier">>,
        object_id => <<"sample_object_id">>
    });
sample(opportunity_currency_contract, full) ->
    beam4pm_types:new_opportunity_currency_contract(#{
        opportunity_id => <<"sample_opportunity_id">>,
        currency_code => <<"sample_currency_code">>,
        fx_basis_id => <<"sample_fx_basis_id">>
    });
sample(opportunity_currency_contract, minimal) ->
    beam4pm_types:new_opportunity_currency_contract(#{
        opportunity_id => <<"sample_opportunity_id">>,
        currency_code => <<"sample_currency_code">>,
        fx_basis_id => <<"sample_fx_basis_id">>
    });
sample(opportunity_value_range, full) ->
    beam4pm_types:new_opportunity_value_range(#{
        opportunity_id => <<"sample_opportunity_id">>,
        minimum_value => <<"sample_minimum_value">>,
        maximum_value => <<"sample_maximum_value">>
    });
sample(opportunity_value_range, minimal) ->
    beam4pm_types:new_opportunity_value_range(#{
        opportunity_id => <<"sample_opportunity_id">>,
        minimum_value => <<"sample_minimum_value">>,
        maximum_value => <<"sample_maximum_value">>
    });
sample(order_form_admission, full) ->
    beam4pm_types:new_order_form_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        order_form_id => <<"sample_order_form_id">>,
        decision => <<"sample_decision">>
    });
sample(order_form_admission, minimal) ->
    beam4pm_types:new_order_form_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        order_form_id => <<"sample_order_form_id">>,
        decision => <<"sample_decision">>
    });
sample(overage_policy, full) ->
    beam4pm_types:new_overage_policy(#{
        policy_id => <<"sample_policy_id">>,
        quota_id => <<"sample_quota_id">>,
        unit_price => 3.5,
        behavior => sample_atom
    });
sample(overage_policy, minimal) ->
    beam4pm_types:new_overage_policy(#{
        policy_id => <<"sample_policy_id">>,
        quota_id => <<"sample_quota_id">>,
        unit_price => 3.5,
        behavior => sample_atom
    });
sample(path_schema, full) ->
    beam4pm_types:new_path_schema(#{
        schema_id => <<"sample_schema_id">>,
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        support => 42
    });
sample(path_schema, minimal) ->
    beam4pm_types:new_path_schema(#{
        schema_id => <<"sample_schema_id">>,
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        support => 42
    });
sample(path_schema_query, full) ->
    beam4pm_types:new_path_schema_query(#{
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        max_length => 42
    });
sample(path_schema_query, minimal) ->
    beam4pm_types:new_path_schema_query(#{
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        max_length => 42
    });
sample(payment_terms, full) ->
    beam4pm_types:new_payment_terms(#{
        terms_id => <<"sample_terms_id">>,
        net_days => 42,
        late_policy => <<"sample_late_policy">>,
        status => sample_atom
    });
sample(payment_terms, minimal) ->
    beam4pm_types:new_payment_terms(#{
        terms_id => <<"sample_terms_id">>,
        net_days => 42,
        late_policy => <<"sample_late_policy">>,
        status => sample_atom
    });
sample(payment_terms_admission, full) ->
    beam4pm_types:new_payment_terms_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        payment_terms => <<"sample_payment_terms">>,
        authority_evidence_hash => <<"sample_authority_evidence_hash">>
    });
sample(payment_terms_admission, minimal) ->
    beam4pm_types:new_payment_terms_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        payment_terms => <<"sample_payment_terms">>,
        authority_evidence_hash => <<"sample_authority_evidence_hash">>
    });
sample(petri_arc, full) ->
    beam4pm_types:new_petri_arc(#{
        source_id => <<"sample_source_id">>,
        target_id => <<"sample_target_id">>,
        weight => 42
    });
sample(petri_arc, minimal) ->
    beam4pm_types:new_petri_arc(#{
        source_id => <<"sample_source_id">>,
        target_id => <<"sample_target_id">>,
        weight => 42
    });
sample(petri_place, full) ->
    beam4pm_types:new_petri_place(#{
        place_id => <<"sample_place_id">>,
        tokens => 42
    });
sample(petri_place, minimal) ->
    beam4pm_types:new_petri_place(#{
        place_id => <<"sample_place_id">>,
        tokens => 42
    });
sample(petri_transition, full) ->
    beam4pm_types:new_petri_transition(#{
        transition_id => <<"sample_transition_id">>,
        label => <<"sample_label">>
    });
sample(petri_transition, minimal) ->
    beam4pm_types:new_petri_transition(#{
        transition_id => <<"sample_transition_id">>
    });
sample(planning_action, full) ->
    beam4pm_types:new_planning_action(#{
        action_name => <<"sample_action_name">>,
        preconditions => [<<"alpha">>, <<"beta">>],
        effects => [<<"alpha">>, <<"beta">>]
    });
sample(planning_action, minimal) ->
    beam4pm_types:new_planning_action(#{
        action_name => <<"sample_action_name">>
    });
sample(planning_state, full) ->
    beam4pm_types:new_planning_state(#{
        state_id => <<"sample_state_id">>,
        facts => [<<"alpha">>, <<"beta">>]
    });
sample(planning_state, minimal) ->
    beam4pm_types:new_planning_state(#{
        state_id => <<"sample_state_id">>,
        facts => [<<"alpha">>, <<"beta">>]
    });
sample(policy_decision, full) ->
    beam4pm_types:new_policy_decision(#{
        decision_id => <<"sample_decision_id">>,
        verdict => sample_atom,
        reason => <<"sample_reason">>
    });
sample(policy_decision, minimal) ->
    beam4pm_types:new_policy_decision(#{
        decision_id => <<"sample_decision_id">>,
        verdict => sample_atom
    });
sample(pricing_basis_contract, full) ->
    beam4pm_types:new_pricing_basis_contract(#{
        opportunity_id => <<"sample_opportunity_id">>,
        pricing_basis_id => <<"sample_pricing_basis_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(pricing_basis_contract, minimal) ->
    beam4pm_types:new_pricing_basis_contract(#{
        opportunity_id => <<"sample_opportunity_id">>,
        pricing_basis_id => <<"sample_pricing_basis_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(private_offer, full) ->
    beam4pm_types:new_private_offer(#{
        offer_id => <<"sample_offer_id">>,
        account_id => <<"sample_account_id">>,
        total_price => 3.5,
        expires_at => <<"2026-08-29T12:00:00Z">>
    });
sample(private_offer, minimal) ->
    beam4pm_types:new_private_offer(#{
        offer_id => <<"sample_offer_id">>,
        account_id => <<"sample_account_id">>,
        total_price => 3.5,
        expires_at => <<"2026-08-29T12:00:00Z">>
    });
sample(process_variant, full) ->
    beam4pm_types:new_process_variant(#{
        variant_id => <<"sample_variant_id">>,
        activity_sequence => [<<"alpha">>, <<"beta">>],
        frequency => 42
    });
sample(process_variant, minimal) ->
    beam4pm_types:new_process_variant(#{
        variant_id => <<"sample_variant_id">>,
        activity_sequence => [<<"alpha">>, <<"beta">>],
        frequency => 42
    });
sample(procurement_blocker, full) ->
    beam4pm_types:new_procurement_blocker(#{
        opportunity_id => <<"sample_opportunity_id">>,
        blocker_id => <<"sample_blocker_id">>,
        refusal_code => <<"sample_refusal_code">>
    });
sample(procurement_blocker, minimal) ->
    beam4pm_types:new_procurement_blocker(#{
        opportunity_id => <<"sample_opportunity_id">>,
        blocker_id => <<"sample_blocker_id">>,
        refusal_code => <<"sample_refusal_code">>
    });
sample(procurement_channel_selection, full) ->
    beam4pm_types:new_procurement_channel_selection(#{
        opportunity_id => <<"sample_opportunity_id">>,
        channel_id => <<"sample_channel_id">>,
        selection_evidence_hash => <<"sample_selection_evidence_hash">>
    });
sample(procurement_channel_selection, minimal) ->
    beam4pm_types:new_procurement_channel_selection(#{
        opportunity_id => <<"sample_opportunity_id">>,
        channel_id => <<"sample_channel_id">>,
        selection_evidence_hash => <<"sample_selection_evidence_hash">>
    });
sample(proof_of_value_budget, full) ->
    beam4pm_types:new_proof_of_value_budget(#{
        opportunity_id => <<"sample_opportunity_id">>,
        budget_id => <<"sample_budget_id">>,
        decision => <<"sample_decision">>
    });
sample(proof_of_value_budget, minimal) ->
    beam4pm_types:new_proof_of_value_budget(#{
        opportunity_id => <<"sample_opportunity_id">>,
        budget_id => <<"sample_budget_id">>,
        decision => <<"sample_decision">>
    });
sample(proof_of_value_exit_gate, full) ->
    beam4pm_types:new_proof_of_value_exit_gate(#{
        pov_id => <<"sample_pov_id">>,
        exit_gate_id => <<"sample_exit_gate_id">>,
        decision => <<"sample_decision">>
    });
sample(proof_of_value_exit_gate, minimal) ->
    beam4pm_types:new_proof_of_value_exit_gate(#{
        pov_id => <<"sample_pov_id">>,
        exit_gate_id => <<"sample_exit_gate_id">>,
        decision => <<"sample_decision">>
    });
sample(purchase_order_binding, full) ->
    beam4pm_types:new_purchase_order_binding(#{
        binding_id => <<"sample_binding_id">>,
        order_id => <<"sample_order_id">>,
        purchase_order_number => <<"sample_purchase_order_number">>,
        status => sample_atom
    });
sample(purchase_order_binding, minimal) ->
    beam4pm_types:new_purchase_order_binding(#{
        binding_id => <<"sample_binding_id">>,
        order_id => <<"sample_order_id">>,
        purchase_order_number => <<"sample_purchase_order_number">>,
        status => sample_atom
    });
sample(purchase_order_requirement, full) ->
    beam4pm_types:new_purchase_order_requirement(#{
        opportunity_id => <<"sample_opportunity_id">>,
        requirement_id => <<"sample_requirement_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(purchase_order_requirement, minimal) ->
    beam4pm_types:new_purchase_order_requirement(#{
        opportunity_id => <<"sample_opportunity_id">>,
        requirement_id => <<"sample_requirement_id">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(purchasing_entity_identity, full) ->
    beam4pm_types:new_purchasing_entity_identity(#{
        opportunity_id => <<"sample_opportunity_id">>,
        purchasing_entity_id => <<"sample_purchasing_entity_id">>,
        identity_evidence_hash => <<"sample_identity_evidence_hash">>
    });
sample(purchasing_entity_identity, minimal) ->
    beam4pm_types:new_purchasing_entity_identity(#{
        opportunity_id => <<"sample_opportunity_id">>,
        purchasing_entity_id => <<"sample_purchasing_entity_id">>,
        identity_evidence_hash => <<"sample_identity_evidence_hash">>
    });
sample(queue_snapshot, full) ->
    beam4pm_types:new_queue_snapshot(#{
        queue_name => <<"sample_queue_name">>,
        depth => 42,
        observed_at => <<"2026-08-29T12:00:00Z">>
    });
sample(queue_snapshot, minimal) ->
    beam4pm_types:new_queue_snapshot(#{
        queue_name => <<"sample_queue_name">>,
        depth => 42,
        observed_at => <<"2026-08-29T12:00:00Z">>
    });
sample(quota_policy, full) ->
    beam4pm_types:new_quota_policy(#{
        quota_id => <<"sample_quota_id">>,
        metric_name => <<"sample_metric_name">>,
        limit => 3.5,
        window => sample_atom
    });
sample(quota_policy, minimal) ->
    beam4pm_types:new_quota_policy(#{
        quota_id => <<"sample_quota_id">>,
        metric_name => <<"sample_metric_name">>,
        limit => 3.5,
        window => sample_atom
    });
sample(ramp_commitment, full) ->
    beam4pm_types:new_ramp_commitment(#{
        ramp_id => <<"sample_ramp_id">>,
        phase => 42,
        committed_amount => 3.5,
        effective_at => <<"2026-08-29T12:00:00Z">>
    });
sample(ramp_commitment, minimal) ->
    beam4pm_types:new_ramp_commitment(#{
        ramp_id => <<"sample_ramp_id">>,
        phase => 42,
        committed_amount => 3.5,
        effective_at => <<"2026-08-29T12:00:00Z">>
    });
sample(renewal_option, full) ->
    beam4pm_types:new_renewal_option(#{
        option_id => <<"sample_option_id">>,
        subscription_id => <<"sample_subscription_id">>,
        term_months => 42,
        notice_by => <<"2026-08-29T12:00:00Z">>
    });
sample(renewal_option, minimal) ->
    beam4pm_types:new_renewal_option(#{
        option_id => <<"sample_option_id">>,
        subscription_id => <<"sample_subscription_id">>,
        term_months => 42,
        notice_by => <<"2026-08-29T12:00:00Z">>
    });
sample(renewal_term_admission, full) ->
    beam4pm_types:new_renewal_term_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        renewal_term => <<"sample_renewal_term">>,
        decision => <<"sample_decision">>
    });
sample(renewal_term_admission, minimal) ->
    beam4pm_types:new_renewal_term_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        renewal_term => <<"sample_renewal_term">>,
        decision => <<"sample_decision">>
    });
sample(reseller_authorization, full) ->
    beam4pm_types:new_reseller_authorization(#{
        authorization_id => <<"sample_authorization_id">>,
        reseller_id => <<"sample_reseller_id">>,
        sku => <<"sample_sku">>,
        status => sample_atom
    });
sample(reseller_authorization, minimal) ->
    beam4pm_types:new_reseller_authorization(#{
        authorization_id => <<"sample_authorization_id">>,
        reseller_id => <<"sample_reseller_id">>,
        sku => <<"sample_sku">>,
        status => sample_atom
    });
sample(resource_allocation, full) ->
    beam4pm_types:new_resource_allocation(#{
        resource_id => <<"sample_resource_id">>,
        activity => <<"sample_activity">>,
        event_id => <<"sample_event_id">>
    });
sample(resource_allocation, minimal) ->
    beam4pm_types:new_resource_allocation(#{
        resource_id => <<"sample_resource_id">>,
        activity => <<"sample_activity">>,
        event_id => <<"sample_event_id">>
    });
sample(revenue_contract_admission, full) ->
    beam4pm_types:new_revenue_contract_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        contract_id => <<"sample_contract_id">>,
        admission_receipt_hash => <<"sample_admission_receipt_hash">>
    });
sample(revenue_contract_admission, minimal) ->
    beam4pm_types:new_revenue_contract_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        contract_id => <<"sample_contract_id">>,
        admission_receipt_hash => <<"sample_admission_receipt_hash">>
    });
sample(revenue_schedule_assumption, full) ->
    beam4pm_types:new_revenue_schedule_assumption(#{
        opportunity_id => <<"sample_opportunity_id">>,
        schedule_id => <<"sample_schedule_id">>,
        assumption_evidence_hash => <<"sample_assumption_evidence_hash">>
    });
sample(revenue_schedule_assumption, minimal) ->
    beam4pm_types:new_revenue_schedule_assumption(#{
        opportunity_id => <<"sample_opportunity_id">>,
        schedule_id => <<"sample_schedule_id">>,
        assumption_evidence_hash => <<"sample_assumption_evidence_hash">>
    });
sample(sanctions_screening_result, full) ->
    beam4pm_types:new_sanctions_screening_result(#{
        account_id => <<"sample_account_id">>,
        screening_id => <<"sample_screening_id">>,
        screening_result => <<"sample_screening_result">>
    });
sample(sanctions_screening_result, minimal) ->
    beam4pm_types:new_sanctions_screening_result(#{
        account_id => <<"sample_account_id">>,
        screening_id => <<"sample_screening_id">>,
        screening_result => <<"sample_screening_result">>
    });
sample(security_addendum_state, full) ->
    beam4pm_types:new_security_addendum_state(#{
        opportunity_id => <<"sample_opportunity_id">>,
        addendum_id => <<"sample_addendum_id">>,
        addendum_state => <<"sample_addendum_state">>
    });
sample(security_addendum_state, minimal) ->
    beam4pm_types:new_security_addendum_state(#{
        opportunity_id => <<"sample_opportunity_id">>,
        addendum_id => <<"sample_addendum_id">>,
        addendum_state => <<"sample_addendum_state">>
    });
sample(security_blocker, full) ->
    beam4pm_types:new_security_blocker(#{
        opportunity_id => <<"sample_opportunity_id">>,
        blocker_id => <<"sample_blocker_id">>,
        refusal_code => <<"sample_refusal_code">>
    });
sample(security_blocker, minimal) ->
    beam4pm_types:new_security_blocker(#{
        opportunity_id => <<"sample_opportunity_id">>,
        blocker_id => <<"sample_blocker_id">>,
        refusal_code => <<"sample_refusal_code">>
    });
sample(service_credit, full) ->
    beam4pm_types:new_service_credit(#{
        credit_id => <<"sample_credit_id">>,
        slo_id => <<"sample_slo_id">>,
        amount => 3.5,
        currency => <<"sample_currency">>
    });
sample(service_credit, minimal) ->
    beam4pm_types:new_service_credit(#{
        credit_id => <<"sample_credit_id">>,
        slo_id => <<"sample_slo_id">>,
        amount => 3.5,
        currency => <<"sample_currency">>
    });
sample(service_credit_admission, full) ->
    beam4pm_types:new_service_credit_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        service_credit_id => <<"sample_service_credit_id">>,
        decision => <<"sample_decision">>
    });
sample(service_credit_admission, minimal) ->
    beam4pm_types:new_service_credit_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        service_credit_id => <<"sample_service_credit_id">>,
        decision => <<"sample_decision">>
    });
sample(service_level_objective, full) ->
    beam4pm_types:new_service_level_objective(#{
        slo_id => <<"sample_slo_id">>,
        contract_id => <<"sample_contract_id">>,
        target_percent => 3.5,
        measurement_window => sample_atom
    });
sample(service_level_objective, minimal) ->
    beam4pm_types:new_service_level_objective(#{
        slo_id => <<"sample_slo_id">>,
        contract_id => <<"sample_contract_id">>,
        target_percent => 3.5,
        measurement_window => sample_atom
    });
sample(service_span, full) ->
    beam4pm_types:new_service_span(#{
        span_id => <<"sample_span_id">>,
        service_name => <<"sample_service_name">>,
        duration_ms => 42,
        parent_span_id => <<"sample_parent_span_id">>
    });
sample(service_span, minimal) ->
    beam4pm_types:new_service_span(#{
        span_id => <<"sample_span_id">>,
        service_name => <<"sample_service_name">>,
        duration_ms => 42
    });
sample(showback_allocation, full) ->
    beam4pm_types:new_showback_allocation(#{
        allocation_id => <<"sample_allocation_id">>,
        project_id => <<"sample_project_id">>,
        metric_name => <<"sample_metric_name">>,
        quantity => 3.5
    });
sample(showback_allocation, minimal) ->
    beam4pm_types:new_showback_allocation(#{
        allocation_id => <<"sample_allocation_id">>,
        project_id => <<"sample_project_id">>,
        metric_name => <<"sample_metric_name">>,
        quantity => 3.5
    });
sample(sku_definition, full) ->
    beam4pm_types:new_sku_definition(#{
        sku => <<"sample_sku">>,
        edition_id => <<"sample_edition_id">>,
        billing_model => sample_atom,
        status => sample_atom
    });
sample(sku_definition, minimal) ->
    beam4pm_types:new_sku_definition(#{
        sku => <<"sample_sku">>,
        edition_id => <<"sample_edition_id">>,
        billing_model => sample_atom,
        status => sample_atom
    });
sample(sla_offer_admission, full) ->
    beam4pm_types:new_sla_offer_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        sla_offer_id => <<"sample_sla_offer_id">>,
        decision => <<"sample_decision">>
    });
sample(sla_offer_admission, minimal) ->
    beam4pm_types:new_sla_offer_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        sla_offer_id => <<"sample_sla_offer_id">>,
        decision => <<"sample_decision">>
    });
sample(sojourn_time, full) ->
    beam4pm_types:new_sojourn_time(#{
        object_id => <<"sample_object_id">>,
        event_type => <<"sample_event_type">>,
        seconds => 3.5
    });
sample(sojourn_time, minimal) ->
    beam4pm_types:new_sojourn_time(#{
        object_id => <<"sample_object_id">>,
        event_type => <<"sample_event_type">>,
        seconds => 3.5
    });
sample(support_contract, full) ->
    beam4pm_types:new_support_contract(#{
        contract_id => <<"sample_contract_id">>,
        account_id => <<"sample_account_id">>,
        tier => sample_atom,
        valid_until => <<"2026-08-29T12:00:00Z">>
    });
sample(support_contract, minimal) ->
    beam4pm_types:new_support_contract(#{
        contract_id => <<"sample_contract_id">>,
        account_id => <<"sample_account_id">>,
        tier => sample_atom,
        valid_until => <<"2026-08-29T12:00:00Z">>
    });
sample(support_tier_admission, full) ->
    beam4pm_types:new_support_tier_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        support_tier_id => <<"sample_support_tier_id">>,
        decision => <<"sample_decision">>
    });
sample(support_tier_admission, minimal) ->
    beam4pm_types:new_support_tier_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        support_tier_id => <<"sample_support_tier_id">>,
        decision => <<"sample_decision">>
    });
sample(sync_time, full) ->
    beam4pm_types:new_sync_time(#{
        object_id => <<"sample_object_id">>,
        delaying_object_id => <<"sample_delaying_object_id">>,
        seconds => 3.5
    });
sample(sync_time, minimal) ->
    beam4pm_types:new_sync_time(#{
        object_id => <<"sample_object_id">>,
        seconds => 3.5
    });
sample(tax_jurisdiction_evidence, full) ->
    beam4pm_types:new_tax_jurisdiction_evidence(#{
        contracting_entity_id => <<"sample_contracting_entity_id">>,
        tax_jurisdiction => <<"sample_tax_jurisdiction">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(tax_jurisdiction_evidence, minimal) ->
    beam4pm_types:new_tax_jurisdiction_evidence(#{
        contracting_entity_id => <<"sample_contracting_entity_id">>,
        tax_jurisdiction => <<"sample_tax_jurisdiction">>,
        evidence_hash => <<"sample_evidence_hash">>
    });
sample(technical_blocker, full) ->
    beam4pm_types:new_technical_blocker(#{
        opportunity_id => <<"sample_opportunity_id">>,
        blocker_id => <<"sample_blocker_id">>,
        refusal_code => <<"sample_refusal_code">>
    });
sample(technical_blocker, minimal) ->
    beam4pm_types:new_technical_blocker(#{
        opportunity_id => <<"sample_opportunity_id">>,
        blocker_id => <<"sample_blocker_id">>,
        refusal_code => <<"sample_refusal_code">>
    });
sample(tenant_account, full) ->
    beam4pm_types:new_tenant_account(#{
        tenant_id => <<"sample_tenant_id">>,
        account_id => <<"sample_account_id">>,
        home_region => <<"sample_home_region">>,
        edition_id => <<"sample_edition_id">>
    });
sample(tenant_account, minimal) ->
    beam4pm_types:new_tenant_account(#{
        tenant_id => <<"sample_tenant_id">>,
        account_id => <<"sample_account_id">>,
        home_region => <<"sample_home_region">>,
        edition_id => <<"sample_edition_id">>
    });
sample(tenant_project, full) ->
    beam4pm_types:new_tenant_project(#{
        project_id => <<"sample_project_id">>,
        tenant_id => <<"sample_tenant_id">>,
        cost_center => <<"sample_cost_center">>,
        status => sample_atom
    });
sample(tenant_project, minimal) ->
    beam4pm_types:new_tenant_project(#{
        project_id => <<"sample_project_id">>,
        tenant_id => <<"sample_tenant_id">>,
        cost_center => <<"sample_cost_center">>,
        status => sample_atom
    });
sample(term_subscription, full) ->
    beam4pm_types:new_term_subscription(#{
        subscription_id => <<"sample_subscription_id">>,
        sku => <<"sample_sku">>,
        starts_at => <<"2026-08-29T12:00:00Z">>,
        ends_at => <<"2026-08-29T12:00:00Z">>
    });
sample(term_subscription, minimal) ->
    beam4pm_types:new_term_subscription(#{
        subscription_id => <<"sample_subscription_id">>,
        sku => <<"sample_sku">>,
        starts_at => <<"2026-08-29T12:00:00Z">>,
        ends_at => <<"2026-08-29T12:00:00Z">>
    });
sample(termination_right_admission, full) ->
    beam4pm_types:new_termination_right_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        termination_right_id => <<"sample_termination_right_id">>,
        decision => <<"sample_decision">>
    });
sample(termination_right_admission, minimal) ->
    beam4pm_types:new_termination_right_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        termination_right_id => <<"sample_termination_right_id">>,
        decision => <<"sample_decision">>
    });
sample(training_scope_admission, full) ->
    beam4pm_types:new_training_scope_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        training_scope_id => <<"sample_training_scope_id">>,
        decision => <<"sample_decision">>
    });
sample(training_scope_admission, minimal) ->
    beam4pm_types:new_training_scope_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        training_scope_id => <<"sample_training_scope_id">>,
        decision => <<"sample_decision">>
    });
sample(true_up_policy, full) ->
    beam4pm_types:new_true_up_policy(#{
        policy_id => <<"sample_policy_id">>,
        commitment_id => <<"sample_commitment_id">>,
        cadence => sample_atom,
        shortfall_behavior => sample_atom
    });
sample(true_up_policy, minimal) ->
    beam4pm_types:new_true_up_policy(#{
        policy_id => <<"sample_policy_id">>,
        commitment_id => <<"sample_commitment_id">>,
        cadence => sample_atom,
        shortfall_behavior => sample_atom
    });
sample(type_edge, full) ->
    beam4pm_types:new_type_edge(#{
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        qualifier => <<"sample_qualifier">>,
        direction => sample_atom
    });
sample(type_edge, minimal) ->
    beam4pm_types:new_type_edge(#{
        source_type => <<"sample_source_type">>,
        target_type => <<"sample_target_type">>,
        qualifier => <<"sample_qualifier">>,
        direction => sample_atom
    });
sample(usage_event, full) ->
    beam4pm_types:new_usage_event(#{
        event_id => <<"sample_event_id">>,
        entitlement_id => <<"sample_entitlement_id">>,
        quantity => 3.5,
        metric_name => <<"sample_metric_name">>,
        occurred_at => <<"2026-08-29T12:00:00Z">>
    });
sample(usage_event, minimal) ->
    beam4pm_types:new_usage_event(#{
        event_id => <<"sample_event_id">>,
        entitlement_id => <<"sample_entitlement_id">>,
        quantity => 3.5,
        metric_name => <<"sample_metric_name">>,
        occurred_at => <<"2026-08-29T12:00:00Z">>
    });
sample(usage_plan, full) ->
    beam4pm_types:new_usage_plan(#{
        plan_id => <<"sample_plan_id">>,
        metric_name => <<"sample_metric_name">>,
        unit => <<"sample_unit">>,
        billing_mode => sample_atom
    });
sample(usage_plan, minimal) ->
    beam4pm_types:new_usage_plan(#{
        plan_id => <<"sample_plan_id">>,
        metric_name => <<"sample_metric_name">>,
        unit => <<"sample_unit">>,
        billing_mode => sample_atom
    });
sample(value_baseline, full) ->
    beam4pm_types:new_value_baseline(#{
        baseline_id => <<"sample_baseline_id">>,
        account_id => <<"sample_account_id">>,
        metric_name => <<"sample_metric_name">>,
        baseline_value => 3.5
    });
sample(value_baseline, minimal) ->
    beam4pm_types:new_value_baseline(#{
        baseline_id => <<"sample_baseline_id">>,
        account_id => <<"sample_account_id">>,
        metric_name => <<"sample_metric_name">>,
        baseline_value => 3.5
    });
sample(value_realization, full) ->
    beam4pm_types:new_value_realization(#{
        realization_id => <<"sample_realization_id">>,
        baseline_id => <<"sample_baseline_id">>,
        realized_value => 3.5,
        measured_at => <<"2026-08-29T12:00:00Z">>
    });
sample(value_realization, minimal) ->
    beam4pm_types:new_value_realization(#{
        realization_id => <<"sample_realization_id">>,
        baseline_id => <<"sample_baseline_id">>,
        realized_value => 3.5,
        measured_at => <<"2026-08-29T12:00:00Z">>
    });
sample(vendor_registration_state, full) ->
    beam4pm_types:new_vendor_registration_state(#{
        account_id => <<"sample_account_id">>,
        registration_id => <<"sample_registration_id">>,
        registration_state => <<"sample_registration_state">>
    });
sample(vendor_registration_state, minimal) ->
    beam4pm_types:new_vendor_registration_state(#{
        account_id => <<"sample_account_id">>,
        registration_id => <<"sample_registration_id">>,
        registration_state => <<"sample_registration_state">>
    });
sample(volume_tier_admission, full) ->
    beam4pm_types:new_volume_tier_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        volume_tier_id => <<"sample_volume_tier_id">>,
        decision => <<"sample_decision">>
    });
sample(volume_tier_admission, minimal) ->
    beam4pm_types:new_volume_tier_admission(#{
        opportunity_id => <<"sample_opportunity_id">>,
        volume_tier_id => <<"sample_volume_tier_id">>,
        decision => <<"sample_decision">>
    });
sample(Name, Variant) ->
    erlang:error({unknown_sample, Name, Variant}).

%% Write every record x variant sample as Dir/<record>.<variant>.erl.json.
-spec write_samples(file:filename_all()) -> ok.
write_samples(Dir) ->
    ok = filelib:ensure_path(Dir),
    lists:foreach(
        fun({Name, Variant}) ->
            {ok, Rec} = sample(Name, Variant),
            Json = beam4pm_codec:encode(Rec),
            Path = filename:join(Dir, sample_basename(Name, Variant, "erl")),
            ok = file:write_file(Path, Json)
        end,
        pairs()),
    ok.

%% Read every record x variant fixture Dir/<record>.<variant>.<Suffix>.json,
%% decode it, and compare its canonical map against this module's own sample.
-spec verify_samples(file:filename_all(), string()) ->
    {non_neg_integer(), [string()]}.
verify_samples(Dir, Suffix) ->
    lists:foldl(
        fun({Name, Variant}, {Pass, Failures}) ->
            Label = atom_to_list(Name) ++ "." ++ atom_to_list(Variant),
            Path = filename:join(Dir, sample_basename(Name, Variant, Suffix)),
            {ok, Expected} = sample(Name, Variant),
            case file:read_file(Path) of
                {ok, Bin} ->
                    case beam4pm_codec:decode(Name, Bin) of
                        {ok, Decoded} ->
                            case beam4pm_codec:to_map(Decoded) =:= beam4pm_codec:to_map(Expected) of
                                true -> {Pass + 1, Failures};
                                false -> {Pass, Failures ++ [Label ++ ": map mismatch"]}
                            end;
                        {error, Reason} ->
                            {Pass, Failures ++ [Label ++ ": decode error " ++ format_term(Reason)]}
                    end;
                {error, Reason} ->
                    {Pass, Failures ++ [Label ++ ": read error " ++ format_term(Reason)]}
            end
        end,
        {0, []},
        pairs()).

%% internal

pairs() ->
    [{Name, Variant} || Name <- record_names(), Variant <- [full, minimal]].

sample_basename(Name, Variant, Suffix) ->
    atom_to_list(Name) ++ "." ++ atom_to_list(Variant) ++ "." ++ Suffix ++ ".json".

format_term(Term) ->
    lists:flatten(io_lib:format("~0p", [Term])).
