%% GENERATED by ggen from the admitted bpm:Engine graph (tract). Do not edit.
%%
%% beam4pm_tract: thin Erlang facade over the tract native engine --
%% A real ONNX-inference engine (sonos/tract -- the same crate Wasmtime's own WASI-NN implementation uses for this exact target, native/tract-wasm): graph optimization, the compiled runnable plan and the actual tensor ops all happen inside the wasm module; this side only frames base64 ONNX bytes and JSON tensor descriptors. A model is compiled to a runnable plan at load time, so a malformed or unsupported-op ONNX file fails loudly at load, never on first inference; only f32 tensors are supported and anything else is refused explicitly, never coerced.
%%
%% The engine is compiled to wasm32-wasip1 and hosted inside BEAM by
%% Elixir/wasmex ('Elixir.BeamPM.Tract', lib/beam4pm_tract.ex); this
%% module, that wrapper and the Gleam facade gleam/src/beam4pm/tract.gleam
%% are all rendered from the same admitted bpm:Engine / bpm:EngineOp /
%% bpm:EngineArg facts.
%%
%% Wire contract: every function here delegates 1:1 to the same-named
%% function on 'Elixir.BeamPM.Tract' and returns its result unchanged --
%% {ok, Map} | {error, Reason}, where Map is the JSON-decoded engine
%% response with binary keys. Model handles are plain integers minted
%% by the wasm engine; they are process-lifetime and are ALL invalidated
%% when the Wasmex engine process restarts. No computation happens in
%% Erlang: this module is a facade over the single tract wasm engine.
%%
%% Arity variants: an op whose Elixir head has an optional positional or a
%% keyword-list option (bpm:ArgMode_optional / bpm:ArgMode_keyword) is
%% exported at both its minimal arity (Elixir's default-argument head) and
%% one arity higher taking that value explicitly, since Erlang has no
%% default-argument or keyword-list sugar.
%%
%% Why there is no beam4pm_tract_tests.erl: eunit runs under rebar3 (root
%% rebar.config), which compiles src/ WITHOUT Mix dependencies, so wasmex is
%% not on rebar3's code path. This facade is exercised for real from ExUnit
%% (test/beam4pm_tract_facades_test.exs), in the Mix context.

-module(beam4pm_tract).

-export([start/0,
         load_model/1,
         load_model_path/1,
         run/2,
         model_info/1,
         free_model/1]).

-type result() :: {ok, map()} | {error, term()}.
-type handle() :: non_neg_integer().
-type tensor() :: #{shape := [non_neg_integer()], data := [number()]}.

%% Start (or find already-started) the named Wasmex engine process.
-spec start() -> {ok, pid()} | {error, term()}.
start() -> 'Elixir.BeamPM.Tract':start().

%% `{"op":"load_model","model_b64":...}` -- `model_bytes` is the raw ONNX protobuf (base64-encoded host-side; JSON strings cannot carry raw protobuf). Optimizes and compiles to a runnable plan immediately. `{:ok, %{"handle" => n, "inputs" => [%{"name" => s, "shape" => [dims|nil]}], "outputs" => [...]}}` -- a `nil` dim is a symbolic/dynamic axis tract could not fully resolve at load time, reported honestly rather than guessed.
-spec load_model(binary()) -> result().
load_model(ModelBytes) ->
    'Elixir.BeamPM.Tract':load_model(ModelBytes).

%% `File.read!/1` host-side, then `load_model/2` (raises if the path is absent).
-spec load_model_path(binary()) -> result().
load_model_path(Path) ->
    'Elixir.BeamPM.Tract':load_model_path(Path).

%% `{"op":"run","handle":h,"inputs":[{"shape":[dims],"data":[f32,...]}]}` -- one f32 tensor per declared model input, in order (`inputs` a list of `%{shape: [dims], data: [floats]}`, converted to the wire's string-keyed shape here). `{:ok, %{"outputs" => [%{"shape" => [dims], "data" => [floats]}]}}`, one per declared model output, in order. Real tensor inference, even on a tiny model, draws the heavy timeout budget.
-spec run(handle(), [tensor()]) -> result().
run(Handle, Inputs) ->
    'Elixir.BeamPM.Tract':run(Handle, Inputs).

%% `{"op":"model_info","handle":h}` -- same input/output fact shape as `load_model/2`.
-spec model_info(handle()) -> result().
model_info(Handle) ->
    'Elixir.BeamPM.Tract':model_info(Handle).

%% `{"op":"free_model","handle":h}` -- releases the model handle; subsequent use errors with an unknown-handle message.
-spec free_model(handle()) -> result().
free_model(Handle) ->
    'Elixir.BeamPM.Tract':free_model(Handle).
